Repository zed-industries/zed, pull requests merged in 2024-06, with the labels that each got.

#12514 Fix or promote leftover TODOs and GPUI APIs
  Cargo.toml
  assets/keymaps/default-linux.json
  crates/gpui/Cargo.toml
  crates/gpui/src/app.rs
  crates/gpui/src/platform.rs
  crates/gpui/src/platform/app_menu.rs
  crates/gpui/src/platform/blade/blade_renderer.rs
  crates/gpui/src/platform/linux.rs
  crates/gpui/src/platform/linux/dispatcher.rs
  crates/gpui/src/platform/linux/headless/client.rs
  crates/gpui/src/platform/linux/platform.rs
  crates/gpui/src/platform/linux/wayland/client.rs
  crates/gpui/src/platform/linux/wayland/display.rs
  crates/gpui/src/platform/linux/wayland/serial.rs
  crates/gpui/src/platform/linux/wayland/window.rs
  crates/gpui/src/platform/linux/x11/client.rs
  crates/gpui/src/platform/linux/x11/window.rs
  crates/gpui/src/platform/linux/x11/xim_handler.rs
  crates/gpui/src/platform/linux/xdg_desktop_portal.rs
  crates/gpui/src/platform/mac/platform.rs
  crates/gpui/src/platform/mac/window.rs
  crates/gpui/src/platform/test.rs
  crates/gpui/src/platform/test/text_system.rs
  crates/gpui/src/platform/test/window.rs
  crates/gpui/src/platform/windows/window.rs
  crates/gpui/src/window.rs
  crates/zed/src/zed.rs
Labels: cla-signed

#12118 JavaScript: Add runnable tests
  crates/languages/src/javascript/outline.scm
  crates/languages/src/javascript/runnables.scm
  crates/languages/src/lib.rs
  crates/languages/src/typescript.rs
  crates/languages/src/typescript/outline.scm
  crates/languages/src/typescript/runnables.scm
Labels: cla-signed

#12560 typescript: Add completions for tsconfig.json properties
  crates/languages/src/json.rs
  crates/languages/src/json/schemas/tsconfig.json
Labels: cla-signed

#12562 collab_ui: remove branch menu popover in favor of opening a modal
  crates/collab_ui/src/collab_titlebar_item.rs
  crates/recent_projects/src/recent_projects.rs
  crates/vcs_menu/src/lib.rs
Labels: cla-signed

#12451 python: Add runnable unittest tasks
  crates/languages/src/lib.rs
  crates/languages/src/python.rs
  crates/languages/src/python/runnables.scm
Labels: cla-signed, tasks

#12528 indent guides: Respect language specific settings in multibuffers
  crates/editor/src/editor.rs
  crates/editor/src/editor_tests.rs
  crates/editor/src/element.rs
  crates/editor/src/indent_guides.rs
  crates/language/src/buffer.rs
  crates/multi_buffer/src/multi_buffer.rs
Labels: cla-signed

#12571 Fix GPUI get_menus documentation
  crates/gpui/src/app.rs
Labels: cla-signed

#12584 Disable indent guides for single line editors
  crates/editor/src/editor.rs
Labels: cla-signed

#12512 Fix TSX and JavaScript shorthand property syntax highlighting
  crates/languages/src/javascript/highlights.scm
  crates/languages/src/tsx/highlights.scm
Labels: cla-signed

#12591 Change on remote setup and one more SSH command as example
  docs/src/remote-development.md
Labels: cla-signed

#12370 windows: Fix project prepare_ssh_shell to support setting PATH on Windows
  crates/project/src/terminals.rs
Labels: cla-signed

#12600 json: Fix tsconfig.json schema overriding other schemas (such as keymap)
  crates/languages/src/json.rs
Labels: cla-signed

#12601 task: Rebind UseSelectedQuery in modal to F2
  assets/keymaps/default-macos.json
  crates/tasks_ui/src/modal.rs
Labels: cla-signed

#12468 Start on a database-backed prompt library
  Cargo.lock
  Cargo.toml
  assets/icons/star.svg
  assets/icons/star_filled.svg
  assets/keymaps/default-linux.json
  assets/keymaps/default-macos.json
  crates/assistant/Cargo.toml
  crates/assistant/src/assistant.rs
  crates/assistant/src/assistant_panel.rs
  crates/assistant/src/prompt_library.rs
  crates/assistant/src/prompts.rs
  crates/assistant/src/prompts/prompt.rs
  crates/assistant/src/prompts/prompt_library.rs
  crates/assistant/src/prompts/prompt_manager.rs
  crates/assistant/src/slash_command/prompt_command.rs
  crates/editor/src/editor.rs
  crates/extensions_ui/src/extensions_ui.rs
  crates/gpui/src/elements/list.rs
  crates/gpui/src/elements/uniform_list.rs
  crates/language_tools/src/syntax_tree_view.rs
  crates/outline/src/outline.rs
  crates/picker/src/picker.rs
  crates/project_panel/src/project_panel.rs
  crates/ui/src/components/icon.rs
  crates/ui/src/components/keybinding.rs
Labels: cla-signed

#12604 linux/x11: Ignore bounds.origin on resize event
  crates/gpui/src/platform/linux/x11/window.rs
Labels: linux, cla-signed

#12597 Support formatting unsaved buffers with external formatter
  crates/project/src/project.rs
Labels: cla-signed

#12603 Fix XI2 Scrolling Issue
  crates/gpui/src/platform/linux/x11/client.rs
  crates/gpui/src/platform/linux/x11/window.rs
Labels: cla-signed

#12606 typescript: Add support for VTSLS
  crates/languages/src/lib.rs
  crates/languages/src/vtsls.rs
Labels: cla-signed

#12552 Add !vimwaiting to togglecomment
  assets/keymaps/vim.json
Labels: cla-signed

#12587 cosmic_text: Handle variation selectors; fix emoji colors
  crates/gpui/src/platform/cosmic_text/text_system.rs
Labels: cla-signed

#12581 wayland: Fix window bounds restoration
  crates/gpui/src/geometry.rs
  crates/gpui/src/platform/linux/wayland/client.rs
  crates/gpui/src/platform/linux/wayland/display.rs
  crates/gpui/src/platform/linux/wayland/window.rs
Labels: cla-signed

#12558 Fix terminal key bindings
  assets/keymaps/default-linux.json
  crates/terminal/src/mappings/keys.rs
Labels: cla-signed

#12611 Disable `vtsls` by default
  assets/settings/default.json
  crates/languages/src/vtsls.rs
Labels: cla-signed

#12612 Remove default language settings that are provided by extensions
  assets/settings/default.json
Labels: cla-signed

#12613 assistant: Allow `/rustdoc` to use local docs
  crates/assistant/src/slash_command/rustdoc_command.rs
Labels: cla-signed

#12614 Paginate through extensions from the blob store
  crates/collab/src/api/extensions.rs
Labels: cla-signed

#12619 Fix issues with Claude in Assistant2
  crates/assistant/src/assistant.rs
  crates/assistant/src/assistant_panel.rs
  crates/assistant/src/assistant_settings.rs
  crates/assistant/src/codegen.rs
  crates/assistant/src/completion_provider.rs
  crates/assistant/src/completion_provider/anthropic.rs
  crates/assistant/src/completion_provider/cloud.rs
  crates/assistant/src/completion_provider/open_ai.rs
  crates/editor/src/editor.rs
  crates/editor/src/element.rs
  crates/editor/src/hunk_diff.rs
Labels: cla-signed

#12615 linux watcher
  crates/assistant/src/assistant_panel.rs
  crates/extension/src/extension_store.rs
  crates/fs/src/fs.rs
  crates/settings/src/settings_file.rs
  crates/worktree/src/worktree.rs
  crates/zed/src/main.rs
Labels: cla-signed

#12620 Fix excluded file creation
  Cargo.lock
  crates/collab/Cargo.toml
  crates/collab/src/tests/integration_tests.rs
  crates/gpui/src/platform/cosmic_text/text_system.rs
  crates/project/src/project.rs
  crates/project/src/project_tests.rs
  crates/project_panel/Cargo.toml
  crates/project_panel/src/project_panel.rs
  crates/terminal_view/src/terminal_view.rs
  crates/workspace/src/notifications.rs
  crates/worktree/src/worktree.rs
  crates/worktree/src/worktree_tests.rs
Labels: cla-signed

#12630 editor: Cancel ongoing completion requests more eagerly
  crates/editor/src/debounced_delay.rs
  crates/editor/src/editor.rs
Labels: cla-signed

#12645 assistant: Add `/fetch` slash command
  crates/assistant/src/assistant.rs
  crates/assistant/src/slash_command.rs
  crates/assistant/src/slash_command/fetch_command.rs
  crates/rustdoc_to_markdown/src/rustdoc_to_markdown.rs
Labels: cla-signed

#12647 Polish prompt library UX
  Cargo.lock
  assets/icons/zed_assistant_filled.svg
  crates/assistant/Cargo.toml
  crates/assistant/src/assistant.rs
  crates/assistant/src/assistant_panel.rs
  crates/assistant/src/prompt_library.rs
  crates/assistant/src/slash_command.rs
  crates/assistant/src/slash_command/active_command.rs
  crates/assistant/src/slash_command/default_command.rs
  crates/assistant/src/slash_command/fetch_command.rs
  crates/assistant/src/slash_command/file_command.rs
  crates/assistant/src/slash_command/project_command.rs
  crates/assistant/src/slash_command/prompt_command.rs
  crates/assistant/src/slash_command/rustdoc_command.rs
  crates/assistant/src/slash_command/search_command.rs
  crates/assistant/src/slash_command/tabs_command.rs
  crates/assistant_slash_command/src/assistant_slash_command.rs
  crates/extension/src/extension_slash_command.rs
  crates/gpui/src/platform/mac/window.rs
  crates/picker/src/picker.rs
  crates/ui/src/components/icon.rs
  crates/ui/src/components/list/list_sub_header.rs
Labels: cla-signed

#12646 vcs_menu: Fix header taking up too much space
  crates/vcs_menu/src/lib.rs
Labels: cla-signed

#12651 Fix a bug where the IME pre-edit would desync from Zed
  crates/gpui/src/platform/mac/window.rs
Labels: cla-signed

#12652 Allow restarting remote language servers
  crates/collab/src/rpc.rs
  crates/project/src/project.rs
  crates/rpc/proto/zed.proto
  crates/rpc/src/proto.rs
  crates/text/src/text.rs
Labels: cla-signed

#12653 Make HTML to Markdown conversion more pluggable
  Cargo.lock
  Cargo.toml
  crates/assistant/Cargo.toml
  crates/assistant/src/slash_command/fetch_command.rs
  crates/assistant/src/slash_command/rustdoc_command.rs
  crates/html_to_markdown/Cargo.toml
  crates/html_to_markdown/LICENSE-GPL
  crates/html_to_markdown/examples/test.rs
  crates/html_to_markdown/src/html_element.rs
  crates/html_to_markdown/src/html_to_markdown.rs
  crates/html_to_markdown/src/markdown.rs
  crates/html_to_markdown/src/markdown_writer.rs
  crates/html_to_markdown/src/structure.rs
  crates/html_to_markdown/src/structure/rustdoc.rs
  crates/rustdoc_to_markdown/src/markdown_writer.rs
Labels: cla-signed

#11482 vue: Improve syntax highlighting
  extensions/vue/languages/vue/highlights.scm
  extensions/vue/languages/vue/injections.scm
Labels: cla-signed

#12430 Implement Indent & Outdent as operators
  assets/keymaps/vim.json
  crates/gpui/src/keymap/context.rs
  crates/vim/src/normal.rs
  crates/vim/src/normal/indent.rs
  crates/vim/src/state.rs
  crates/vim/src/test.rs
  crates/vim/src/vim.rs
Labels: cla-signed

#12656 vue: Bump to v0.0.3
  Cargo.lock
  extensions/vue/Cargo.toml
  extensions/vue/extension.toml
Labels: cla-signed

#12654 Always open the project panel for dev server projects
  crates/project/src/project.rs
  crates/project_panel/src/project_panel.rs
  crates/terminal_view/src/terminal_panel.rs
  crates/zed/src/zed.rs
Labels: cla-signed

#12622 Update linux binary expectations
  crates/cli/src/main.rs
  crates/zed/Cargo.toml
  crates/zed/resources/flatpak/manifest-template.json
  docs/src/development/linux.md
  script/bundle-linux
  script/bundle-mac
  script/install.sh
  script/zed-local
Labels: cla-signed

#12658 html_to_markdown: Remove unused examples
  crates/html_to_markdown/examples/test.rs
Labels: cla-signed

#12660 Auto updater disabler
  crates/auto_update/src/auto_update.rs
  crates/cli/src/main.rs
  docs/src/development/linux.md
Labels: cla-signed

#12662 Add note about auto-updating on Linux
  assets/settings/default.json
Labels: cla-signed

#12671 Omit clickable hunks when git hunks are disabled in the gutter
  crates/editor/src/element.rs
Labels: cla-signed

#12674 Autocomplete commands that don't require access to workspace in prompt library
  crates/assistant/src/assistant_panel.rs
  crates/assistant/src/prompt_library.rs
  crates/assistant/src/slash_command.rs
  crates/assistant/src/slash_command/active_command.rs
  crates/assistant/src/slash_command/default_command.rs
  crates/assistant/src/slash_command/fetch_command.rs
  crates/assistant/src/slash_command/file_command.rs
  crates/assistant/src/slash_command/project_command.rs
  crates/assistant/src/slash_command/prompt_command.rs
  crates/assistant/src/slash_command/rustdoc_command.rs
  crates/assistant/src/slash_command/search_command.rs
  crates/assistant/src/slash_command/tabs_command.rs
  crates/assistant_slash_command/src/assistant_slash_command.rs
  crates/extension/src/extension_slash_command.rs
Labels: cla-signed

#12677 Do not occlude terminal pane by terminal element
  crates/terminal_view/src/terminal_element.rs
Labels: cla-signed

#11954 editor: Render boundary whitespace
  crates/editor/src/element.rs
  crates/language/src/language_settings.rs
Labels: cla-signed

#12680 Allow using the inline assistant in prompt library
  crates/assistant/src/assistant.rs
  crates/assistant/src/assistant_panel.rs
  crates/assistant/src/codegen.rs
  crates/assistant/src/inline_assistant.rs
  crates/assistant/src/prompt_library.rs
  crates/gpui/src/window.rs
Labels: cla-signed

#12683 Support wrapping and hard newlines in inline assistant
  crates/assistant/src/inline_assistant.rs
  crates/editor/src/display_map.rs
  crates/editor/src/display_map/block_map.rs
  crates/editor/src/editor.rs
Labels: cla-signed

#12684 Cancel inline assist editor on blur if it wasn't confirmed
  crates/assistant/src/inline_assistant.rs
Labels: cla-signed

#12686 Polish prompt library some more
  crates/assistant/src/prompt_library.rs
  crates/editor/src/editor.rs
  crates/editor/src/hunk_diff.rs
Labels: cla-signed

#12687 Bump alacritty to fix some file descriptor yuck
  Cargo.lock
  crates/terminal/Cargo.toml
Labels: cla-signed

#12697 html_to_markdown: Move `TableHandler` out of `rustdoc`
  crates/html_to_markdown/src/html_to_markdown.rs
  crates/html_to_markdown/src/markdown.rs
  crates/html_to_markdown/src/structure/rustdoc.rs
Labels: cla-signed

#12650 Add ability to scroll popovers with vim
  crates/editor/src/hover_links.rs
  crates/editor/src/hover_popover.rs
  crates/editor/src/scroll/scroll_amount.rs
  crates/gpui/src/elements/div.rs
  crates/vim/src/normal/scroll.rs
Labels: cla-signed

#10831 Search in selections
  assets/icons/search_selection.svg
  assets/keymaps/default-linux.json
  assets/keymaps/default-macos.json
  crates/editor/src/editor.rs
  crates/editor/src/items.rs
  crates/editor/src/selections_collection.rs
  crates/language_tools/src/lsp_log.rs
  crates/multi_buffer/src/multi_buffer.rs
  crates/search/src/buffer_search.rs
  crates/search/src/search.rs
  crates/terminal_view/src/terminal_view.rs
  crates/ui/src/components/icon.rs
  crates/workspace/src/searchable.rs
Labels: cla-signed

#12607 vim: Fix `g _` not having the expected behavior
  crates/vim/src/motion.rs
  crates/vim/test_data/test_end_of_line_downward.json
Labels: cla-signed

#12699 Don't show backtraces in prompts
  crates/call/src/room.rs
  crates/workspace/src/notifications.rs
Labels: cla-signed

#12640 lsp: Handle responses in background thread
  crates/lsp/src/input_handler.rs
  crates/lsp/src/lsp.rs
Labels: cla-signed

#12701 assistant: Initialize the UI font in the prompt library window
  crates/assistant/src/prompt_library.rs
Labels: cla-signed

#12702 Adjust IME action buffering to only apply to insert actions
  crates/gpui/src/platform/mac/window.rs
Labels: cla-signed

#12499 editor: Add ToggleTabBar action
  crates/editor/src/actions.rs
  crates/editor/src/editor.rs
  crates/editor/src/element.rs
Labels: cla-signed

#12689 Update prompt library styles
  assets/icons/sparkle.svg
  assets/icons/sparkle_filled.svg
  crates/assistant/src/prompt_library.rs
  crates/picker/src/picker.rs
  crates/ui/src/components/icon.rs
Labels: cla-signed

#12714 Fix ordering of keyboard shortcuts so that you can use AI on linux
  assets/keymaps/default-linux.json
  script/linux
Labels: cla-signed

#12717 Update the whitespace docs in the default settings file
  assets/settings/default.json
  crates/language/src/language_settings.rs
Labels: cla-signed

#12716 Fixed default LSP default settings for `JavaScript`, `TypeScript` & `TSX`
  assets/settings/default.json
Labels: cla-signed

#12718 Fix key-bindings doc typo
  docs/src/key-bindings.md
Labels: cla-signed

#12710 chore: added inl to cpp config
  assets/icons/file_icons/file_types.json
  crates/languages/src/cpp/config.toml
Labels: cla-signed

#12632 linux/x11: Don't surround selection when XMI composing
  crates/editor/src/editor.rs
Labels: cla-signed

#12721 Improve UX for saved contexts
  crates/assistant/src/assistant.rs
  crates/assistant/src/assistant_panel.rs
  crates/assistant/src/conversation_store.rs
  crates/assistant/src/saved_conversation.rs
Labels: cla-signed

#12724 Rename conversations to contexts
  assets/keymaps/default-linux.json
  assets/keymaps/default-macos.json
  crates/assistant/src/assistant.rs
  crates/assistant/src/assistant_panel.rs
  crates/assistant/src/context_store.rs
  crates/assistant/src/inline_assistant.rs
  crates/assistant/src/slash_command.rs
  crates/util/src/paths.rs
Labels: cla-signed

#12727 chore: Fix clippy for upcoming 1.79 Rust release
  crates/collab/src/tests/randomized_test_helpers.rs
  crates/color/src/color.rs
  crates/editor/src/hover_links.rs
  crates/editor/src/hover_popover.rs
  crates/gpui/src/platform/mac/display_link.rs
  crates/gpui/src/taffy.rs
  crates/language/src/syntax_map.rs
  crates/project/src/project.rs
  crates/project/src/project_settings.rs
  crates/project/src/project_tests.rs
  crates/workspace/src/workspace.rs
Labels: cla-signed

#12700 Use cwd to run package.json script
  crates/languages/src/json.rs
Labels: cla-signed

#12735 docs: Fix Vim documentation for bindings
  docs/src/vim.md
Labels: cla-signed

#12729 Prevent folder expansion when all items are closed
  crates/workspace/src/pane.rs
Labels: cla-signed

#12582 Maintain cursor to upper line in visual mode indent/outdent
  crates/vim/src/normal.rs
  crates/vim/src/test.rs
Labels: cla-signed

#12741 astro: Fix Tailwind LS not working in attributes
  extensions/astro/languages/astro/overrides.scm
Labels: cla-signed

#12742 ruby: Allow opt-in to Tailwind LS in string
  extensions/ruby/languages/ruby/config.toml
Labels: cla-signed

#12743 ruby: Bump version to 0.0.7
  extensions/ruby/extension.toml
Labels: cla-signed

#12744 astro: Bump version to 0.0.3
  extensions/astro/extension.toml
Labels: cla-signed

#12418 Use rust-analyzer from path if possible
  crates/languages/src/c.rs
  crates/languages/src/go.rs
  crates/languages/src/rust.rs
  crates/project/src/project_settings.rs
Labels: cla-signed

#12767 workspace: Fix drag&dropping project panel entries into editor area
  crates/project_panel/src/project_panel.rs
  crates/workspace/src/pane.rs
Labels: cla-signed

#12762 docs: Document how to setup Tailwind CSS support in Ruby
  docs/src/languages/ruby.md
Labels: cla-signed

#12777 Add basic Wikipedia support to `/fetch`
  crates/assistant/src/slash_command/fetch_command.rs
  crates/html_to_markdown/src/html_to_markdown.rs
  crates/html_to_markdown/src/markdown.rs
  crates/html_to_markdown/src/structure.rs
  crates/html_to_markdown/src/structure/wikipedia.rs
Labels: cla-signed

#12780 Handle Wikipedia code blocks in `/fetch` command
  crates/assistant/src/slash_command/fetch_command.rs
  crates/html_to_markdown/src/markdown_writer.rs
  crates/html_to_markdown/src/structure/wikipedia.rs
Labels: cla-signed

#12781 Check validity of new.range too
  crates/diagnostics/src/diagnostics.rs
Labels: cla-signed

#12784 Block publishing of `zed_extension_api` v0.0.7
  crates/extension_api/Cargo.toml
Labels: cla-signed

#12785 Add event for yarn project identification
  crates/project/src/project.rs
Labels: cla-signed

#12782 vim: Add gU/gu/g~
  assets/keymaps/vim.json
  crates/vim/src/normal.rs
  crates/vim/src/normal/case.rs
  crates/vim/src/state.rs
  crates/vim/src/vim.rs
  crates/vim/test_data/test_change_case_motion.json
Labels: cla-signed

#12787 Use the new assistant icon in the setup instructions
  crates/assistant/src/completion_provider/anthropic.rs
  crates/assistant/src/completion_provider/open_ai.rs
Labels: cla-signed

#12775 Refactor: Make it possible to share a remote worktree
  Cargo.lock
  crates/client/src/client.rs
  crates/collab/src/tests/editor_tests.rs
  crates/collab/src/tests/integration_tests.rs
  crates/project/src/project.rs
  crates/project/src/project_tests.rs
  crates/rpc/src/peer.rs
  crates/semantic_index/src/semantic_index.rs
  crates/settings/src/settings_store.rs
  crates/terminal_view/src/terminal_view.rs
  crates/util/src/paths.rs
  crates/worktree/Cargo.toml
  crates/worktree/src/worktree.rs
  crates/worktree/src/worktree_settings.rs
  crates/worktree/src/worktree_tests.rs
Labels: cla-signed

#12789 vim: add guu gUU g~~ g/
  assets/keymaps/vim.json
  crates/gpui/src/keymap/context.rs
  docs/src/vim.md
Labels: cla-signed

#12672 Rename `workspace::Restart` action into `workspace::Reload`
  crates/activity_indicator/src/activity_indicator.rs
  crates/collab_ui/src/collab_titlebar_item.rs
  crates/workspace/src/workspace.rs
Labels: cla-signed

#12751 cpp: Highlight sized type specifiers as keywords
  crates/languages/src/cpp/highlights.scm
Labels: cla-signed

#12792 Add auto-completion support for `package.json` files
  crates/languages/src/json.rs
  crates/languages/src/json/schemas/package.json
Labels: cla-signed

#12839 linux: run runnables only when event loop is idle
  crates/gpui/src/platform/linux/wayland/client.rs
  crates/gpui/src/platform/linux/x11/client.rs
Labels: cla-signed

#12840 linux/x11: handle XIM events sync to reduce lag
  crates/gpui/src/platform/linux/x11/client.rs
  crates/gpui/src/platform/linux/x11/xim_handler.rs
Labels: cla-signed

#12642 ruby: Remove outline for running tests
  extensions/ruby/languages/ruby/outline.scm
  extensions/ruby/languages/ruby/runnables.scm
  extensions/ruby/languages/ruby/tasks.json
Labels: cla-signed

#12856 assistant: Add `/now` slash command
  crates/assistant/src/assistant.rs
  crates/assistant/src/slash_command.rs
  crates/assistant/src/slash_command/now_command.rs
Labels: cla-signed

#12857 Show extension download counts with thousands separators
  Cargo.lock
  Cargo.toml
  crates/extensions_ui/Cargo.toml
  crates/extensions_ui/src/extensions_ui.rs
Labels: cla-signed

#12861 Fix target of proto diff on CI
  .github/workflows/ci.yml
Labels: cla-signed

#12863 Add missing LICENSE file to `proto` crate
  Cargo.toml
  crates/proto/LICENSE-GPL
Labels: cla-signed

#12860 Remove unused `color` crate
  Cargo.lock
  Cargo.toml
  crates/color/Cargo.toml
  crates/color/LICENSE-GPL
  crates/color/src/color.rs
  crates/theme/Cargo.toml
Labels: cla-signed

#12864 assistant: Improve JSON handling in `/fetch` command
  crates/assistant/src/slash_command/fetch_command.rs
Labels: cla-signed

#12858 Update EULA
  script/eula/eula.md
  script/eula/eula.rtf
Labels: cla-signed

#12859 Update windows doc to mention rust-lld linker error
  docs/src/development/windows.md
Labels: cla-signed

#12669 Reconnect button for remote projects
  Cargo.lock
  crates/collab/Cargo.toml
  crates/collab/src/tests/dev_server_tests.rs
  crates/collab/src/tests/editor_tests.rs
  crates/collab_ui/src/collab_titlebar_item.rs
  crates/project/src/project.rs
  crates/project/src/terminals.rs
  crates/project_panel/src/project_panel.rs
  crates/recent_projects/Cargo.toml
  crates/recent_projects/src/dev_servers.rs
  crates/recent_projects/src/disconnected_overlay.rs
  crates/recent_projects/src/recent_projects.rs
  crates/workspace/src/modal_layer.rs
  crates/workspace/src/persistence.rs
  crates/workspace/src/workspace.rs
Labels: cla-signed

#12871 Wait for composition to end before sending InputIgnored
  crates/editor/src/editor.rs
Labels: cla-signed

#12870 linux make install
  .github/workflows/ci.yml
  docs/src/development/linux.md
  script/bundle-linux
  script/install-linux
  script/install.sh
Labels: cla-signed

#12879 linux/x11: Only create ModifiersChanged event if they changed
  crates/gpui/src/platform/linux/x11/client.rs
Labels: cla-signed

#12846 Overhaul inline assistant
  Cargo.lock
  Cargo.toml
  assets/icons/context.svg
  assets/icons/rotate_cw.svg
  assets/icons/stop.svg
  crates/assistant/Cargo.toml
  crates/assistant/src/assistant_panel.rs
  crates/assistant/src/inline_assistant.rs
  crates/editor/src/display_map.rs
  crates/editor/src/editor.rs
  crates/editor/src/element.rs
  crates/language/Cargo.toml
  crates/language/src/buffer.rs
  crates/ui/src/components/icon.rs
Labels: cla-signed

#12889 Remove headers from prompt library picker
  crates/assistant/src/inline_assistant.rs
  crates/assistant/src/prompt_library.rs
  crates/editor/src/editor.rs
  crates/text/src/selection.rs
Labels: cla-signed

#12873 Fix most vim tests on linux
  Cargo.lock
  crates/editor/Cargo.toml
  crates/editor/src/editor_tests.rs
  crates/editor/src/test/editor_lsp_test_context.rs
Labels: cla-signed

#12869 Pull app / OS info out of GPUI, add Linux information, make fallible window initialization
  Cargo.lock
  Cargo.toml
  crates/assistant/src/prompt_library.rs
  crates/channel/src/channel_store_tests.rs
  crates/client/Cargo.toml
  crates/client/src/telemetry.rs
  crates/collab/src/api/events.rs
  crates/collab/src/tests/test_server.rs
  crates/collab_ui/src/notifications/project_shared_notification.rs
  crates/editor/src/editor_tests.rs
  crates/editor/src/inlay_hint_cache.rs
  crates/extension/src/extension_store_test.rs
  crates/feedback/src/feedback.rs
  crates/feedback/src/feedback_modal.rs
  crates/feedback/src/system_specs.rs
  crates/gpui/Cargo.toml
  crates/gpui/examples/animation.rs
  crates/gpui/examples/hello_world.rs
  crates/gpui/examples/image/image.rs
  crates/gpui/examples/set_menus.rs
  crates/gpui/examples/window_positioning.rs
  crates/gpui/src/app.rs
  crates/gpui/src/app/async_context.rs
  crates/gpui/src/app/test_context.rs
  crates/gpui/src/interactive.rs
  crates/gpui/src/platform.rs
  crates/gpui/src/platform/linux/headless/client.rs
  crates/gpui/src/platform/linux/platform.rs
  crates/gpui/src/platform/linux/wayland/client.rs
  crates/gpui/src/platform/linux/wayland/window.rs
  crates/gpui/src/platform/linux/x11/client.rs
  crates/gpui/src/platform/linux/x11/window.rs
  crates/gpui/src/platform/mac/platform.rs
  crates/gpui/src/platform/test/platform.rs
  crates/gpui/src/platform/windows/platform.rs
  crates/gpui/src/window.rs
  crates/language_tools/src/lsp_log_tests.rs
  crates/lsp/src/lsp.rs
  crates/markdown/examples/markdown.rs
  crates/project/src/project_tests.rs
  crates/project_symbols/src/project_symbols.rs
  crates/release_channel/src/lib.rs
  crates/telemetry_events/src/telemetry_events.rs
  crates/vim/src/test/vim_test_context.rs
  crates/welcome/src/welcome.rs
  crates/workspace/src/workspace.rs
  crates/zed/Cargo.toml
  crates/zed/src/main.rs
  crates/zed/src/reliability.rs
  crates/zed/src/zed.rs
Labels: cla-signed

#12901 Hoist `indexmap` to workspace level
  Cargo.toml
  crates/theme/Cargo.toml
  crates/theme_importer/Cargo.toml
Labels: cla-signed

#12903 Add tag handler for collecting crate items from rustdoc output
  Cargo.lock
  crates/assistant/src/slash_command/fetch_command.rs
  crates/assistant/src/slash_command/rustdoc_command.rs
  crates/html_to_markdown/Cargo.toml
  crates/html_to_markdown/src/html_to_markdown.rs
  crates/html_to_markdown/src/markdown_writer.rs
  crates/html_to_markdown/src/structure/rustdoc.rs
  crates/html_to_markdown/src/structure/wikipedia.rs
Labels: cla-signed

#12912 Fix alt key getting stuck when tabbing on linux
  crates/gpui/src/platform/linux/wayland/client.rs
Labels: cla-signed

#12910 project_panel: Don't show file icon during rename when file icons are otherwise hidden
  crates/project_panel/src/project_panel.rs
Labels: cla-signed

#12902 Ollama Provider for Assistant
  Cargo.lock
  Cargo.toml
  crates/assistant/Cargo.toml
  crates/assistant/src/assistant.rs
  crates/assistant/src/assistant_settings.rs
  crates/assistant/src/completion_provider.rs
  crates/assistant/src/completion_provider/ollama.rs
  crates/ollama/Cargo.toml
  crates/ollama/src/ollama.rs
Labels: cla-signed

#12914 Fix cursors on some GNOME installations
  crates/gpui/src/platform/linux/wayland/client.rs
  crates/gpui/src/platform/linux/wayland/cursor.rs
  crates/gpui/src/platform/linux/x11/client.rs
  crates/gpui/src/platform/linux/xdg_desktop_portal.rs
Labels: cla-signed

#12899 Make install.sh sh-compatible
  script/install.sh
Labels: cla-signed

#12756 linux: Use filesystem based unix socket instead of abstract namespace
  Cargo.lock
  crates/cli/Cargo.toml
  crates/cli/src/main.rs
  crates/zed/src/zed/open_listener.rs
Labels: cla-signed

#12922 Added TSX test runnables
  crates/languages/src/lib.rs
  crates/languages/src/tsx/runnables.scm
  crates/languages/src/typescript.rs
Labels: cla-signed

#12932 Wrap JS/TS runnables in quotes
  crates/languages/src/typescript.rs
Labels: cla-signed

#12935 Make notification windows not have titles on X11
  crates/gpui/src/platform/linux/x11/window.rs
  crates/zed/src/main.rs
  script/zed-local
Labels: cla-signed

#12895 vim: Implement named registers
  assets/keymaps/vim.json
  crates/editor/src/editor.rs
  crates/gpui/src/keymap/context.rs
  crates/vim/src/mode_indicator.rs
  crates/vim/src/normal/paste.rs
  crates/vim/src/state.rs
  crates/vim/src/test/neovim_backed_test_context.rs
  crates/vim/src/utils.rs
  crates/vim/src/vim.rs
  crates/vim/test_data/test_named_registers.json
  crates/vim/test_data/test_numbered_registers.json
  crates/vim/test_data/test_special_registers.json
  docs/src/vim.md
Labels: cla-signed

#12943 Add missing LICENSE file to `ollama` crate
  crates/ollama/Cargo.toml
  crates/ollama/LICENSE-GPL
Labels: cla-signed

#12942 Start on rustdoc crawler
  Cargo.lock
  Cargo.toml
  crates/html_to_markdown/src/html_to_markdown.rs
  crates/html_to_markdown/src/structure/rustdoc.rs
  crates/rustdoc/Cargo.toml
  crates/rustdoc/LICENSE-GPL
  crates/rustdoc/src/crawler.rs
  crates/rustdoc/src/rustdoc.rs
Labels: cla-signed

#12945 Move rustdoc-related code to `rustdoc` crate
  Cargo.lock
  crates/assistant/Cargo.toml
  crates/assistant/src/slash_command/rustdoc_command.rs
  crates/html_to_markdown/Cargo.toml
  crates/html_to_markdown/src/html_element.rs
  crates/html_to_markdown/src/html_to_markdown.rs
  crates/html_to_markdown/src/markdown.rs
  crates/html_to_markdown/src/markdown_writer.rs
  crates/html_to_markdown/src/structure.rs
  crates/html_to_markdown/src/structure/rustdoc.rs
  crates/html_to_markdown/src/structure/wikipedia.rs
  crates/rustdoc/Cargo.toml
  crates/rustdoc/src/crawler.rs
  crates/rustdoc/src/item.rs
  crates/rustdoc/src/rustdoc.rs
  crates/rustdoc/src/to_markdown.rs
Labels: cla-signed

#12924 Add libgit2 build dependency to Arch-based distros
  script/linux
Labels: cla-signed

#12637 Introduce an outline panel
  Cargo.lock
  Cargo.toml
  assets/icons/list_tree.svg
  assets/keymaps/default-linux.json
  assets/keymaps/default-macos.json
  assets/settings/default.json
  crates/editor/src/editor.rs
  crates/fuzzy/src/char_bag.rs
  crates/git/src/repository.rs
  crates/gpui/src/color.rs
  crates/gpui/src/style.rs
  crates/language/src/buffer.rs
  crates/language/src/language.rs
  crates/language/src/outline.rs
  crates/multi_buffer/src/multi_buffer.rs
  crates/outline/Cargo.toml
  crates/outline/src/outline.rs
  crates/outline_panel/Cargo.toml
  crates/outline_panel/LICENSE-GPL
  crates/outline_panel/src/outline_panel.rs
  crates/outline_panel/src/outline_panel_settings.rs
  crates/ui/src/components/icon.rs
  crates/worktree/src/worktree.rs
  crates/zed/Cargo.toml
  crates/zed/src/main.rs
  crates/zed/src/zed.rs
  crates/zed/src/zed/app_menus.rs
Labels: cla-signed

#12944 Use clang+mold on linux
  .cargo/config.toml
  script/linux
Labels: cla-signed

#12952 assistant: Add MVP for `/rustdoc` using indexed docs
  Cargo.lock
  crates/assistant/src/assistant.rs
  crates/assistant/src/slash_command/rustdoc_command.rs
  crates/rustdoc/Cargo.toml
  crates/rustdoc/src/crawler.rs
  crates/rustdoc/src/item.rs
  crates/rustdoc/src/rustdoc.rs
  crates/rustdoc/src/store.rs
Labels: cla-signed

#12950 Reveal the selected item when cycling a picker's selection
  crates/file_finder/Cargo.toml
  crates/file_finder/src/file_finder_tests.rs
  crates/gpui/src/elements/uniform_list.rs
  crates/picker/Cargo.toml
  crates/picker/src/picker.rs
Labels: cla-signed

#12951 zed.desktop.in: Don't hardcode executable name due to binary conflicts
  crates/zed/resources/zed.desktop.in
  script/bundle-linux
  script/flatpak/bundle-flatpak
Labels: cla-signed

#12958 Docs to help people find their way back
  docs/src/vim.md
Labels: cla-signed

#12939 Refine inline transformation UX
  crates/assistant/src/assistant_panel.rs
  crates/assistant/src/inline_assistant.rs
  crates/assistant/src/prompt_library.rs
  crates/collab_ui/src/channel_view.rs
  crates/editor/src/editor.rs
  crates/editor/src/editor_tests.rs
  crates/editor/src/element.rs
  crates/editor/src/hunk_diff.rs
  crates/editor/src/items.rs
  crates/extensions_ui/src/extensions_ui.rs
  crates/feedback/src/feedback_modal.rs
  crates/go_to_line/src/go_to_line.rs
  crates/gpui/src/subscription.rs
  crates/markdown_preview/src/markdown_preview_view.rs
  crates/multi_buffer/src/multi_buffer.rs
  crates/outline/src/outline.rs
  crates/search/src/buffer_search.rs
  crates/text/src/text.rs
  crates/vim/src/vim.rs
  crates/zed/src/zed/inline_completion_registry.rs
Labels: cla-signed

#12964 Add mold package for opensuse, arch, void and gentoo
  script/linux
Labels: cla-signed

#12978 Fix typo error in flatpak script
  script/flatpak/bundle-flatpak
Labels: cla-signed

#12928 chore: Bump lsp-types to 0.97.0
  Cargo.lock
  crates/collab/src/tests/editor_tests.rs
  crates/collab/src/tests/integration_tests.rs
  crates/collab/src/tests/random_project_collaboration_tests.rs
  crates/copilot/src/copilot.rs
  crates/copilot/src/copilot_completion_provider.rs
  crates/copilot/src/request.rs
  crates/editor/src/editor.rs
  crates/editor/src/editor_tests.rs
  crates/editor/src/hover_links.rs
  crates/editor/src/hover_popover.rs
  crates/editor/src/inlay_hint_cache.rs
  crates/editor/src/test/editor_lsp_test_context.rs
  crates/languages/src/rust.rs
  crates/lsp/Cargo.toml
  crates/lsp/src/lsp.rs
  crates/project/src/lsp_command.rs
  crates/project/src/lsp_ext_command.rs
  crates/project/src/project.rs
  crates/project/src/project_tests.rs
  crates/project_symbols/src/project_symbols.rs
  crates/vim/src/test.rs
Labels: cla-signed

#12893 lsp: Provide completion reason in the request
  crates/assistant/src/assistant_panel.rs
  crates/assistant/src/slash_command.rs
  crates/collab/src/tests/random_project_collaboration_tests.rs
  crates/collab_ui/src/chat_panel/message_editor.rs
  crates/editor/src/actions.rs
  crates/editor/src/editor.rs
  crates/editor/src/editor_tests.rs
  crates/extension/src/extension_store_test.rs
  crates/lsp/src/lsp.rs
  crates/project/src/lsp_command.rs
  crates/project/src/project.rs
  crates/project/src/project_tests.rs
Labels: cla-signed

#12960 Fix headless mode
  crates/zed/src/main.rs
  script/install.sh
Labels: cla-signed

#12961 Arm builds
  .cargo/config.toml
  .github/workflows/ci.yml
  script/generate-licenses
Labels: cla-signed

#12959 Add dependencies for Ubuntu/Debian
  script/linux
Labels: cla-signed

#12822 Update linux keybinds
  assets/keymaps/default-linux.json
Labels: cla-signed

#12994 Disable mic and screenshare buttons on non-macOS platforms
  crates/collab_ui/src/collab_titlebar_item.rs
  script/zed-local
Labels: cla-signed

#12995 worktree: Fix race condition when a root of worktree is .git directory
  crates/worktree/src/worktree.rs
Labels: cla-signed

#12972 Add missing Linux build dependencies
  script/linux
Labels: cla-signed

#12431 windows: Fix scrolling bug
  crates/gpui/src/platform/windows/events.rs
  crates/gpui/src/platform/windows/window.rs
Labels: cla-signed

#12991 Fix issues where screen and window sizes contained Pixels, but were declared as DevicePixels
  crates/assistant/src/prompt_library.rs
  crates/collab_ui/src/collab_ui.rs
  crates/editor/src/editor_tests.rs
  crates/gpui/examples/image/image.rs
  crates/gpui/examples/window_positioning.rs
  crates/gpui/src/geometry.rs
  crates/gpui/src/platform.rs
  crates/gpui/src/platform/blade/blade_renderer.rs
  crates/gpui/src/platform/linux/wayland/client.rs
  crates/gpui/src/platform/linux/wayland/display.rs
  crates/gpui/src/platform/linux/wayland/window.rs
  crates/gpui/src/platform/linux/x11/client.rs
  crates/gpui/src/platform/linux/x11/display.rs
  crates/gpui/src/platform/linux/x11/window.rs
  crates/gpui/src/platform/mac/display.rs
  crates/gpui/src/platform/mac/metal_renderer.rs
  crates/gpui/src/platform/mac/window.rs
  crates/gpui/src/platform/test/display.rs
  crates/gpui/src/platform/test/window.rs
  crates/gpui/src/platform/windows/display.rs
  crates/gpui/src/platform/windows/events.rs
  crates/gpui/src/platform/windows/window.rs
  crates/gpui/src/window.rs
  crates/workspace/src/persistence.rs
  crates/workspace/src/workspace.rs
Labels: cla-signed
