Repository zed-industries/zed, pull requests merged in 2024-03, with the labels that each got.

#8643 Remove ! from todo!() in comments
  .github/workflows/ci.yml
  Cargo.toml
  assets/keymaps/default-linux.json
  crates/assistant/src/assistant_panel.rs
  crates/cli/src/main.rs
  crates/collab/src/main.rs
  crates/collab_ui/src/collab_panel.rs
  crates/color/src/color.rs
  crates/editor/src/hover_popover.rs
  crates/fs/src/fs.rs
  crates/gpui/Cargo.toml
  crates/gpui/src/platform.rs
  crates/gpui/src/platform/blade/blade_renderer.rs
  crates/gpui/src/platform/linux/dispatcher.rs
  crates/gpui/src/platform/linux/platform.rs
  crates/gpui/src/platform/linux/text_system.rs
  crates/gpui/src/platform/linux/wayland.rs
  crates/gpui/src/platform/linux/wayland/client.rs
  crates/gpui/src/platform/linux/wayland/display.rs
  crates/gpui/src/platform/linux/wayland/window.rs
  crates/gpui/src/platform/linux/x11/window.rs
  crates/gpui/src/platform/test/platform.rs
  crates/gpui/src/platform/test/text_system.rs
  crates/gpui/src/scene.rs
  crates/gpui/src/style.rs
  crates/install_cli/src/install_cli.rs
  crates/languages/src/csharp.rs
  crates/languages/src/elixir.rs
  crates/languages/src/lua.rs
  crates/languages/src/purescript.rs
  crates/languages/src/rust.rs
  crates/languages/src/toml.rs
  crates/languages/src/zig.rs
  crates/live_kit_client/src/test.rs
  crates/terminal/src/terminal.rs
  crates/theme/src/one_themes.rs
  crates/theme/src/styles/colors.rs
  crates/time_format/src/time_format.rs
  crates/zed/src/main.rs
Labels: cla-signed

#8122 Zig outline view
  crates/languages/src/zig/highlights.scm
  crates/languages/src/zig/indents.scm
  crates/languages/src/zig/outline.scm
Labels: cla-signed

#8646 Wire up Azure OpenAI completion provider
  Cargo.lock
  assets/settings/default.json
  crates/ai/Cargo.toml
  crates/ai/src/providers/open_ai/completion.rs
  crates/assistant/src/assistant_panel.rs
  crates/assistant/src/assistant_settings.rs
  crates/client/src/telemetry.rs
Labels: cla-signed

#8647 Replace `lazy_static!` with `OnceLock` in `ai` crate
  Cargo.lock
  crates/ai/Cargo.toml
  crates/ai/src/providers/open_ai/embedding.rs
  crates/ai/src/providers/open_ai/model.rs
Labels: cla-signed

#8648 Replace `lazy_static!` with `OnceLock` in `time_format` crate
  Cargo.lock
  crates/time_format/Cargo.toml
  crates/time_format/src/time_format.rs
Labels: cla-signed

#8568 Implement workspace_configuration for Dart LSP
  crates/languages/src/dart.rs
Labels: cla-signed

#8329 Scroll project search results to the top
  crates/search/src/project_search.rs
Labels: cla-signed

#8591 Vim mode: make `motion::EndOfLine` works with times.
  crates/vim/src/motion.rs
  crates/vim/src/normal.rs
  crates/vim/src/test.rs
  crates/vim/test_data/test_end_of_line_with_neovim.json
Labels: cla-signed

#8677 Replace `lazy_static!` with `OnceLock` in `collab` crate
  crates/collab/Cargo.toml
  crates/collab/src/api/events.rs
  crates/collab/src/auth.rs
  crates/collab/src/rpc.rs
  crates/collab/src/tests/randomized_test_helpers.rs
Labels: cla-signed

#8673 Prompt to save files on recent project selection
  Cargo.lock
  crates/recent_projects/Cargo.toml
  crates/recent_projects/src/recent_projects.rs
  crates/tasks_ui/src/modal.rs
  crates/workspace/src/persistence/model.rs
Labels: cla-signed

#8649 Upload crashes to collab directly
  Cargo.lock
  Cargo.toml
  crates/collab/.env.toml
  crates/collab/Cargo.toml
  crates/collab/k8s/collab.template.yml
  crates/collab/src/api.rs
  crates/collab/src/api/events.rs
  crates/collab/src/api/ips_file.rs
  crates/collab/src/api/slack.rs
  crates/collab/src/lib.rs
  crates/collab/src/tests/test_server.rs
  crates/zed/src/main.rs
  script/seed-db
Labels: cla-signed

#8685 Make collab quieter on startup
  Procfile
  crates/collab/src/api/extensions.rs
  crates/collab/src/lib.rs
  script/bootstrap
  script/run-local-minio
Labels: cla-signed

#8559 Setting to show/hide terminal title
  assets/settings/default.json
  crates/terminal/src/terminal_settings.rs
  crates/terminal_view/src/terminal_view.rs
  docs/src/configuring_zed.md
Labels: cla-signed

#8688 Add a way to change what `menu::Confirm` does in the recent projects modal
  Cargo.lock
  assets/keymaps/default-linux.json
  assets/keymaps/default-macos.json
  crates/recent_projects/Cargo.toml
  crates/recent_projects/src/recent_projects.rs
  crates/zed/src/app_menus.rs
Labels: cla-signed

#8684 Allow reconnect before disconnect
  crates/collab/src/db/queries/buffers.rs
  crates/collab/src/db/queries/rooms.rs
  crates/collab/src/rpc.rs
  crates/collab/src/tests/following_tests.rs
  crates/collab/src/tests/test_server.rs
  crates/rpc/src/peer.rs
Labels: cla-signed

#8635 Fix documentation for use_system_clipboard
  crates/vim/src/vim.rs
Labels: cla-signed

#8544 Improve Ruby Grammar for superclasses
  crates/languages/src/ruby/highlights.scm
Labels: cla-signed

#8689 When clicking the checkbox, toggle open the LSP trace logs
  crates/language_tools/src/lsp_log.rs
Labels: cla-signed

#8655 Clean up and refactor X11 refresh loop (alternative)
  crates/gpui/Cargo.toml
  crates/gpui/src/platform/linux/platform.rs
  crates/gpui/src/platform/linux/x11/client.rs
  crates/gpui/src/platform/linux/x11/window.rs
Labels: cla-signed

#8664 Add Void Linux support to `script/linux`
  script/linux
Labels: cla-signed

#8690 docs: Fix "it's" typos that should be "its"
  crates/color/src/color.rs
  crates/editor/src/editor.rs
  crates/gpui/src/elements/div.rs
  crates/gpui/src/keymap/binding.rs
  crates/gpui/src/style.rs
  crates/gpui/src/styled.rs
  crates/gpui/src/text_system/line_layout.rs
  crates/language/src/language.rs
  crates/task/src/static_source.rs
  crates/terminal/src/terminal.rs
  crates/workspace/src/workspace.rs
Labels: cla-signed

#8692 Allow overriding player colors via `experimental.theme_overrides`
  crates/theme/src/registry.rs
  crates/theme/src/settings.rs
  crates/theme/src/styles/players.rs
Labels: cla-signed

#8693 Upgrade `bitflags` to v2.4.2
  Cargo.lock
  Cargo.toml
  crates/feedback/Cargo.toml
  crates/fsevent/Cargo.toml
  crates/fsevent/src/fsevent.rs
  crates/search/Cargo.toml
  crates/search/src/search.rs
Labels: cla-signed

#8694 Use long flags in `script/clippy` for readability
  script/clippy
Labels: cla-signed

#8695 Document `release_channel` crate
  crates/release_channel/src/lib.rs
Labels: cla-signed

#8697 Remove `expect`s when constructing Clickhouse client
  crates/collab/src/lib.rs
Labels: cla-signed

#8696 Fix Clippy warnings in `fs`
  crates/fs/src/fs.rs
  crates/fs/src/repository.rs
Labels: cla-signed

#8700 Fix Clippy warnings in `settings` crate
  crates/settings/src/settings_file.rs
  crates/settings/src/settings_store.rs
Labels: cla-signed

#8698 Remove unneeded `'static` lifetimes on `&str`s in constants
  crates/ai/src/providers/open_ai.rs
  crates/collab/src/db.rs
  crates/collab/src/db/tests/feature_flag_tests.rs
  crates/collab/src/main.rs
  crates/collab/src/tests/integration_tests.rs
  crates/collab_ui/src/chat_panel.rs
  crates/collab_ui/src/collab_panel.rs
  crates/collab_ui/src/notification_panel.rs
  crates/copilot/src/copilot.rs
  crates/copilot_ui/src/sign_in.rs
  crates/db/src/db.rs
  crates/editor/src/editor.rs
  crates/gpui/src/platform/mac/metal_renderer.rs
  crates/languages/src/astro.rs
  crates/languages/src/css.rs
  crates/languages/src/dockerfile.rs
  crates/languages/src/elm.rs
  crates/languages/src/html.rs
  crates/languages/src/json.rs
  crates/languages/src/prisma.rs
  crates/languages/src/purescript.rs
  crates/languages/src/python.rs
  crates/languages/src/svelte.rs
  crates/languages/src/tailwind.rs
  crates/languages/src/yaml.rs
  crates/project_core/src/worktree_tests.rs
  crates/project_panel/src/file_associations.rs
  crates/project_panel/src/project_panel.rs
  crates/rpc/src/notification.rs
  crates/terminal_view/src/terminal_panel.rs
  crates/ui/src/components/stories/list_item.rs
  crates/vim/src/object.rs
Labels: cla-signed

#8701 Fix Clippy warnings in `fuzzy` crate
  crates/fuzzy/src/char_bag.rs
  crates/fuzzy/src/paths.rs
  crates/fuzzy/src/strings.rs
Labels: cla-signed

#8691 Fix unsafe precondition violation when building with nightly `rustc`
  crates/gpui/src/platform/mac/platform.rs
Labels: cla-signed

#8356 Expose more errors from rust-analyzer on invalid Cargo.toml contents
  crates/lsp/src/lsp.rs
  crates/project/src/project.rs
  crates/workspace/src/notifications.rs
Labels: cla-signed

#8715 Fix Clippy warnings in `theme` crate
  crates/theme/src/one_themes.rs
  crates/theme/src/registry.rs
  crates/theme/src/schema.rs
  crates/theme/src/settings.rs
  crates/theme/src/styles/players.rs
Labels: cla-signed

#8710 Add flex_wrap_* and content_* to GPUI
  crates/gpui/src/styled.rs
Labels: cla-signed

#8719 Fix Clippy warnings in `client` crate
  crates/client/src/client.rs
  crates/client/src/telemetry.rs
  crates/client/src/user.rs
Labels: cla-signed

#8721 Fix Clippy warnings in `util` crate
  crates/util/src/http.rs
  crates/util/src/paths.rs
  crates/util/src/test.rs
  crates/util/src/test/marked_text.rs
Labels: cla-signed

#8722 Add `cargo xtask clippy`
  .cargo/ci-config.toml
  .cargo/config.toml
  Cargo.lock
  Cargo.toml
  crates/cli/Cargo.toml
  crates/storybook/Cargo.toml
  crates/theme_importer/Cargo.toml
  script/clippy
  tooling/xtask/Cargo.toml
  tooling/xtask/LICENSE-GPL
  tooling/xtask/src/main.rs
Labels: cla-signed

#8720 Deny all Clippy warnings
  .github/workflows/ci.yml
  .github/workflows/deploy_collab.yml
  .github/workflows/release_nightly.yml
  crates/gpui/build.rs
  tooling/xtask/src/main.rs
Labels: cla-signed

#8723 Enable `clippy::bind_instead_of_map`
  crates/ai/src/prompts/base.rs
  crates/ai/src/prompts/repository_context.rs
  crates/language_tools/src/lsp_log.rs
  crates/workspace/src/workspace.rs
  tooling/xtask/src/main.rs
Labels: cla-signed

#8724 Enable `clippy::useless_conversion`
  crates/ai/src/embedding.rs
  crates/channel/src/channel_buffer.rs
  crates/channel/src/channel_chat.rs
  crates/collab/src/db.rs
  crates/editor/src/display_map/block_map.rs
  crates/editor/src/display_map/tab_map.rs
  crates/editor/src/editor.rs
  crates/editor/src/editor_tests.rs
  crates/editor/src/element.rs
  crates/editor/src/scroll.rs
  crates/language/src/outline.rs
  crates/language/src/syntax_map.rs
  crates/language_tools/src/syntax_tree_view.rs
  crates/lsp/src/lsp.rs
  crates/project/src/project.rs
  crates/storybook/src/stories/scroll.rs
  crates/terminal/src/mappings/mouse.rs
  crates/terminal/src/terminal.rs
  crates/terminal_view/src/terminal_element.rs
  crates/vim/src/motion.rs
  tooling/xtask/src/main.rs
Labels: cla-signed

#8726 terminal: Make `rgb_for_index` take a `u8` instead of a `&u8`
  crates/terminal/src/terminal.rs
Labels: cla-signed

#8727 Enable `clippy::single_char_pattern`
  crates/assistant/src/codegen.rs
  crates/channel/src/channel_store.rs
  crates/collab/src/db/tests.rs
  crates/collab_ui/src/chat_panel/message_editor.rs
  crates/editor/src/editor.rs
  crates/editor/src/git/permalink.rs
  crates/file_finder/src/file_finder.rs
  crates/gpui/src/app/test_context.rs
  crates/language/src/buffer_tests.rs
  crates/languages/src/ocaml.rs
  crates/languages/src/terraform.rs
  crates/lsp/src/lsp.rs
  crates/project_panel/src/project_panel.rs
  crates/semantic_index/src/semantic_index_tests.rs
  crates/vim/src/command.rs
  crates/vim/src/normal/paste.rs
  crates/vim/src/test/neovim_backed_test_context.rs
  crates/vim/src/test/neovim_connection.rs
  crates/workspace/src/pane.rs
  crates/workspace/src/workspace.rs
  crates/zed/src/open_listener.rs
  tooling/xtask/src/main.rs
Labels: cla-signed

#8728 Enable `clippy::clone_on_copy`
  crates/ai/src/prompts/repository_context.rs
  crates/assistant/src/assistant_panel.rs
  crates/call/src/call.rs
  crates/collab/src/tests/following_tests.rs
  crates/collab/src/tests/random_project_collaboration_tests.rs
  crates/collab_ui/src/channel_view.rs
  crates/collab_ui/src/collab_titlebar_item.rs
  crates/collab_ui/src/notifications/incoming_call_notification.rs
  crates/collab_ui/src/notifications/project_shared_notification.rs
  crates/diagnostics/src/diagnostics.rs
  crates/editor/src/display_map.rs
  crates/editor/src/display_map/fold_map.rs
  crates/editor/src/display_map/inlay_map.rs
  crates/editor/src/editor.rs
  crates/editor/src/hover_links.rs
  crates/editor/src/hover_popover.rs
  crates/editor/src/inlay_hint_cache.rs
  crates/editor/src/items.rs
  crates/editor/src/movement.rs
  crates/editor/src/selections_collection.rs
  crates/gpui/src/platform/mac/platform.rs
  crates/language/src/syntax_map.rs
  crates/lsp/src/lsp.rs
  crates/markdown_preview/src/markdown_parser.rs
  crates/multi_buffer/src/anchor.rs
  crates/multi_buffer/src/multi_buffer.rs
  crates/project/src/lsp_command.rs
  crates/project_core/src/worktree.rs
  crates/search/src/project_search.rs
  crates/semantic_index/src/db.rs
  crates/semantic_index/src/semantic_index.rs
  crates/storybook/src/storybook.rs
  crates/terminal/src/terminal.rs
  crates/terminal_view/src/terminal_element.rs
  crates/ui/src/components/right_click_menu.rs
  crates/vim/src/normal/repeat.rs
  crates/vim/src/test/vim_test_context.rs
  crates/vim/src/visual.rs
  crates/workspace/src/persistence.rs
  crates/workspace/src/workspace.rs
  crates/zed/src/zed.rs
  tooling/xtask/src/main.rs
Labels: cla-signed

#8730 Add license to Gleam extension
  extensions/gleam/Cargo.toml
  extensions/gleam/LICENSE-APACHE
Labels: cla-signed

#8731 Enable `clippy::map_identity`
  crates/lsp/src/lsp.rs
  crates/project/src/project.rs
  tooling/xtask/src/main.rs
Labels: cla-signed

#8732 Enable `clippy::to_string_in_format_args`
  crates/editor/src/movement.rs
  crates/editor/src/test/editor_test_context.rs
  tooling/xtask/src/main.rs
Labels: cla-signed

#8734 Enable `clippy::too_many_arguments`
  crates/assistant/src/assistant_panel.rs
  crates/collab/src/db/queries/messages.rs
  crates/collab/src/rpc.rs
  crates/collab/src/tests/randomized_test_helpers.rs
  crates/collab_ui/src/collab_titlebar_item.rs
  crates/editor/src/element.rs
  crates/language/src/syntax_map.rs
  crates/lsp/src/lsp.rs
  crates/project/src/project.rs
  crates/project_core/src/worktree.rs
  crates/rich_text/src/rich_text.rs
  crates/terminal/src/terminal.rs
  crates/workspace/src/pane_group.rs
  tooling/xtask/src/main.rs
Labels: cla-signed

#8737 Enable `clippy::manual_find`
  crates/prettier/src/prettier.rs
  tooling/xtask/src/main.rs
Labels: cla-signed

#8738 Enable `clippy::unnecessary_filter_map`
  crates/assistant/src/assistant_panel.rs
  crates/channel/src/channel_store.rs
  crates/collab/src/db/queries/channels.rs
  crates/collab_ui/src/collab_panel.rs
  crates/multi_buffer/src/multi_buffer.rs
  crates/zed/src/open_listener.rs
  tooling/xtask/src/main.rs
Labels: cla-signed

#8739 Enable `clippy::manual_flatten`
  crates/project_core/src/worktree.rs
  crates/semantic_index/src/db.rs
  crates/workspace/src/workspace.rs
  crates/zed/src/main.rs
  tooling/xtask/src/main.rs
Labels: cla-signed

#8740 Enable `clippy::unnecessary_find_map`
  crates/collab_ui/src/chat_panel.rs
  tooling/xtask/src/main.rs
Labels: cla-signed

#8741 Enable `clippy::filter_map_identity`
  crates/project/src/project.rs
  crates/recent_projects/src/recent_projects.rs
  tooling/xtask/src/main.rs
Labels: cla-signed

#8742 Enable `clippy::unit_arg`
  crates/gpui/src/platform/mac/platform.rs
  tooling/xtask/src/main.rs
Labels: cla-signed

#8743 Enable `clippy::needless_arbitrary_self_type`
  crates/editor/src/display_map.rs
  tooling/xtask/src/main.rs
Labels: cla-signed

#8745 Enable `clippy::drain_collect`
  crates/editor/src/element.rs
  tooling/xtask/src/main.rs
Labels: cla-signed

#8746 Enable `clippy::needless_borrowed_reference`
  crates/editor/src/element.rs
  tooling/xtask/src/main.rs
Labels: cla-signed

#8747 Enable `clippy::option_as_ref_deref`
  crates/project/src/project.rs
  tooling/xtask/src/main.rs
Labels: cla-signed

#8748 Enable `clippy::search_is_some`
  crates/editor/src/editor.rs
  crates/feature_flags/src/feature_flags.rs
  crates/search/src/history.rs
  crates/sum_tree/src/tree_map.rs
  tooling/xtask/src/main.rs
Labels: cla-signed

#8750 Enable `clippy::redundant_locals`
  crates/editor/src/editor.rs
  crates/rpc/src/conn.rs
  crates/semantic_index/src/semantic_index.rs
  crates/terminal_view/src/terminal_element.rs
  crates/workspace/src/workspace.rs
  tooling/xtask/src/main.rs
Labels: cla-signed

#8751 Enable `clippy::option_map_unit_fn`
  crates/collab_ui/src/chat_panel.rs
  crates/copilot_ui/src/copilot_button.rs
  crates/editor/src/editor.rs
  crates/gpui/src/test.rs
  crates/semantic_index/src/semantic_index.rs
  crates/workspace/src/pane.rs
  crates/workspace/src/workspace.rs
  tooling/xtask/src/main.rs
Labels: cla-signed

#8752 Enable `clippy::unnecessary_operation`
  crates/collab/src/db/tests/contributor_tests.rs
  crates/collab/src/db/tests/db_tests.rs
  tooling/xtask/src/main.rs
Labels: cla-signed

#8753 Enable `clippy::explicit_auto_deref`
  crates/collab/src/db/queries/buffers.rs
  crates/collab/src/db/queries/channels.rs
  crates/collab/src/db/queries/contacts.rs
  crates/collab/src/db/queries/contributors.rs
  crates/collab/src/db/queries/messages.rs
  crates/collab/src/db/queries/projects.rs
  crates/collab/src/db/queries/rooms.rs
  crates/collab/src/db/queries/users.rs
  crates/collab/src/db/tests/buffer_tests.rs
  crates/collab/src/db/tests/channel_tests.rs
  crates/collab/src/db/tests/message_tests.rs
  crates/collab/src/rpc.rs
  crates/collab/src/tests/test_server.rs
  crates/editor/src/editor.rs
  crates/editor/src/editor_tests.rs
  crates/gpui/src/app/test_context.rs
  crates/multi_buffer/src/multi_buffer.rs
  crates/ui/src/components/stories/keybinding.rs
  crates/workspace/src/item.rs
  tooling/xtask/src/main.rs
Labels: cla-signed

#8754 Enable `clippy::extra_unused_lifetimes`
  crates/collab_ui/src/collab_panel.rs
  crates/gpui/src/app/test_context.rs
  crates/project_core/src/worktree.rs
  tooling/xtask/src/main.rs
Labels: cla-signed

#8755 Enable `clippy::nonminimal_bool`
  crates/collab_ui/src/collab_panel.rs
  crates/project/src/project.rs
  crates/terminal_view/src/terminal_view.rs
  crates/vim/src/object.rs
  crates/vim/src/visual.rs
  tooling/xtask/src/main.rs
Labels: cla-signed

#8756 Enable `clippy::unnecessary_unwrap`
  crates/ai/src/embedding.rs
  crates/ui/src/components/popover_menu.rs
  crates/ui/src/components/right_click_menu.rs
  tooling/xtask/src/main.rs
Labels: cla-signed

#8758 Enable `clippy::useless_format`
  crates/collab/src/api/events.rs
  crates/collab/src/db/tests.rs
  crates/collab/src/db/tests/contributor_tests.rs
  crates/collab/src/db/tests/db_tests.rs
  crates/collab/src/db/tests/feature_flag_tests.rs
  crates/collab_ui/src/channel_view.rs
  crates/collab_ui/src/chat_panel/message_editor.rs
  crates/collab_ui/src/collab_panel.rs
  crates/collab_ui/src/notification_panel.rs
  crates/editor/src/movement.rs
  crates/vim/src/test/neovim_connection.rs
  tooling/xtask/src/main.rs
Labels: cla-signed

#8759 Enable `clippy::needless_question_mark`
  crates/collab/src/api.rs
  crates/collab/src/db/queries/rooms.rs
  crates/collab/src/db/tests/channel_tests.rs
  crates/editor/src/items.rs
  crates/project/src/project.rs
  crates/project_panel/src/project_panel.rs
  crates/semantic_index/src/db.rs
  crates/workspace/src/persistence.rs
  crates/workspace/src/workspace.rs
  tooling/xtask/src/main.rs
Labels: cla-signed

#8760 Fix some comments
  crates/gpui/README.md
  crates/gpui/src/gpui.rs
  crates/language/src/buffer.rs
  crates/languages/src/python.rs
  docs/src/tasks.md
Labels: cla-signed

#8767 Enable `clippy::useless_conversion`
  crates/assistant/src/assistant_panel.rs
  crates/collab/src/api/ips_file.rs
  crates/collab/src/db/queries/rooms.rs
  crates/collab/src/rpc.rs
  crates/collab/src/tests/channel_tests.rs
  crates/collab/src/tests/editor_tests.rs
  crates/collab_ui/src/chat_panel/message_editor.rs
  crates/collab_ui/src/collab_panel.rs
  crates/copilot_ui/src/copilot_button.rs
  crates/diagnostics/src/diagnostics.rs
  crates/editor/src/display_map.rs
  crates/editor/src/element.rs
  crates/editor/src/rust_analyzer_ext.rs
  crates/editor/src/scroll/autoscroll.rs
  crates/extension/src/extension_lsp_adapter.rs
  crates/extensions_ui/src/extensions_ui.rs
  crates/gpui/src/app/test_context.rs
  crates/language/src/syntax_map.rs
  crates/markdown_preview/src/markdown_preview_view.rs
  crates/outline/src/outline.rs
  crates/recent_projects/src/recent_projects.rs
  crates/search/src/buffer_search.rs
  crates/search/src/project_search.rs
  crates/terminal/src/terminal.rs
  crates/vim/src/command.rs
  crates/workspace/src/dock.rs
  crates/workspace/src/pane.rs
  crates/workspace/src/workspace.rs
  crates/zed/src/main.rs
  tooling/xtask/src/main.rs
Labels: cla-signed

#8768 Enable `clippy::expect_fun_call`
  crates/collab/src/bin/seed.rs
  tooling/xtask/src/main.rs
Labels: cla-signed

#8769 Enable `clippy::bool_comparison`
  crates/terminal/src/terminal.rs
  tooling/xtask/src/main.rs
Labels: cla-signed

#8770 Enable `clippy::redundant_guards`
  crates/project/src/project.rs
  tooling/xtask/src/main.rs
Labels: cla-signed

#8771 Enable `clippy::vec_init_then_push`
  crates/collab/src/db/tests/buffer_tests.rs
  crates/workspace/src/workspace.rs
  tooling/xtask/src/main.rs
Labels: cla-signed

#8773 Enable `clippy::identity_op`
  crates/languages/src/ocaml.rs
  tooling/xtask/src/main.rs
Labels: cla-signed

#8775 Enable `clippy::needless_option_as_deref`
  crates/editor/src/display_map.rs
  tooling/xtask/src/main.rs
Labels: cla-signed

#8682 Accept partial copilot suggestions
  assets/keymaps/default-linux.json
  assets/keymaps/default-macos.json
  crates/editor/src/actions.rs
  crates/editor/src/editor.rs
  crates/editor/src/editor_tests.rs
  crates/editor/src/element.rs
Labels: cla-signed

#8776 Enable `clippy::explicit_counter_loop`
  crates/editor/src/editor.rs
  tooling/xtask/src/main.rs
Labels: cla-signed

#8777 Enable `clippy::needless_lifetimes`
  crates/channel/src/channel_store/channel_index.rs
  crates/collab/src/tests/test_server.rs
  crates/editor/src/display_map.rs
  crates/editor/src/display_map/inlay_map.rs
  crates/editor/src/editor.rs
  crates/editor/src/editor_tests.rs
  crates/editor/src/items.rs
  crates/git/src/diff.rs
  crates/language/src/buffer.rs
  crates/multi_buffer/src/multi_buffer.rs
  crates/project/src/project.rs
  crates/zed/src/zed.rs
  tooling/xtask/src/main.rs
Labels: cla-signed

#8778 Enable `clippy::default_constructed_unit_structs`
  crates/editor/src/editor_tests.rs
  tooling/xtask/src/main.rs
Labels: cla-signed

#8490 Windows gpui platform
  Cargo.lock
  crates/gpui/Cargo.toml
  crates/gpui/src/platform.rs
  crates/gpui/src/platform/windows.rs
  crates/gpui/src/platform/windows/dispatcher.rs
  crates/gpui/src/platform/windows/display.rs
  crates/gpui/src/platform/windows/platform.rs
  crates/gpui/src/platform/windows/text_system.rs
  crates/gpui/src/platform/windows/util.rs
  crates/gpui/src/platform/windows/window.rs
  crates/zed/build.rs
Labels: cla-signed

#8531 Replace todo calls with error values in linux/platform
  crates/gpui/src/platform/linux/platform.rs
Labels: cla-signed

#8780 Add libzstd to script/linux
  script/linux
Labels: cla-signed

#8632 linux: wayland: implement cursor style handling
  Cargo.lock
  crates/gpui/Cargo.toml
  crates/gpui/src/platform/linux/client.rs
  crates/gpui/src/platform/linux/platform.rs
  crates/gpui/src/platform/linux/wayland.rs
  crates/gpui/src/platform/linux/wayland/client.rs
  crates/gpui/src/platform/linux/wayland/cursor.rs
  crates/gpui/src/platform/linux/x11/client.rs
Labels: cla-signed

#8331 Implement `all_font_families` for the LinuxTextSystem
  crates/gpui/src/platform/linux/text_system.rs
Labels: cla-signed

#8785 windows: get pid with win32 api
  Cargo.lock
  crates/terminal/Cargo.toml
  crates/terminal/src/terminal.rs
Labels: cla-signed

#8786 Move windows up to workspace dependency
  Cargo.toml
  crates/gpui/Cargo.toml
  crates/terminal/Cargo.toml
Labels: cla-signed

#8789 Fix name of zstd package in Arch Linux repos
  script/linux
Labels: cla-signed

#8788 Add doas support in script/linux
  script/linux
  typos.toml
Labels: cla-signed

#8035 linux: add credentials impl via oo7
  Cargo.lock
  crates/gpui/Cargo.toml
  crates/gpui/src/platform/linux/platform.rs
Labels: cla-signed

#8806 Implement 'format without save'
  assets/keymaps/default-linux.json
  assets/keymaps/default-macos.json
  crates/diagnostics/src/diagnostics.rs
  crates/editor/src/editor_tests.rs
  crates/editor/src/items.rs
  crates/search/src/project_search.rs
  crates/workspace/src/item.rs
  crates/workspace/src/pane.rs
  crates/workspace/src/workspace.rs
  crates/zed/src/zed.rs
Labels: cla-signed

#8659 Add a fish-specific fix for #8633
  crates/project/src/project.rs
Labels: cla-signed

#8790 Docs: Made "Configuring Zed" a link
  docs/src/getting_started.md
Labels: cla-signed

#8798 Return "open in new window" as default in recent projects
  crates/recent_projects/src/recent_projects.rs
  crates/zed/src/app_menus.rs
Labels: cla-signed

#8824 linux/wayland: prevent possible panic
  crates/gpui/src/platform/linux/wayland/client.rs
Labels: cla-signed

#8826 Fix argument order when printing prettier debug info
  crates/prettier/src/prettier.rs
Labels: cla-signed

#8827 task: Spawn static tasks in separate shell
  crates/task/src/lib.rs
  crates/task/src/oneshot_source.rs
  crates/task/src/static_source.rs
  crates/terminal_view/src/terminal_panel.rs
Labels: cla-signed

#8820 clangd: download the correct binary on Linux
  crates/languages/src/c.rs
Labels: cla-signed

#8830 Enable `clippy::needless_update`
  crates/collab/src/db/queries/projects.rs
  crates/collab/src/rpc.rs
  crates/collab/src/tests/integration_tests.rs
  tooling/xtask/src/main.rs
Labels: cla-signed

#8832 Enable `clippy::iter_kv_map`
  crates/extension/src/extension_store.rs
  tooling/xtask/src/main.rs
Labels: cla-signed

#8822 linux: clipboard
  Cargo.lock
  crates/gpui/Cargo.toml
  crates/gpui/src/platform/linux/client.rs
  crates/gpui/src/platform/linux/platform.rs
  crates/gpui/src/platform/linux/wayland/client.rs
  crates/gpui/src/platform/linux/x11/client.rs
Labels: cla-signed

#8835 Assign OpenAI model based on Azure OpenAI deployment ID
  crates/assistant/src/assistant_settings.rs
Labels: cla-signed

#8836 Enable `clippy::derivable_impls`
  crates/ai/src/test.rs
  tooling/xtask/src/main.rs
Labels: cla-signed

#8834 linux: remove todo for credential implementation
  crates/gpui/src/platform/linux/platform.rs
Labels: cla-signed

#8837 Set working directory for `project` to project path
  crates/prettier/src/prettier.rs
Labels: cla-signed

#8839 Enable `clippy::iter_overeager_cloned`
  crates/language/src/syntax_map.rs
  tooling/xtask/src/main.rs
Labels: cla-signed

#8846 Optimize project panel subscriptions
  crates/project_panel/src/project_panel.rs
Labels: cla-signed

#8853 Add option to sign in to copilot from welcome screen
  Cargo.lock
  crates/copilot_ui/src/copilot_button.rs
  crates/copilot_ui/src/copilot_ui.rs
  crates/welcome/Cargo.toml
  crates/welcome/src/welcome.rs
Labels: cla-signed

#8849 Ensure followed cursors are always visible
  crates/editor/src/element.rs
Labels: cla-signed

#8675 task: Add task contexts
  Cargo.lock
  crates/extension/src/extension_store.rs
  crates/language/src/language.rs
  crates/language/src/language_registry.rs
  crates/languages/src/lib.rs
  crates/project/src/task_inventory.rs
  crates/task/Cargo.toml
  crates/task/src/lib.rs
  crates/task/src/oneshot_source.rs
  crates/task/src/static_source.rs
  crates/tasks_ui/Cargo.toml
  crates/tasks_ui/src/lib.rs
  crates/tasks_ui/src/modal.rs
Labels: cla-signed

#8863 Remove release channel from Zed URLs
  Cargo.lock
  crates/channel/src/channel_store.rs
  crates/client/src/client.rs
  crates/collab_ui/src/channel_view.rs
  crates/collab_ui/src/collab_panel.rs
  crates/collab_ui/src/collab_panel/channel_modal.rs
  crates/command_palette/Cargo.toml
  crates/command_palette/src/command_palette.rs
  crates/gpui/src/app.rs
  crates/gpui/src/platform.rs
  crates/gpui/src/platform/linux/platform.rs
  crates/gpui/src/platform/mac/platform.rs
  crates/gpui/src/platform/test/platform.rs
  crates/gpui/src/platform/windows/platform.rs
  crates/install_cli/src/install_cli.rs
  crates/release_channel/src/lib.rs
  crates/zed/Cargo.toml
  crates/zed/src/main.rs
  crates/zed/src/open_listener.rs
  crates/zed/src/zed.rs
  script/bundle
Labels: cla-signed

#8702 vim: Support keybinding `z.`
  assets/keymaps/vim.json
Labels: cla-signed

#7687 vim: Add support for `ap` and `ip` paragraph text objects
  assets/keymaps/vim.json
  crates/vim/src/normal/delete.rs
  crates/vim/src/object.rs
  crates/vim/src/visual.rs
  crates/vim/test_data/test_change_paragraph_object.json
  crates/vim/test_data/test_delete_paragraph_object.json
  crates/vim/test_data/test_paragraph_object_with_landing_positions_not_at_beginning_of_line.json
  crates/vim/test_data/test_visual_paragraph_object.json
Labels: cla-signed

#8475 macOS: Fix center window with fixed bounds size
  crates/gpui/examples/hello_world.rs
  crates/gpui/src/platform/mac/window.rs
Labels: cla-signed

#8627 hosted projects
  crates/call/src/room.rs
  crates/channel/src/channel.rs
  crates/channel/src/channel_store.rs
  crates/client/src/user.rs
  crates/collab/migrations.sqlite/20221109000000_test_schema.sql
  crates/collab/migrations/20240227215556_hosted_projects_in_projects.sql
  crates/collab/src/db.rs
  crates/collab/src/db/queries/hosted_projects.rs
  crates/collab/src/db/queries/projects.rs
  crates/collab/src/db/queries/rooms.rs
  crates/collab/src/db/tables/project.rs
  crates/collab/src/rpc.rs
  crates/collab/src/tests/following_tests.rs
  crates/collab/src/tests/integration_tests.rs
  crates/collab_ui/src/collab_panel.rs
  crates/collab_ui/src/notifications/incoming_call_notification.rs
  crates/collab_ui/src/notifications/project_shared_notification.rs
  crates/project/src/project.rs
  crates/rpc/proto/zed.proto
  crates/rpc/src/proto.rs
  crates/workspace/src/pane_group.rs
  crates/workspace/src/workspace.rs
Labels: cla-signed

#8870 Fix panic in enclosing bracket ranges
  crates/multi_buffer/src/multi_buffer.rs
Labels: cla-signed

#8876 Fix license generation and Closure LSP repo link
  docs/src/languages/clojure.md
  script/generate-licenses
  script/licenses/zed-licenses.toml
Labels: cla-signed

#8879 Improve VCS Menu header top margin.
  crates/vcs_menu/src/lib.rs
Labels: cla-signed

#8877 Fix all Picker Item cursor to use `Pointer`.
  crates/picker/src/picker.rs
  crates/recent_projects/src/recent_projects.rs
  crates/vcs_menu/src/lib.rs
Labels: cla-signed

#8880 Fix first/last item margin on scroll
  crates/command_palette/src/command_palette.rs
  crates/file_finder/src/file_finder.rs
  crates/gpui/src/elements/list.rs
  crates/gpui/src/elements/uniform_list.rs
Labels: cla-signed

#8873 Optimize rustybuzz and ttf-parser in Dev
  Cargo.toml
Labels: cla-signed

#8888 Use correct worktree when getting permalink to line
  crates/editor/src/editor.rs
  crates/project/src/project.rs
  crates/project_core/src/worktree.rs
Labels: cla-signed

#8890 Request more resources for collab pods on Kubernetes
  crates/collab/k8s/collab.template.yml
Labels: cla-signed

#8791 windows: mouse and keyboard
  Cargo.toml
  crates/gpui/src/platform/windows/platform.rs
  crates/gpui/src/platform/windows/util.rs
  crates/gpui/src/platform/windows/window.rs
Labels: cla-signed

#8811 Update blade to latest: work around Intel+NVidia driver bug
  Cargo.lock
  Cargo.toml
  crates/gpui/src/platform/blade/blade_renderer.rs
  crates/gpui/src/platform/linux/wayland/window.rs
  crates/gpui/src/platform/linux/x11/window.rs
  crates/gpui/src/platform/windows/window.rs
Labels: cla-signed

#8872 Add libxcb-devel build dep to void linux script
  script/linux
Labels: cla-signed

#8828 Windows: use folders under AppData
  crates/util/src/paths.rs
Labels: cla-signed

#8897 Enable tokio-console
  .cargo/config.toml
  Cargo.lock
  crates/collab/Cargo.toml
  crates/collab/k8s/collab.template.yml
  crates/collab/src/main.rs
Labels: cla-signed

#8899 Enable `clippy::cmp_owned`
  Cargo.toml
  crates/assistant/src/assistant_panel.rs
Labels: cla-signed

#8900 Fix project subscription order
  crates/project/src/project.rs
Labels: cla-signed

#8906 Enable `clippy::implied_bounds_in_impls`
  Cargo.toml
  crates/workspace/src/pane.rs
Labels: cla-signed

#8904 Always resolve code action if needed
  crates/lsp/src/lsp.rs
  crates/project/src/lsp_command.rs
  crates/project/src/project.rs
  crates/project/src/project_tests.rs
Labels: cla-signed, run-build-dmg

#8907 Fix tracing subscriber after introducing Tokio-console
  Cargo.lock
  crates/collab/Cargo.toml
  crates/collab/k8s/collab.template.yml
  crates/collab/src/api.rs
  crates/collab/src/api/events.rs
  crates/collab/src/api/extensions.rs
  crates/collab/src/lib.rs
  crates/collab/src/main.rs
  crates/collab/src/rpc.rs
  script/run-local-minio
Labels: cla-signed

#8908 Enable `clippy::unnecessary_to_owned`
  Cargo.toml
  crates/editor/src/editor.rs
Labels: cla-signed

#8909 Log the time incoming RPC messages were queued
  crates/collab/src/rpc.rs
  crates/rpc/src/macros.rs
  crates/rpc/src/peer.rs
  crates/rpc/src/proto.rs
Labels: cla-signed

#8926 0-downtime collab deploys?
  crates/collab/k8s/collab.template.yml
  crates/collab/src/rpc.rs
Labels: cla-signed

#8925 Modify the link to the latest
  docs/src/languages/vue.md
Labels: cla-signed

#8939 Give a name to load balancers and increase node count for production
  .github/workflows/deploy_collab.yml
  crates/collab/k8s/collab.template.yml
  crates/collab/k8s/postgrest.template.yml
Labels: cla-signed

#8918 Throttle the sending of UpdateFollowers messages
  Cargo.lock
  crates/collab/src/tests/following_tests.rs
  crates/gpui/src/test.rs
  crates/picker/Cargo.toml
  crates/picker/src/picker.rs
  crates/workspace/src/item.rs
  crates/workspace/src/workspace.rs
Labels: cla-signed

#8943 Update `Project search` to `Project Search`.
  crates/search/src/project_search.rs
Labels: cla-signed

#8922 Remove workspace border, avoid the main window having double borders
  crates/workspace/src/workspace.rs
Labels: cla-signed

#8951 Update App Menus to add `...` for some modal action menu, and group menu items by type.
  crates/collab_ui/src/collab_titlebar_item.rs
  crates/zed/src/app_menus.rs
Labels: cla-signed

#8912 Enable `clippy::cast_abs_to_unsigned`
  Cargo.toml
  crates/terminal/src/mappings/mouse.rs
Labels: cla-signed

#8955 Remove console-subscriber
  Cargo.lock
  crates/collab/Cargo.toml
  crates/collab/k8s/collab.template.yml
  crates/collab/src/main.rs
Labels: cla-signed

#8957 Install perf tools in production containers
  Dockerfile
Labels: cla-signed

#8584 Improve bindings to better match VS-Code
  assets/keymaps/default-macos.json
  assets/keymaps/jetbrains.json
  crates/editor/src/actions.rs
  crates/editor/src/editor.rs
  crates/editor/src/editor_tests.rs
  crates/zed/src/app_menus.rs
Labels: cla-signed

#8924 prevent empty cwd in terminal view
  crates/terminal_view/src/terminal_view.rs
Labels: cla-signed

#8935 Update `mio`
  Cargo.lock
Labels: windows, cla-signed

#8936 Set the default DPI awareness for Zed
  crates/zed/build.rs
  crates/zed/resources/windows/manifest.xml
Labels: windows, cla-signed

#8921 windows: more frequent frame requests
  Cargo.toml
  crates/gpui/src/platform/windows/platform.rs
  crates/gpui/src/platform/windows/window.rs
Labels: windows, cla-signed

#8963 Emit the WorktreeUpdatedEntries event for all projects, not just local
  crates/project/src/project.rs
Labels: cla-signed
