Repository zed-industries/zed, pull requests merged in 2025-09, with the labels that each got.

#37278 docs: Improve Bedrock suggested IAM policy
  docs/src/ai/llm-providers.md
Labels: docs, cla-signed

#37244 Improve system window tabs visibility
  crates/gpui/src/platform.rs
  crates/gpui/src/platform/mac/window.rs
  crates/gpui/src/window.rs
  crates/title_bar/src/system_window_tabs.rs
  crates/zed/src/main.rs
Labels: cla-signed

#37175 gpui: Do not render ligatures between different styled text runs
  crates/gpui/src/platform/mac/text_system.rs
  crates/gpui/src/text_system.rs
  crates/gpui/src/text_system/line_layout.rs
Labels: cla-signed

#36987 editor: Add an option to disable rounded corners for text selection
  assets/settings/default.json
  crates/editor/src/editor_settings.rs
  crates/editor/src/element.rs
  crates/terminal_view/src/terminal_element.rs
  docs/src/configuring-zed.md
Labels: cla-signed

#33905 deepseek: Fix API URL
  assets/settings/default.json
  crates/deepseek/src/deepseek.rs
Labels: ai, cla-signed

#37314 windows: Don’t skip the typo check for the windows folder
  crates/gpui/src/platform/windows/directx_renderer.rs
  crates/gpui/src/platform/windows/events.rs
  crates/gpui/src/platform/windows/vsync.rs
  typos.toml
Labels: cla-signed

#37167 Implement perceptual gamma / contrast correction
  Cargo.toml
  crates/gpui/src/platform/windows/alpha_correction.hlsl
  crates/gpui/src/platform/windows/color_text_raster.hlsl
  crates/gpui/src/platform/windows/direct_write.rs
  crates/gpui/src/platform/windows/directx_renderer.rs
  crates/gpui/src/platform/windows/platform.rs
  crates/gpui/src/platform/windows/shaders.hlsl
Labels: cla-signed

#37129 ACP Terminal support
  Cargo.lock
  Cargo.toml
  crates/acp_thread/Cargo.toml
  crates/acp_thread/src/acp_thread.rs
  crates/acp_thread/src/terminal.rs
  crates/agent2/Cargo.toml
  crates/agent2/src/agent.rs
  crates/agent2/src/thread.rs
  crates/agent2/src/tools/terminal_tool.rs
  crates/agent_servers/src/acp.rs
  crates/agent_ui/src/acp/entry_view_state.rs
  crates/agent_ui/src/acp/thread_view.rs
Labels: cla-signed

#37328 gpui: Fix typo in Windows alpha correction shader
  crates/gpui/src/platform/windows/alpha_correction.hlsl
Labels: cla-signed

#37331 settings_ui: Add dynamic settings UI item
  crates/settings/src/settings_ui.rs
  crates/settings_ui/src/settings_ui.rs
  crates/settings_ui_macros/src/settings_ui_macros.rs
Labels: cla-signed

#37337 settings_ui: Move settings UI trait to file content
  crates/agent_settings/src/agent_settings.rs
  crates/audio/src/audio_settings.rs
  crates/auto_update/src/auto_update.rs
  crates/call/src/call_settings.rs
  crates/client/src/client.rs
  crates/collab_ui/src/panel_settings.rs
  crates/dap/src/debugger_settings.rs
  crates/editor/src/editor_settings.rs
  crates/file_finder/src/file_finder_settings.rs
  crates/git_ui/src/git_panel_settings.rs
  crates/go_to_line/src/cursor_position.rs
  crates/language/src/language_settings.rs
  crates/language_models/src/settings.rs
  crates/onboarding/src/base_keymap_picker.rs
  crates/onboarding/src/basics_page.rs
  crates/outline_panel/src/outline_panel_settings.rs
  crates/project_panel/src/project_panel_settings.rs
  crates/recent_projects/src/remote_connections.rs
  crates/repl/src/jupyter_settings.rs
  crates/settings/src/base_keymap_setting.rs
  crates/settings/src/settings_store.rs
  crates/settings/src/settings_ui.rs
  crates/settings_ui_macros/src/settings_ui_macros.rs
  crates/terminal/src/terminal_settings.rs
  crates/theme/src/settings.rs
  crates/title_bar/src/title_bar_settings.rs
  crates/vim/src/vim.rs
  crates/workspace/src/item.rs
  crates/workspace/src/workspace_settings.rs
  crates/worktree/src/worktree_settings.rs
Labels: cla-signed

#37330 settings_ui: Get editor settings working
  assets/settings/default.json
  crates/editor/src/editor_settings.rs
  crates/language/src/buffer.rs
  crates/project/src/project_settings.rs
  crates/settings/src/settings.rs
  crates/settings/src/settings_store.rs
  crates/settings/src/settings_ui_core.rs
  crates/settings_ui/src/settings_ui.rs
  crates/settings_ui_macros/src/settings_ui_macros.rs
Labels: cla-signed

#37342 settings_ui: Improve case handling
  Cargo.lock
  crates/settings/src/settings_ui_core.rs
  crates/settings_ui/src/settings_ui.rs
  crates/settings_ui_macros/Cargo.toml
  crates/settings_ui_macros/src/settings_ui_macros.rs
Labels: cla-signed

#37361 project: Temporarily disable terminal activation scripts on windows
  crates/project/src/terminals.rs
  crates/terminal/src/terminal.rs
Labels: cla-signed

#37370 Use premultiplied alpha for emoji rendering
  crates/gpui/src/platform/windows/color_text_raster.hlsl
  crates/gpui/src/platform/windows/direct_write.rs
Labels: cla-signed

#37356 Remove extra brace in rules template
  assets/prompts/assistant_system_prompt.hbs
Labels: ai, cla-signed

#37360 Add the Glossary from the channel into Zed
  CONTRIBUTING.md
  docs/src/development/glossary.md
Labels: cla-signed

#37382 Revert "gpui: Do not render ligatures between different styled text runs (#37175)
  crates/gpui/src/platform/mac/text_system.rs
  crates/gpui/src/text_system.rs
  crates/gpui/src/text_system/line_layout.rs
Labels: cla-signed

#37375 inline assistant: Adjust completion menu item font size
  crates/agent_ui/src/inline_prompt_editor.rs
Labels: cla-signed

#37329 zeta: Small refactoring in license detection check - rfind instead of iterated ends_with
  crates/zeta/src/license_detection.rs
Labels: cla-signed

#34921 language_models: Make `JsonSchemaSubset` the default `tool_input_format` for the OpenAI-compatible provider
  crates/language_models/src/provider/open_ai_compatible.rs
Labels: ai, cla-signed

#37377 Disable external agents over collab
  Cargo.toml
  crates/agent_ui/src/acp/thread_view.rs
  crates/agent_ui/src/agent_panel.rs
Labels: cla-signed

#37393 Nice errors for unsupported ACP slash commands
  crates/agent_ui/src/acp/entry_view_state.rs
  crates/agent_ui/src/acp/message_editor.rs
  crates/agent_ui/src/acp/thread_view.rs
Labels: cla-signed

#37390 acp: Enable claude code feature flag for everyone
  crates/feature_flags/src/feature_flags.rs
Labels: cla-signed

#37400 editor: Do not show edit prediction during in-progress IME composition
  crates/editor/src/editor.rs
Labels: cla-signed

#37403 agent2: Only setup real client for real models
  crates/agent2/src/tests/mod.rs
Labels: cla-signed

#37386 vim: Fix change surround with any brackets text object
  crates/vim/src/object.rs
  crates/vim/src/surrounds.rs
Labels: cla-signed

#37401 gpui: Remove `http_client` feature
  Cargo.toml
  crates/gpui/Cargo.toml
Labels: cla-signed

#37404 Add option for code context menu items to have dynamic width
  crates/agent_ui/src/acp/completion_provider.rs
  crates/agent_ui/src/context_picker/completion_provider.rs
  crates/agent_ui/src/slash_command.rs
  crates/collab_ui/src/chat_panel/message_editor.rs
  crates/debugger_ui/src/session/running/console.rs
  crates/editor/src/code_context_menus.rs
  crates/editor/src/editor.rs
  crates/inspector_ui/src/div_inspector.rs
  crates/keymap_editor/src/keymap_editor.rs
  crates/project/src/lsp_store.rs
  crates/project/src/project.rs
Labels: cla-signed

#34554 language_models: Fix tool_choice null issue for other providers
  crates/lmstudio/src/lmstudio.rs
  crates/mistral/src/mistral.rs
  crates/open_ai/src/open_ai.rs
Labels: ai, cla-signed

#37221 language_models: Prevent sending the tools object to unsupported models for Ollama
  crates/language_models/src/provider/ollama.rs
Labels: ai, cla-signed

#37402 acp: Disable external agents over SSH
  Cargo.toml
  crates/agent_ui/src/acp/thread_view.rs
  crates/agent_ui/src/agent_panel.rs
  crates/git_ui/src/branch_picker.rs
  crates/vim/src/visual.rs
Labels: cla-signed

#36797 tailwind: Add `HTML+ERB` to the list of supported languages
  crates/languages/src/lib.rs
  crates/languages/src/tailwind.rs
Labels: cla-signed

#33348 Add configurable timeout for context server tool calls
  crates/agent2/src/tests/mod.rs
  crates/context_server/src/client.rs
  crates/context_server/src/context_server.rs
  crates/project/src/context_server_store.rs
  crates/project/src/context_server_store/extension.rs
  crates/project/src/project_settings.rs
Labels: ai, cla-signed

#36694 ci: Remove Windows crash analysis CI scripts
  .github/actions/run_tests_windows/action.yml
Labels: cla-signed

#37383 Handle model refusal in ACP threads
  crates/acp_thread/src/acp_thread.rs
  crates/agent_ui/src/acp/model_selector_popover.rs
  crates/agent_ui/src/acp/thread_view.rs
  crates/agent_ui/src/active_thread.rs
  crates/agent_ui/src/agent_diff.rs
  crates/agent_ui/src/agent_panel.rs
Labels: cla-signed

#37408 agent: Fix cut off slash command descriptions
  crates/agent_ui/src/acp/completion_provider.rs
Labels: cla-signed

#37407 ci: Skip Nix for commits on release branches and tags
  .github/workflows/ci.yml
Labels: cla-signed

#37410 reqwest_client: Remove example
  Cargo.lock
  crates/reqwest_client/Cargo.toml
  crates/reqwest_client/examples/client.rs
Labels: cla-signed

#37415 Bump Zed to v0.204
  Cargo.lock
  crates/zed/Cargo.toml
Labels: cla-signed

#37422 Remove wsl command line args on non-windows platforms
  crates/cli/src/main.rs
  crates/zed/src/main.rs
Labels: cla-signed

#37426 Allow wrapping markdown text into `*` by selecting text and writing the `*`
  crates/languages/src/markdown/config.toml
Labels: cla-signed

#37412 acp: Fix handling of single-file worktrees
  crates/agent_ui/src/acp/thread_view.rs
Labels: cla-signed

#37439 rust: Improve highlighting in derive macros
  crates/languages/src/rust/highlights.scm
Labels: cla-signed

#37440 Fix font rendering at very large scales
  crates/gpui/src/platform/windows/direct_write.rs
Labels: cla-signed

#35083 gpui: Fix overflow_hidden to support clip with border radius
  crates/editor/src/element.rs
  crates/gpui/examples/content_mask.rs
  crates/gpui/src/elements/list.rs
  crates/gpui/src/elements/uniform_list.rs
  crates/gpui/src/platform/blade/shaders.wgsl
  crates/gpui/src/platform/mac/shaders.metal
  crates/gpui/src/platform/windows/shaders.hlsl
  crates/gpui/src/style.rs
  crates/gpui/src/window.rs
  crates/terminal_view/src/terminal_element.rs
  crates/ui/src/components/scrollbar.rs
Labels: cla-signed

#37454 languages: Fix python tasks failing when binary contains whitespaces
  crates/languages/src/python.rs
  crates/project/src/debugger/locators/python.rs
Labels: cla-signed

#37366 editor: Make blame and inline blame work for multibuffers
  crates/collab/src/tests/editor_tests.rs
  crates/editor/src/editor.rs
  crates/editor/src/editor_tests.rs
  crates/editor/src/element.rs
  crates/editor/src/git/blame.rs
  crates/multi_buffer/src/multi_buffer.rs
  crates/outline_panel/src/outline_panel.rs
  crates/project/src/lsp_store.rs
  crates/search/src/project_search.rs
  crates/sum_tree/src/tree_map.rs
Labels: cla-signed

#37352 Make word deletions less greedy
  assets/keymaps/default-linux.json
  assets/keymaps/default-macos.json
  assets/keymaps/default-windows.json
  assets/keymaps/linux/emacs.json
  assets/keymaps/linux/sublime_text.json
  assets/keymaps/macos/emacs.json
  assets/keymaps/macos/sublime_text.json
  assets/keymaps/macos/textmate.json
  assets/keymaps/vim.json
  crates/editor/src/actions.rs
  crates/editor/src/editor.rs
  crates/editor/src/editor_tests.rs
  crates/editor/src/movement.rs
  crates/language/src/language.rs
Labels: cla-signed

#37471 editor: Do not correct text contrast on non-opaque editor
  crates/editor/src/element.rs
  crates/gpui/src/color.rs
Labels: cla-signed

#37480 Revert "gpui: Fix overflow_hidden to support clip with border radius"
  crates/editor/src/element.rs
  crates/gpui/examples/content_mask.rs
  crates/gpui/src/elements/list.rs
  crates/gpui/src/elements/uniform_list.rs
  crates/gpui/src/platform/blade/shaders.wgsl
  crates/gpui/src/platform/mac/shaders.metal
  crates/gpui/src/platform/windows/shaders.hlsl
  crates/gpui/src/style.rs
  crates/gpui/src/window.rs
  crates/terminal_view/src/terminal_element.rs
  crates/ui/src/components/scrollbar.rs
Labels: cla-signed

#37497 docs: Fix typo in the `CLAUDE.md` section
  docs/src/ai/external-agents.md
Labels: cla-signed

#37492 Centralize `ZED_STATELESS`
  Cargo.lock
  Cargo.toml
  crates/agent/Cargo.toml
  crates/agent/src/thread_store.rs
  crates/agent2/Cargo.toml
  crates/agent2/src/db.rs
  crates/assistant_context/Cargo.toml
  crates/assistant_context/src/context_store.rs
  crates/db/Cargo.toml
  crates/db/src/db.rs
  crates/zed/Cargo.toml
  crates/zed/src/main.rs
  crates/zed_env_vars/Cargo.toml
  crates/zed_env_vars/LICENSE-GPL
  crates/zed_env_vars/src/zed_env_vars.rs
  script/new-crate
Labels: cla-signed

#37500 Update external agents installation docs
  docs/src/ai/external-agents.md
Labels: cla-signed

#37502 onboarding: Add telemetry to Basics page
  crates/onboarding/src/basics_page.rs
  crates/onboarding/src/onboarding.rs
  crates/sum_tree/src/tree_map.rs
Labels: cla-signed

#37504 onboarding: Improve performance of AI upsell card
  crates/ai_onboarding/src/ai_upsell_card.rs
Labels: cla-signed

#37517 docs: Update OpenAI-compatible provider config format
  docs/src/ai/llm-providers.md
Labels: cla-signed

#37397 agent2: Use inline enums in `now` and `edit_file` tools JSON schema
  crates/agent2/src/tools/edit_file_tool.rs
  crates/agent2/src/tools/now_tool.rs
Labels: ai, cla-signed

#37445 windows: Keep just one copy of GPU instance
  crates/gpui/src/platform/windows.rs
  crates/gpui/src/platform/windows/direct_write.rs
  crates/gpui/src/platform/windows/directx_devices.rs
  crates/gpui/src/platform/windows/directx_renderer.rs
  crates/gpui/src/platform/windows/events.rs
  crates/gpui/src/platform/windows/platform.rs
  crates/gpui/src/platform/windows/window.rs
Labels: cla-signed

#37541 onboarding: Fix typos in comments
  crates/onboarding/src/basics_page.rs
Labels: cla-signed

#37546 diagnostics: Fix diagnostics pane clearing up too eagerly on typing
  crates/diagnostics/src/diagnostics.rs
  crates/diagnostics/src/items.rs
Labels: cla-signed

#37516 Fix Wayland crash on AMD GPUs by updating Blade
  Cargo.lock
  Cargo.toml
  crates/gpui/src/platform/blade/blade_renderer.rs
Labels: cla-signed

#37554 Use full SHA for `blade` dependency
  Cargo.lock
  Cargo.toml
Labels: cla-signed

#37555 debugger: Fix stack frame filter crash
  crates/debugger_ui/src/session/running/stack_frame_list.rs
  crates/debugger_ui/src/tests/stack_frame_list.rs
Labels: cla-signed

#37559 acp: Keep diff editors in sync with `AgentFontSize` global
  crates/agent_ui/src/acp/entry_view_state.rs
  crates/agent_ui/src/acp/thread_view.rs
  crates/theme/src/settings.rs
Labels: cla-signed

#37560 Make remote projects to sync in local user settings
  crates/project/src/project.rs
  crates/project/src/project_settings.rs
  crates/proto/proto/worktree.proto
  crates/proto/proto/zed.proto
  crates/proto/src/proto.rs
  crates/remote_server/src/remote_editing_tests.rs
  crates/remote_server/src/unix.rs
  crates/settings/src/settings_store.rs
Labels: cla-signed

#37564 Make fallback open picker more intuitive
  crates/file_finder/src/open_path_prompt.rs
  crates/file_finder/src/open_path_prompt_tests.rs
Labels: cla-signed

#37567 snippets: Bump to v0.0.6
  Cargo.lock
  extensions/snippets/Cargo.toml
  extensions/snippets/extension.toml
Labels: cla-signed

#37573 docs: Claude Authentication
  docs/src/ai/agent-panel.md
  docs/src/ai/external-agents.md
Labels: docs, cla-signed

#37581 settings ui: Improve setting proc macro and add scroll to UI
  crates/editor/src/editor_settings.rs
  crates/language/src/language_settings.rs
  crates/settings/src/settings_ui_core.rs
  crates/settings_ui/src/settings_ui.rs
  crates/settings_ui_macros/src/settings_ui_macros.rs
Labels: cla-signed

#37600 linux: Fix IME positioning on scaled display on Wayland
  crates/gpui/src/platform.rs
  crates/gpui/src/platform/linux/wayland/client.rs
  crates/gpui/src/platform/linux/wayland/window.rs
  crates/gpui/src/platform/linux/x11/client.rs
  crates/gpui/src/platform/linux/x11/window.rs
  crates/gpui/src/platform/mac/window.rs
  crates/gpui/src/platform/test/window.rs
  crates/gpui/src/platform/windows/window.rs
  crates/gpui/src/window.rs
Labels: cla-signed

#37588 Fix logic for default values for task variables
  crates/task/src/task_template.rs
Labels: cla-signed

#37636 linux: Restore ctrl-escape to keymap
  assets/keymaps/default-linux.json
Labels: cla-signed

#37650 windows: Make sure `zed.sh` using the correct line ending
  .gitattributes
Labels: cla-signed

#35392 Add line ending selector
  Cargo.lock
  Cargo.toml
  crates/language/src/buffer.rs
  crates/language/src/buffer_tests.rs
  crates/language/src/proto.rs
  crates/line_ending_selector/Cargo.toml
  crates/line_ending_selector/LICENSE-GPL
  crates/line_ending_selector/src/line_ending_selector.rs
  crates/proto/proto/buffer.proto
  crates/zed/Cargo.toml
  crates/zed/src/main.rs
  crates/zed/src/zed.rs
Labels: cla-signed

#37646 editor: Fix text manipulation on line mode selections
  crates/editor/src/editor.rs
  crates/editor/src/editor_tests.rs
Labels: cla-signed

#37657 Show actual error in InvalidBufferView
  crates/workspace/src/invalid_buffer_view.rs
Labels: cla-signed

#37661 Restore notification panel settings
  crates/collab_ui/src/panel_settings.rs
Labels: cla-signed

#37663 editor: Fix fold placeholder hover width smaller than marker
  crates/editor/src/editor.rs
Labels: cla-signed

#37608 Fix attach modal showing local processes in SSH sessions
  crates/debugger_ui/src/attach_modal.rs
  crates/debugger_ui/src/new_process_modal.rs
  crates/proto/proto/debugger.proto
  crates/proto/proto/zed.proto
  crates/proto/src/proto.rs
  crates/remote_server/src/headless_project.rs
Labels: cla-signed

#37671 Update Link
  docs/src/configuring-languages.md
Labels: cla-signed

#37036 debugger: Fix allow showing more than 1 compact session item
  crates/debugger_ui/src/dropdown_menus.rs
Labels: cla-signed

#37009 toolchains: Allow users to provide custom paths to toolchains
  Cargo.lock
  assets/keymaps/default-linux.json
  assets/keymaps/default-macos.json
  crates/file_finder/src/open_path_prompt.rs
  crates/language/src/language.rs
  crates/language/src/toolchain.rs
  crates/languages/src/lib.rs
  crates/languages/src/python.rs
  crates/project/src/lsp_store.rs
  crates/project/src/project.rs
  crates/project/src/project_tests.rs
  crates/project/src/toolchain_store.rs
  crates/proto/proto/toolchain.proto
  crates/proto/proto/zed.proto
  crates/proto/src/proto.rs
  crates/repl/src/kernels/mod.rs
  crates/toolchain_selector/Cargo.toml
  crates/toolchain_selector/src/active_toolchain.rs
  crates/toolchain_selector/src/toolchain_selector.rs
  crates/workspace/src/persistence.rs
  crates/workspace/src/persistence/model.rs
  crates/workspace/src/workspace.rs
Labels: cla-signed

#37673 Highlight labels in Go
  crates/languages/src/go/highlights.scm
Labels: cla-signed

#37572 Disable foreign keys in sqlite when running migrations
  Cargo.lock
  crates/sqlez/Cargo.toml
  crates/sqlez/src/migrations.rs
  crates/sqlez/src/thread_safe_connection.rs
  crates/workspace/src/persistence.rs
Labels: cla-signed

#37659 Optimize Chunks::seek when offset is in current chunk
  crates/rope/src/rope.rs
Labels: cla-signed

#37626 language_models: Skip empty delta text content in OpenAI and OpenAI compatible provider
  crates/language_models/src/provider/open_ai.rs
Labels: ai, cla-signed

#37534 language_models: Use `/models/user` for fetching OpenRouter models
  crates/language_models/src/provider/open_router.rs
  crates/open_router/src/open_router.rs
Labels: ai, cla-signed

#37682 Fixed LSP binary info not being shown in full
  crates/language_tools/src/lsp_log_view.rs
  crates/project/src/lsp_store/log_store.rs
Labels: cla-signed

#37697 Tweak word completions more
  crates/agent_ui/src/message_editor.rs
  crates/editor/src/code_context_menus.rs
  crates/editor/src/editor.rs
  crates/editor/src/editor_tests.rs
Labels: cla-signed

#37701 linux: Fix IME preedit text not showing in Terminal on Wayland
  crates/terminal_view/src/terminal_element.rs
  crates/terminal_view/src/terminal_view.rs
Labels: cla-signed

#37722 windows: Remove some unused keys from the keymap
  assets/keymaps/default-windows.json
Labels: cla-signed

#37086 editor: Fix inconsistent search behavior for untitled/temporary tabs
  crates/editor/src/items.rs
Labels: cla-signed

#34750 ollama: Properly format tool calls fed back to the model
  crates/language_models/src/provider/ollama.rs
  crates/ollama/src/ollama.rs
Labels: ai, cla-signed

#35403 agent_ui: Fix `context_server` duplication when name is updated
  crates/agent_ui/src/agent_configuration/configure_context_server_modal.rs
Labels: ai, cla-signed

#37569 agent_ui: Clear model selector query on dismiss
  crates/agent_ui/src/acp/model_selector.rs
Labels: ai, cla-signed

#37740 docs: Fix typos in language configurations
  docs/src/languages/c.md
  docs/src/languages/cpp.md
  docs/src/languages/rust.md
Labels: cla-signed

#37264 markdown: Add support for inline HTML `img` tags inside text
  crates/markdown_preview/src/markdown_elements.rs
  crates/markdown_preview/src/markdown_parser.rs
  crates/markdown_preview/src/markdown_renderer.rs
Labels: cla-signed

#37716 tests: Fix doctests in crates/component
  Cargo.lock
  crates/component/Cargo.toml
  crates/component/src/component.rs
Labels: cla-signed

#37674 Highlight shorthand fields in Rust
  crates/languages/src/rust/highlights.scm
Labels: cla-signed

#37769 cargo: Remove unused -fuse-ld=lld flag from Win config
  .cargo/config.toml
Labels: cla-signed

#35750 markdown_preview: Fix trimming of leading whitespace in Markdown lists
  crates/markdown_preview/src/markdown_renderer.rs
Labels: cla-signed

#37780 Remove unused `semantic_index` crate
  Cargo.lock
  Cargo.toml
  crates/semantic_index/Cargo.toml
  crates/semantic_index/LICENSE-GPL
  crates/semantic_index/examples/index.rs
  crates/semantic_index/fixture/main.rs
  crates/semantic_index/fixture/needle.md
  crates/semantic_index/src/chunking.rs
  crates/semantic_index/src/embedding.rs
  crates/semantic_index/src/embedding/lmstudio.rs
  crates/semantic_index/src/embedding/ollama.rs
  crates/semantic_index/src/embedding/open_ai.rs
  crates/semantic_index/src/embedding_index.rs
  crates/semantic_index/src/indexing.rs
  crates/semantic_index/src/project_index.rs
  crates/semantic_index/src/project_index_debug_view.rs
  crates/semantic_index/src/semantic_index.rs
  crates/semantic_index/src/summary_backlog.rs
  crates/semantic_index/src/summary_index.rs
  crates/semantic_index/src/worktree_index.rs
Labels: cla-signed

#37707 macos: Fix menu bar flickering
  crates/zed/src/zed.rs
Labels: cla-signed

#34060 helix: Add match operator
  assets/keymaps/vim.json
  crates/editor/src/movement.rs
  crates/vim/src/helix.rs
  crates/vim/src/helix/boundary.rs
  crates/vim/src/helix/object.rs
  crates/vim/src/helix/select.rs
  crates/vim/src/normal.rs
  crates/vim/src/object.rs
  crates/vim/src/state.rs
  crates/vim/src/vim.rs
  crates/zed/src/zed.rs
  docs/src/helix.md
Labels: cla-signed

#37639 agent: Make read_file and edit_file tool call titles more specific
  crates/agent2/src/tests/test_tools.rs
  crates/agent2/src/thread.rs
  crates/agent2/src/tools/context_server_registry.rs
  crates/agent2/src/tools/copy_path_tool.rs
  crates/agent2/src/tools/create_directory_tool.rs
  crates/agent2/src/tools/delete_path_tool.rs
  crates/agent2/src/tools/diagnostics_tool.rs
  crates/agent2/src/tools/edit_file_tool.rs
  crates/agent2/src/tools/fetch_tool.rs
  crates/agent2/src/tools/find_path_tool.rs
  crates/agent2/src/tools/grep_tool.rs
  crates/agent2/src/tools/list_directory_tool.rs
  crates/agent2/src/tools/move_path_tool.rs
  crates/agent2/src/tools/now_tool.rs
  crates/agent2/src/tools/open_tool.rs
  crates/agent2/src/tools/read_file_tool.rs
  crates/agent2/src/tools/terminal_tool.rs
  crates/agent2/src/tools/thinking_tool.rs
  crates/agent2/src/tools/web_search_tool.rs
  crates/agent_ui/src/acp/thread_view.rs
  crates/markdown/src/markdown.rs
  crates/project/src/project.rs
Labels: cla-signed

#37801 Only reject agent actions, don't restore checkpoint on revert
  crates/acp_thread/src/acp_thread.rs
  crates/agent_ui/src/acp/thread_view.rs
Labels: cla-signed

#37789 Remove Chat
  Cargo.lock
  assets/settings/default.json
  crates/auto_update_ui/src/auto_update_ui.rs
  crates/channel/Cargo.toml
  crates/channel/src/channel.rs
  crates/channel/src/channel_chat.rs
  crates/channel/src/channel_store.rs
  crates/channel/src/channel_store_tests.rs
  crates/collab/src/db.rs
  crates/collab/src/db/queries.rs
  crates/collab/src/db/queries/channels.rs
  crates/collab/src/db/queries/messages.rs
  crates/collab/src/db/queries/rooms.rs
  crates/collab/src/db/tests.rs
  crates/collab/src/db/tests/channel_tests.rs
  crates/collab/src/db/tests/message_tests.rs
  crates/collab/src/rpc.rs
  crates/collab/src/tests.rs
  crates/collab/src/tests/channel_message_tests.rs
  crates/collab_ui/Cargo.toml
  crates/collab_ui/src/chat_panel.rs
  crates/collab_ui/src/chat_panel/message_editor.rs
  crates/collab_ui/src/collab_panel.rs
  crates/collab_ui/src/collab_ui.rs
  crates/collab_ui/src/notification_panel.rs
  crates/collab_ui/src/panel_settings.rs
  crates/notifications/Cargo.toml
  crates/notifications/src/notification_store.rs
  crates/proto/proto/channel.proto
  crates/rpc/src/notification.rs
  crates/vim/src/command.rs
  crates/zed/src/zed.rs
  docs/src/configuring-zed.md
  docs/src/visual-customization.md
Labels: cla-signed

#37822 docs: Fix casing on mentions to some brand names
  docs/src/configuring-zed.md
  docs/src/development/debuggers.md
  docs/src/extensions/languages.md
  docs/src/globs.md
  docs/src/languages/deno.md
  docs/src/languages/gdscript.md
  docs/src/languages/java.md
  docs/src/languages/lua.md
  docs/src/languages/yarn.md
  docs/src/repl.md
  docs/src/snippets.md
Labels: cla-signed

#37825 Fix hot reload of builtin TreeSitter queries on Linux
  crates/zed/src/main.rs
Labels: cla-signed

#37833 editor: Remove unnecessary clone
  crates/editor/src/element.rs
Labels: cla-signed

#37684 terminal: Sanitize trailing periods in URL detection
  crates/terminal/src/terminal_hyperlinks.rs
Labels: cla-signed

#37852 cloud_llm_client: Add another `Plan` variant
  crates/agent_ui/src/acp/thread_view.rs
  crates/agent_ui/src/agent_configuration.rs
  crates/agent_ui/src/agent_panel.rs
  crates/agent_ui/src/ui/end_trial_upsell.rs
  crates/agent_ui/src/ui/preview/usage_callouts.rs
  crates/ai_onboarding/src/ai_onboarding.rs
  crates/ai_onboarding/src/ai_upsell_card.rs
  crates/cloud_llm_client/src/cloud_llm_client.rs
  crates/language_model/src/model/cloud_model.rs
  crates/title_bar/src/title_bar.rs
Labels: cla-signed

#37860 Fix git staging in a subfolder
  crates/worktree/src/worktree.rs
Labels: cla-signed

#37857 Allow unauthenticated commit models to show
  crates/git_ui/src/git_panel.rs
Labels: cla-signed

#37865 python: Add import paths to Pyright/BasedPyright completion items
  crates/languages/src/python.rs
Labels: cla-signed

#36713 Allow user-defined worktree names in title bar and platform windows
  assets/settings/default.json
  crates/title_bar/src/title_bar.rs
  crates/workspace/src/workspace.rs
  crates/worktree/src/worktree_settings.rs
Labels: cla-signed

#37849 Make it possible to support GPUI in the scheduler crate
  Cargo.lock
  Cargo.toml
  crates/scheduler/Cargo.toml
  crates/scheduler/src/clock.rs
  crates/scheduler/src/executor.rs
  crates/scheduler/src/scheduler.rs
  crates/scheduler/src/test_scheduler.rs
  crates/scheduler/src/tests.rs
Labels: cla-signed

#36971 Update Editor::select_larger_syntax_node
  crates/editor/src/editor.rs
  crates/editor/src/editor_tests.rs
  crates/editor/src/test.rs
  crates/util/src/test/marked_text.rs
Labels: cla-signed

#35994 editor: Implement Go to next/prev Document Highlight
  crates/editor/src/actions.rs
  crates/editor/src/editor.rs
  crates/editor/src/editor_tests.rs
  crates/editor/src/element.rs
Labels: cla-signed

#36973 project_panel: Add action to open file in split pane
  assets/keymaps/vim.json
  crates/project_panel/src/project_panel.rs
Labels: cla-signed

#37575 Allow outline modal toggling
  crates/outline/src/outline.rs
Labels: cla-signed

#37118 language_models: Make Copilot Chat resilient to new model vendors and add tokenizer-based token counting
  crates/copilot/src/copilot_chat.rs
  crates/language_models/src/provider/copilot_chat.rs
Labels: ai, cla-signed

#37031 git: Add uncommit action
  crates/git_ui/src/git_panel.rs
  crates/git_ui/src/git_ui.rs
Labels: cla-signed

#37316 Fix SVG preview not refreshing on external file changes
  Cargo.lock
  crates/svg_preview/Cargo.toml
  crates/svg_preview/src/svg_preview_view.rs
Labels: cla-signed

#37872 Skip "open this directory" menu entry in case of errors
  crates/file_finder/src/open_path_prompt.rs
  crates/file_finder/src/open_path_prompt_tests.rs
Labels: cla-signed

#37874 Consistently map syntax node navigation actions on macOS
  assets/keymaps/default-linux.json
  assets/keymaps/default-macos.json
  assets/keymaps/default-windows.json
Labels: cla-signed

#37723 ollama: Add mistral-nemo
  crates/ollama/src/ollama.rs
Labels: ai, cla-signed

#37746 Fix import not working on first column first row of file
  crates/project/src/lsp_store.rs
Labels: cla-signed

#37879 Potentially fix welcome banner in agent panel not going away
  crates/agent_ui/src/agent_panel.rs
Labels: cla-signed

#37884 workspace: Fix tab bar drop target height when no unpinned tabs present
  crates/workspace/src/pane.rs
Labels: cla-signed

#37893 Revert "markdown: Add support for inline HTML `img` tags inside text (#37264)"
  crates/markdown_preview/src/markdown_elements.rs
  crates/markdown_preview/src/markdown_parser.rs
  crates/markdown_preview/src/markdown_renderer.rs
Labels: cla-signed

#37912 editor: Fix adjacent custom highlights interfering with each other
  crates/editor/src/display_map.rs
  crates/editor/src/display_map/custom_highlights.rs
Labels: cla-signed

#37876 acp: Add keybindings for authorizing tool calls
  Cargo.lock
  assets/keymaps/default-linux.json
  assets/keymaps/default-macos.json
  assets/keymaps/default-windows.json
  crates/acp_thread/src/acp_thread.rs
  crates/agent_ui/Cargo.toml
  crates/agent_ui/src/acp/thread_view.rs
  crates/agent_ui/src/agent_ui.rs
Labels: cla-signed

#37917 Bump Zed to v0.205
  Cargo.lock
  crates/zed/Cargo.toml
Labels: cla-signed

#37919 editor: Wrap placeholder if text overflows
  crates/agent_ui/src/acp/message_editor.rs
  crates/agent_ui/src/acp/thread_history.rs
  crates/agent_ui/src/acp/thread_view.rs
  crates/agent_ui/src/active_thread.rs
  crates/agent_ui/src/agent_configuration/manage_profiles_modal.rs
  crates/agent_ui/src/inline_prompt_editor.rs
  crates/agent_ui/src/message_editor.rs
  crates/agent_ui/src/thread_history.rs
  crates/collab_ui/src/collab_panel.rs
  crates/debugger_ui/src/new_process_modal.rs
  crates/debugger_ui/src/session/running/breakpoint_list.rs
  crates/debugger_ui/src/session/running/console.rs
  crates/debugger_ui/src/session/running/memory_view.rs
  crates/editor/src/editor.rs
  crates/editor/src/element.rs
  crates/extensions_ui/src/extensions_ui.rs
  crates/git_ui/src/commit_modal.rs
  crates/git_ui/src/git_panel.rs
  crates/git_ui/src/git_ui.rs
  crates/go_to_line/src/go_to_line.rs
  crates/keymap_editor/src/keymap_editor.rs
  crates/language_models/src/provider/anthropic.rs
  crates/language_models/src/provider/bedrock.rs
  crates/language_models/src/provider/deepseek.rs
  crates/language_models/src/provider/google.rs
  crates/language_models/src/provider/mistral.rs
  crates/language_models/src/provider/open_router.rs
  crates/outline_panel/src/outline_panel.rs
  crates/picker/src/head.rs
  crates/picker/src/picker.rs
  crates/recent_projects/src/remote_servers.rs
  crates/rules_library/src/rules_library.rs
  crates/search/src/buffer_search.rs
  crates/search/src/project_search.rs
  crates/ui_input/src/ui_input.rs
  crates/zeta/src/rate_completion_modal.rs
Labels: cla-signed

#37928 keymap_editor: Move OpenKeymapEditor action into zed_actions
  Cargo.lock
  crates/keymap_editor/src/keymap_editor.rs
  crates/title_bar/Cargo.toml
  crates/title_bar/src/title_bar.rs
  crates/zed/src/zed/app_menus.rs
  crates/zed_actions/src/lib.rs
Labels: cla-signed

#37929 Fix crash when filtering items in Picker
  crates/agent_ui/src/agent_configuration/tool_picker.rs
  crates/agent_ui/src/context_picker/file_context_picker.rs
  crates/agent_ui/src/context_picker/rules_context_picker.rs
  crates/agent_ui/src/context_picker/symbol_context_picker.rs
  crates/agent_ui/src/context_picker/thread_context_picker.rs
  crates/collab_ui/src/collab_panel/contact_finder.rs
  crates/debugger_ui/src/attach_modal.rs
  crates/debugger_ui/src/new_process_modal.rs
  crates/extensions_ui/src/extension_version_selector.rs
  crates/file_finder/src/file_finder.rs
  crates/git_ui/src/branch_picker.rs
  crates/git_ui/src/picker_prompt.rs
  crates/jj_ui/src/bookmark_picker.rs
  crates/language_selector/src/language_selector.rs
  crates/line_ending_selector/src/line_ending_selector.rs
  crates/onboarding/src/base_keymap_picker.rs
  crates/project_symbols/src/project_symbols.rs
  crates/settings_profile_selector/src/settings_profile_selector.rs
  crates/snippets_ui/src/snippets_ui.rs
  crates/tab_switcher/src/tab_switcher.rs
  crates/tasks_ui/src/modal.rs
  crates/theme_selector/src/icon_theme_selector.rs
  crates/theme_selector/src/theme_selector.rs
  crates/toolchain_selector/src/toolchain_selector.rs
  crates/vim/src/state.rs
Labels: cla-signed

#37704 Add whitespace_map setting
  assets/settings/default.json
  crates/editor/src/element.rs
  crates/language/src/language_settings.rs
Labels: cla-signed

#37935 Remove unnecessary `Option` from functions querying buffer outline
  crates/agent/src/context.rs
  crates/agent2/src/tools/grep_tool.rs
  crates/agent_ui/src/inline_assistant.rs
  crates/assistant_slash_commands/src/symbols_command.rs
  crates/assistant_tool/src/outline.rs
  crates/assistant_tools/src/grep_tool.rs
  crates/language/src/buffer.rs
  crates/language/src/buffer_tests.rs
  crates/languages/src/css.rs
  crates/languages/src/typescript.rs
  crates/multi_buffer/src/multi_buffer.rs
  crates/outline_panel/src/outline_panel.rs
  crates/project/src/task_inventory.rs
Labels: cla-signed

#37941 Make plans backwards compatible
  crates/agent_ui/src/acp/thread_view.rs
  crates/agent_ui/src/agent_configuration.rs
  crates/agent_ui/src/agent_panel.rs
  crates/agent_ui/src/debug.rs
  crates/agent_ui/src/message_editor.rs
  crates/agent_ui/src/ui/end_trial_upsell.rs
  crates/agent_ui/src/ui/preview/usage_callouts.rs
  crates/ai_onboarding/src/agent_panel_onboarding_content.rs
  crates/ai_onboarding/src/ai_onboarding.rs
  crates/ai_onboarding/src/ai_upsell_card.rs
  crates/ai_onboarding/src/edit_prediction_onboarding_content.rs
  crates/client/src/test.rs
  crates/client/src/user.rs
  crates/cloud_api_types/src/cloud_api_types.rs
  crates/cloud_llm_client/src/cloud_llm_client.rs
  crates/language_model/src/model/cloud_model.rs
  crates/language_models/src/provider/cloud.rs
  crates/title_bar/src/title_bar.rs
Labels: cla-signed

#37797 Compress minidumps
  Cargo.lock
  crates/crashes/Cargo.toml
  crates/crashes/src/crashes.rs
  crates/zed/src/reliability.rs
Labels: cla-signed

#37786 Rodio audio
  .config/hakari.toml
  Cargo.lock
  Cargo.toml
  crates/audio/Cargo.toml
  crates/audio/src/audio.rs
  crates/audio/src/audio_settings.rs
  crates/audio/src/replays.rs
  crates/audio/src/rodio_ext.rs
  crates/call/Cargo.toml
  crates/call/src/call_impl/room.rs
  crates/gpui/src/app/async_context.rs
  crates/livekit_client/Cargo.toml
  crates/livekit_client/examples/test_app.rs
  crates/livekit_client/src/livekit_client.rs
  crates/livekit_client/src/livekit_client/playback.rs
  crates/livekit_client/src/livekit_client/playback/source.rs
  crates/livekit_client/src/record.rs
  crates/livekit_client/src/test.rs
  crates/zed/Cargo.toml
  crates/zed/src/zed.rs
  tooling/workspace-hack/Cargo.toml
Labels: cla-signed

#37948 scheduler: Add missing constructs for Cloud
  crates/scheduler/src/clock.rs
  crates/scheduler/src/test_scheduler.rs
Labels: cla-signed

#37933 Fix wrong cursor shape description in Configuring Zed page
  docs/src/configuring-zed.md
Labels: cla-signed

#38097 Add debug methods for visually annotating ranges
  crates/editor/src/element.rs
  crates/multi_buffer/src/multi_buffer.rs
  crates/text/src/text.rs
Labels: cla-signed

#38098 collab: Add Orb cancellation date to `billing_subscriptions` table
  crates/collab/migrations/20250913035238_add_orb_cancellation_date_to_billing_subscriptions.sql
Labels: cla-signed

#37428 Add setting to show/hide title bar
  assets/settings/default.json
  crates/title_bar/src/title_bar.rs
  crates/title_bar/src/title_bar_settings.rs
  crates/workspace/src/workspace.rs
  docs/src/configuring-zed.md
  docs/src/visual-customization.md
Labels: cla-signed

#37927 Expose REPL Settings
  Cargo.lock
  assets/settings/default.json
  crates/repl/Cargo.toml
  crates/repl/src/outputs/plain.rs
  crates/repl/src/repl.rs
  crates/repl/src/repl_settings.rs
  docs/src/configuring-zed.md
Labels: cla-signed

#38123 Fix typo in default settings
  assets/settings/default.json
Labels: cla-signed
