Repository zed-industries/zed, pull requests merged in 2025-10, with the labels that each got.

#39267 zeta_cli: Avoid unnecessary rechecks in `retrieval-stats`
  crates/edit_prediction_context/src/syntax_index.rs
  crates/zeta_cli/src/main.rs
Labels: cla-signed

#39235 gpui: Respect macOS 'Do Nothing' window double-click setting
  crates/gpui/src/platform/mac/window.rs
Labels: cla-signed

#39223 editor: Preserve grapheme identity during rewrap
  crates/editor/src/editor.rs
Labels: cla-signed

#38887 multi_buffer: Fix handling of `ExcerptId::max()`
  crates/editor/src/editor.rs
  crates/editor/src/element.rs
  crates/editor/src/hover_links.rs
  crates/editor/src/hover_popover.rs
  crates/editor/src/inlay_hint_cache.rs
  crates/editor/src/items.rs
  crates/editor/src/movement.rs
  crates/editor/src/scroll.rs
  crates/editor/src/selections_collection.rs
  crates/multi_buffer/src/anchor.rs
  crates/multi_buffer/src/multi_buffer.rs
  crates/vim/src/helix.rs
Labels: cla-signed

#39244 Enable vim mode within the rules editor
  crates/rules_library/src/rules_library.rs
Labels: cla-signed, community champion

#39254 Remove obsolete extensions and avoid loading or downloading them
  .config/hakari.toml
  Cargo.lock
  Cargo.toml
  crates/extension_host/src/extension_host.rs
  extensions/ruff/Cargo.toml
  extensions/ruff/LICENSE-APACHE
  extensions/ruff/README.md
  extensions/ruff/extension.toml
  extensions/ruff/src/ruff.rs
  extensions/snippets/Cargo.toml
  extensions/snippets/LICENSE-APACHE
  extensions/snippets/extension.toml
  extensions/snippets/src/snippets.rs
Labels: cla-signed

#39297 perf: Functionality for CI integration
  tooling/perf/src/lib.rs
  tooling/perf/src/main.rs
Labels: cla-signed

#39306 docs: Improve description on some agent settings
  docs/src/ai/agent-settings.md
Labels: cla-signed

#39295 terminal: Log selected shell
  crates/terminal/src/terminal.rs
Labels: cla-signed

#39253 ui: Add a `TreeViewItem` component
  crates/ui/src/components.rs
  crates/ui/src/components/tree_view_item.rs
Labels: cla-signed

#39329 settings ui: Use the tree view item component and other design tweaks
  crates/settings_ui/src/components.rs
  crates/settings_ui/src/settings_ui.rs
Labels: cla-signed

#39327 Add codex acp
  Cargo.lock
  crates/agent_servers/src/acp.rs
  crates/agent_servers/src/agent_servers.rs
  crates/agent_servers/src/codex.rs
  crates/agent_servers/src/e2e_tests.rs
  crates/agent_ui/src/acp/thread_view.rs
  crates/agent_ui/src/agent_configuration.rs
  crates/agent_ui/src/agent_panel.rs
  crates/agent_ui/src/agent_ui.rs
  crates/feature_flags/src/flags.rs
  crates/project/Cargo.toml
  crates/project/src/agent_server_store.rs
  crates/settings/src/settings_content/agent.rs
Labels: cla-signed

#39261 Add an action for that runs a sequence of actions
  crates/settings/src/keymap_file.rs
  crates/settings/src/settings.rs
  crates/workspace/src/workspace.rs
  crates/zed/src/zed.rs
Labels: cla-signed

#38881 project panel: Make updates asynchronous
  Cargo.lock
  crates/project/src/project.rs
  crates/project_panel/Cargo.toml
  crates/project_panel/benches/linux_repo_snapshot.txt
  crates/project_panel/benches/sorting.rs
  crates/project_panel/src/project_panel.rs
  crates/project_panel/src/project_panel_tests.rs
  crates/util/src/paths.rs
  crates/zed/src/zed.rs
  typos.toml
Labels: cla-signed

#39343 settings ui: Add basic setting page fields to UI
  crates/settings/src/settings_content.rs
  crates/settings/src/settings_content/editor.rs
  crates/settings/src/settings_content/language.rs
  crates/settings/src/settings_content/project.rs
  crates/settings/src/settings_content/terminal.rs
  crates/settings/src/settings_content/theme.rs
  crates/settings/src/settings_content/workspace.rs
  crates/settings_ui/src/components.rs
  crates/settings_ui/src/settings_ui.rs
Labels: cla-signed

#39262 Add more selection options to app menus
  crates/zed/src/zed/app_menus.rs
Labels: cla-signed

#39353 editor: Improve inlay color border
  crates/editor/src/display_map/inlay_map.rs
Labels: cla-signed, community champion

#39325 agent: Fix Claude Code terminal login on Windows
  Cargo.lock
  crates/agent_ui/Cargo.toml
  crates/agent_ui/src/acp/thread_view.rs
Labels: cla-signed

#39363 acp: Alphabetize the external agents list
  crates/agent_ui/src/agent_configuration.rs
  crates/agent_ui/src/agent_panel.rs
Labels: cla-signed

#38885 Add missing `GEMINI.md` rule file for `gemini-cli`
  GEMINI.md
Labels: ai, cla-signed

#39373 Add extension licensing documentation
  docs/src/extensions/developing-extensions.md
Labels: cla-signed

#39380 Subscribe to CodexAcpFeatureFlag
  crates/project/src/agent_server_store.rs
Labels: cla-signed

#39391 docs: Re-add context for `lsp_highlight_debounce`
  docs/src/configuring-zed.md
Labels: cla-signed

#39304 file_finder: Fix history items not using worktree path
  crates/file_finder/src/file_finder.rs
  crates/file_finder/src/file_finder_tests.rs
Labels: cla-signed

#39225 ui: Implement graceful autohiding for scrollbars
  crates/editor/src/signature_help.rs
  crates/ui/src/components/scrollbar.rs
Labels: cla-signed

#39302 git: Use environment from login shell to search for system git binary, and prefer it to the bundled binary
  crates/fs/src/fake_git_repo.rs
  crates/fs/src/fs.rs
  crates/git/src/repository.rs
  crates/project/src/git_store.rs
  crates/project/src/project_tests.rs
Labels: cla-signed

#39398 JSON based migrations
  Cargo.lock
  crates/migrator/Cargo.toml
  crates/migrator/src/migrator.rs
  crates/zed/src/zed.rs
  tooling/workspace-hack/Cargo.toml
Labels: cla-signed

#39349 acp_thread: Respect terminal settings shell for terminal tool environment
  crates/acp_thread/src/acp_thread.rs
  crates/assistant_tools/src/terminal_tool.rs
  crates/languages/src/python.rs
  crates/project/src/direnv.rs
  crates/project/src/environment.rs
  crates/project/src/project.rs
  crates/project/src/terminals.rs
  crates/task/src/shell_builder.rs
  crates/task/src/task.rs
  crates/terminal/src/terminal.rs
  crates/util/src/shell.rs
  crates/util/src/shell_env.rs
  crates/util/src/util.rs
Labels: cla-signed

#39400 Don't allow formatters in format on save
  crates/migrator/src/migrations.rs
  crates/migrator/src/migrations/m_2025_10_02/settings.rs
  crates/migrator/src/migrator.rs
  crates/onboarding/src/editing_page.rs
  crates/project/src/lsp_store.rs
  crates/settings/src/settings_content/language.rs
Labels: cla-signed

#39404 collab: Add `token_spend_in_cents` column to `billing_subscriptions` table
  crates/collab/migrations/20251002214229_add_token_spend_in_cents_to_billing_subscriptions.sql
Labels: cla-signed

#39413 Fix Claude Code login regression
  crates/agent_ui/src/acp/thread_view.rs
Labels: cla-signed

#39419 Display-only ACP terminals
  Cargo.lock
  crates/acp_thread/src/acp_thread.rs
  crates/agent_servers/Cargo.toml
  crates/agent_servers/src/acp.rs
  crates/terminal/src/terminal.rs
Labels: cla-signed

#36342 file_icons: Add support for multiple file extensions
  crates/file_icons/src/file_icons.rs
  crates/util/src/paths.rs
Labels: cla-signed

#39436 multi_buffer: Fix `ExcerptId::max()` handling in `summaries_for_anchors`
  crates/multi_buffer/src/multi_buffer.rs
Labels: cla-signed

#39441 Fix rust-analyzer startup issue in single-file worktrees
  crates/project/src/lsp_store.rs
Labels: cla-signed

#39456 Clarify extension license detection in docs
  docs/src/extensions/developing-extensions.md
Labels: cla-signed

#39408 settings_ui: Write local settings files
  crates/project/src/project.rs
  crates/settings_ui/Cargo.toml
  crates/settings_ui/src/settings_ui.rs
Labels: cla-signed

#39396 Keep folds at cursor open for "fold at level"
  crates/editor/src/editor.rs
  crates/editor/src/editor_tests.rs
  crates/editor/src/selections_collection.rs
Labels: cla-signed

#39472 extension_host: Load granted extension capabilities from settings
  assets/settings/default.json
  crates/extension_host/src/extension_settings.rs
  crates/extension_host/src/wasm_host.rs
  crates/remote_server/src/headless_project.rs
  crates/settings/src/settings_content.rs
  crates/settings/src/settings_content/extension.rs
Labels: cla-signed

#39468 agent: Introduce `agent_buffer_font_size` setting
  assets/settings/default.json
  crates/agent_ui/src/acp/entry_view_state.rs
  crates/agent_ui/src/acp/message_editor.rs
  crates/agent_ui/src/acp/thread_view.rs
  crates/agent_ui/src/agent_panel.rs
  crates/assistant_tools/src/edit_file_tool.rs
  crates/migrator/src/migrations.rs
  crates/migrator/src/migrations/m_2025_10_03/settings.rs
  crates/migrator/src/migrator.rs
  crates/settings/src/settings_content/theme.rs
  crates/theme/src/settings.rs
  crates/theme/src/theme.rs
Labels: cla-signed

#36513 settings ui: Improve numeric stepper component interface
  Cargo.lock
  crates/editor/src/editor_settings_controls.rs
  crates/gpui/src/app/context.rs
  crates/gpui/src/geometry.rs
  crates/gpui/src/interactive.rs
  crates/onboarding/Cargo.toml
  crates/onboarding/src/editing_page.rs
  crates/ui/src/components.rs
  crates/ui/src/components/numeric_stepper.rs
  crates/ui_input/Cargo.toml
  crates/ui_input/src/numeric_stepper.rs
  crates/ui_input/src/ui_input.rs
  crates/ui_macros/src/derive_register_component.rs
Labels: cla-signed

#39414 Build Windows installer for all releases
  .github/workflows/ci.yml
Labels: cla-signed

#39485 Bring CI back up
  .github/workflows/ci.yml
Labels: cla-signed

#39484 settings_ui: Implement sub pages
  crates/settings_ui/src/settings_ui.rs
Labels: cla-signed

#39493 Make `ShellBuilder::new` not branch on a remote shell
  crates/acp_thread/src/acp_thread.rs
  crates/agent_servers/src/acp.rs
  crates/assistant_tools/src/terminal_tool.rs
  crates/debugger_ui/src/session/running.rs
  crates/project/src/debugger/locators/cargo.rs
  crates/project/src/terminals.rs
  crates/remote/src/transport/ssh.rs
  crates/task/src/shell_builder.rs
  crates/terminal/src/terminal.rs
  crates/terminal_view/src/terminal_panel.rs
Labels: cla-signed

#39500 Fix double-clicking on non-empty title bar area
  crates/gpui/src/platform/windows/events.rs
Labels: cla-signed

#39502 Fix caption buttons going off-screen
  crates/title_bar/src/platform_title_bar.rs
Labels: cla-signed

#39430 Add ability to hide status bar
  assets/settings/default.json
  crates/editor/src/editor_settings.rs
  crates/go_to_line/src/cursor_position.rs
  crates/language_selector/src/active_buffer_language.rs
  crates/settings/src/settings_content.rs
  crates/settings/src/settings_content/editor.rs
  crates/settings/src/settings_content/workspace.rs
  crates/settings_ui/src/settings_ui.rs
  crates/workspace/src/workspace.rs
  crates/workspace/src/workspace_settings.rs
  docs/src/configuring-zed.md
Labels: cla-signed

#39494 settings_ui: Dynamic navbar filtering
  Cargo.lock
  crates/settings_ui/Cargo.toml
  crates/settings_ui/src/settings_ui.rs
  crates/ui/src/components/disclosure.rs
  crates/ui/src/components/list/list_header.rs
  crates/ui/src/components/list/list_item.rs
  crates/ui/src/components/tree_view_item.rs
Labels: cla-signed

#39510 Don't use PTY in the display-only terminal
  crates/acp_thread/src/acp_thread.rs
  crates/agent_servers/src/acp.rs
  crates/agent_ui/src/acp/thread_view.rs
  crates/assistant_tools/src/terminal_tool.rs
  crates/debugger_ui/src/session/running.rs
  crates/terminal/src/terminal.rs
  crates/terminal_view/src/terminal_view.rs
Labels: cla-signed

#39528 Decouple agent reregistration from settings changes
  crates/agent_ui/src/acp/thread_view.rs
  crates/project/src/agent_server_store.rs
  crates/project/src/project.rs
Labels: cla-signed

#39538 Fix CRLF handling in display-only terminals
  crates/terminal/src/terminal.rs
Labels: cla-signed

#39537 terminal: Fix terminal split pane opening in wrong directory
  crates/terminal_view/src/terminal_panel.rs
Labels: cla-signed

#39544 askpass: Don't log error when user cancels askpass prompt
  crates/askpass/src/askpass.rs
  crates/project/src/git_store.rs
Labels: cla-signed

#39199 workspace: Add `Close Multibuffers` pane context menu entry
  crates/agent_ui/src/agent_diff.rs
  crates/collab_ui/src/channel_view.rs
  crates/debugger_ui/src/stack_trace_view.rs
  crates/diagnostics/src/buffer_diagnostics.rs
  crates/diagnostics/src/diagnostics.rs
  crates/editor/src/editor.rs
  crates/editor/src/editor_tests.rs
  crates/editor/src/element.rs
  crates/editor/src/items.rs
  crates/git_ui/src/commit_view.rs
  crates/git_ui/src/file_diff_view.rs
  crates/git_ui/src/project_diff.rs
  crates/git_ui/src/text_diff_view.rs
  crates/image_viewer/src/image_viewer.rs
  crates/onboarding/src/multibuffer_hint.rs
  crates/repl/src/notebook/notebook_ui.rs
  crates/search/src/project_search.rs
  crates/terminal_view/src/terminal_view.rs
  crates/workspace/src/item.rs
  crates/workspace/src/pane.rs
  crates/workspace/src/workspace.rs
  crates/zed/src/zed/quick_action_bar.rs
Labels: cla-signed

#38605 markdown: Add HTML `table` element support
  crates/markdown_preview/src/markdown_minifier.rs
  crates/markdown_preview/src/markdown_parser.rs
  crates/markdown_preview/src/markdown_preview.rs
  crates/markdown_preview/src/markdown_renderer.rs
Labels: cla-signed

#39557 Emit less update events for odd FS events
  crates/fs/src/fs.rs
  crates/project/src/git_store.rs
  crates/project/src/project_tests.rs
  crates/worktree/src/worktree.rs
Labels: cla-signed

#39564 Remove iterations from the slow FS tests
  crates/project/src/project_tests.rs
Labels: cla-signed

#39543 Prep crates for GPUI on crates.io
  .config/hakari.toml
  Cargo.lock
  Cargo.toml
  crates/collections/Cargo.toml
  crates/gpui/Cargo.toml
  crates/gpui/README.md
  crates/gpui_macros/Cargo.toml
  crates/http_client/Cargo.toml
  crates/media/Cargo.toml
  crates/refineable/Cargo.toml
  crates/refineable/derive_refineable/Cargo.toml
  crates/refineable/src/refineable.rs
  crates/semantic_version/Cargo.toml
  crates/sum_tree/Cargo.toml
  crates/util/Cargo.toml
  crates/util/src/paths.rs
  crates/util/src/util.rs
  crates/util_macros/Cargo.toml
  crates/util_macros/src/util_macros.rs
  tooling/perf/Cargo.toml
  tooling/perf/src/main.rs
Labels: cla-signed

#39573 Add script to bump GPUI version
  Cargo.lock
  Cargo.toml
  tooling/xtask/Cargo.toml
  tooling/xtask/src/main.rs
  tooling/xtask/src/tasks.rs
  tooling/xtask/src/tasks/publish_gpui.rs
Labels: cla-signed

#39576 Swap the start building and login buttons
  crates/onboarding/src/onboarding.rs
  crates/paths/src/paths.rs
Labels: cla-signed

#39580 chore: Remove unused settings ui module
  crates/editor/src/editor.rs
  crates/editor/src/editor_settings_controls.rs
Labels: cla-signed

#39568 editor: Shrink `DisplayMapSnapshot` from `824` to `256` bytes
  crates/agent_ui/src/acp/message_editor.rs
  crates/agent_ui/src/agent_diff.rs
  crates/agent_ui/src/inline_assistant.rs
  crates/collab/src/tests/channel_buffer_tests.rs
  crates/collab_ui/src/channel_view.rs
  crates/debugger_ui/src/stack_trace_view.rs
  crates/debugger_ui/src/tests/debugger_panel.rs
  crates/debugger_ui/src/tests/stack_frame_list.rs
  crates/diagnostics/src/diagnostic_renderer.rs
  crates/diagnostics/src/diagnostics_tests.rs
  crates/editor/src/display_map.rs
  crates/editor/src/display_map/block_map.rs
  crates/editor/src/display_map/fold_map.rs
  crates/editor/src/display_map/wrap_map.rs
  crates/editor/src/editor.rs
  crates/editor/src/editor_tests.rs
  crates/editor/src/element.rs
  crates/editor/src/highlight_matching_bracket.rs
  crates/editor/src/hover_links.rs
  crates/editor/src/hover_popover.rs
  crates/editor/src/indent_guides.rs
  crates/editor/src/items.rs
  crates/editor/src/mouse_context_menu.rs
  crates/editor/src/movement.rs
  crates/editor/src/scroll.rs
  crates/editor/src/selections_collection.rs
  crates/editor/src/tasks.rs
  crates/editor/src/test.rs
  crates/editor/src/test/editor_lsp_test_context.rs
  crates/editor/src/test/editor_test_context.rs
  crates/git_ui/src/project_diff.rs
  crates/language_tools/src/syntax_tree_view.rs
  crates/vim/src/command.rs
  crates/vim/src/helix.rs
  crates/vim/src/helix/boundary.rs
  crates/vim/src/helix/paste.rs
  crates/vim/src/motion.rs
  crates/vim/src/normal/change.rs
  crates/vim/src/normal/delete.rs
  crates/vim/src/normal/mark.rs
  crates/vim/src/normal/paste.rs
  crates/vim/src/normal/search.rs
  crates/vim/src/object.rs
  crates/vim/src/replace.rs
  crates/vim/src/surrounds.rs
  crates/vim/src/test.rs
  crates/vim/src/vim.rs
  crates/vim/src/visual.rs
Labels: cla-signed

#39287 zed: Show GPUI Inspector item in Dev build menus
  crates/zed/src/main.rs
  crates/zed/src/zed.rs
  crates/zed/src/zed/app_menus.rs
Labels: cla-signed

#39491 settings ui: Add numeric steppers to settings UI
  Cargo.lock
  assets/settings/default.json
  crates/gpui/src/text_system.rs
  crates/settings/Cargo.toml
  crates/settings/src/merge_from.rs
  crates/settings/src/settings_content/theme.rs
  crates/settings/src/vscode_import.rs
  crates/settings_ui/Cargo.toml
  crates/settings_ui/src/settings_ui.rs
  crates/theme/src/settings.rs
  crates/ui_input/src/numeric_stepper.rs
Labels: cla-signed

#39466 acp_thread: If available, use git bash over powershell in terminal tool
  Cargo.lock
  crates/acp_thread/src/acp_thread.rs
  crates/assistant_tools/src/terminal_tool.rs
  crates/prompt_store/src/prompts.rs
  crates/util/Cargo.toml
  crates/util/src/shell.rs
  crates/util/src/util.rs
Labels: cla-signed

#39624 search: Introduce more yield points in project search `pending_search` task
  crates/search/src/project_search.rs
Labels: cla-signed

#39076 Add note about `inode/directory` to Zed desktop entry
  crates/zed/resources/zed.desktop.in
Labels: cla-signed

#39527 docs: Fix Tree-sitter casing in `vim.md`
  docs/src/vim.md
Labels: cla-signed

#39623 Remove chat from docs
  docs/src/channels.md
Labels: cla-signed

#39631 settings ui: Fix panic from reading `BufferLineHeight` custom variant
  crates/settings/src/settings_content/theme.rs
  crates/settings_ui/src/page_data.rs
  crates/settings_ui/src/settings_ui.rs
Labels: cla-signed

#39643 ci: Show output of failed tests at the end too
  .github/actions/run_tests/action.yml
  .github/actions/run_tests_windows/action.yml
Labels: cla-signed

#39642 git_ui: Update project diff more aggressively
  crates/git_ui/src/project_diff.rs
  crates/project/src/git_store.rs
  crates/project/src/project_tests.rs
  crates/project_panel/src/project_panel.rs
Labels: cla-signed

#39475 askpass: Fix cli path when executed in a remote server
  Cargo.lock
  crates/askpass/Cargo.toml
  crates/askpass/src/askpass.rs
  crates/util/src/paths.rs
  crates/util/src/util.rs
  crates/zed/Cargo.toml
  crates/zed/src/main.rs
Labels: cla-signed

#38836 Remove cx from ThemeSettings
  Cargo.lock
  crates/agent/src/thread.rs
  crates/agent_settings/src/agent_settings.rs
  crates/agent_ui/src/acp/entry_view_state.rs
  crates/agent_ui/src/acp/thread_view.rs
  crates/agent_ui/src/agent_diff.rs
  crates/assistant_tools/src/terminal_tool.rs
  crates/audio/src/audio_settings.rs
  crates/auto_update/src/auto_update.rs
  crates/call/src/call_settings.rs
  crates/client/src/client.rs
  crates/collab/src/tests/editor_tests.rs
  crates/collab/src/tests/randomized_test_helpers.rs
  crates/collab/src/tests/test_server.rs
  crates/collab_ui/src/panel_settings.rs
  crates/dap/src/debugger_settings.rs
  crates/editor/src/editor_settings.rs
  crates/extension_host/src/extension_settings.rs
  crates/file_finder/src/file_finder_settings.rs
  crates/file_icons/Cargo.toml
  crates/file_icons/src/file_icons.rs
  crates/git_hosting_providers/src/settings.rs
  crates/git_ui/src/file_diff_view.rs
  crates/git_ui/src/git_panel_settings.rs
  crates/git_ui/src/text_diff_view.rs
  crates/go_to_line/src/cursor_position.rs
  crates/image_viewer/src/image_viewer_settings.rs
  crates/journal/src/journal.rs
  crates/language/src/language_settings.rs
  crates/language_models/src/settings.rs
  crates/onboarding/src/basics_page.rs
  crates/outline_panel/src/outline_panel_settings.rs
  crates/project/src/agent_server_store.rs
  crates/project/src/project.rs
  crates/project/src/project_settings.rs
  crates/project_panel/src/project_panel_settings.rs
  crates/recent_projects/src/remote_connections.rs
  crates/repl/src/jupyter_settings.rs
  crates/repl/src/repl_settings.rs
  crates/settings/src/base_keymap_setting.rs
  crates/settings/src/settings_store.rs
  crates/settings_profile_selector/src/settings_profile_selector.rs
  crates/storybook/src/storybook.rs
  crates/terminal/src/terminal_settings.rs
  crates/theme/src/fallback_themes.rs
  crates/theme/src/settings.rs
  crates/theme/src/theme.rs
  crates/theme_extension/src/theme_extension.rs
  crates/theme_selector/src/icon_theme_selector.rs
  crates/theme_selector/src/theme_selector.rs
  crates/title_bar/src/title_bar_settings.rs
  crates/vim/src/vim.rs
  crates/vim_mode_setting/src/vim_mode_setting.rs
  crates/workspace/src/item.rs
  crates/workspace/src/workspace.rs
  crates/workspace/src/workspace_settings.rs
  crates/worktree/src/worktree_settings.rs
  crates/zed/src/main.rs
  crates/zed/src/zed.rs
  crates/zlog_settings/src/zlog_settings.rs
Labels: cla-signed

#39640 settings_ui: Language settings UI
  assets/settings/default.json
  crates/language/src/language_settings.rs
  crates/settings/src/settings_content/language.rs
  crates/settings_ui/src/page_data.rs
  crates/settings_ui/src/settings_ui.rs
Labels: cla-signed

#39646 windows: Use nc-esque ssh askpass auth for remoting
  Cargo.lock
  crates/askpass/Cargo.toml
  crates/askpass/src/askpass.rs
  crates/askpass/src/encrypted_password.rs
  crates/project/src/git_store.rs
  crates/remote/src/transport/ssh.rs
Labels: cla-signed

#39154 Fix floating file chooser
  Cargo.lock
  crates/gpui/Cargo.toml
  crates/gpui/src/platform/linux/platform.rs
  crates/gpui/src/platform/linux/wayland/client.rs
  crates/gpui/src/platform/linux/x11/client.rs
  crates/gpui/src/platform/linux/x11/window.rs
  tooling/workspace-hack/Cargo.toml
Labels: cla-signed, community champion

#39674 Improve command logging and `log_err` module paths
  crates/context_server/src/transport/stdio_transport.rs
  crates/dap/src/transport.rs
  crates/extensions_ui/src/extensions_ui.rs
  crates/gpui/src/platform/windows/clipboard.rs
  crates/lsp/src/lsp.rs
  crates/onboarding/src/welcome.rs
  crates/repl/src/repl_sessions_ui.rs
  crates/util/src/util.rs
  crates/workspace/src/workspace.rs
  crates/zed/src/zed.rs
Labels: cla-signed

#39688 agent: Remove some unused code from the `Thread`
  crates/agent/src/thread.rs
Labels: cla-signed

#39691 Revert "Remove cx from ThemeSettings (#38836)"
  Cargo.lock
  crates/agent/src/thread.rs
  crates/agent_settings/src/agent_settings.rs
  crates/agent_ui/src/acp/entry_view_state.rs
  crates/agent_ui/src/acp/thread_view.rs
  crates/agent_ui/src/agent_diff.rs
  crates/assistant_tools/src/terminal_tool.rs
  crates/audio/src/audio_settings.rs
  crates/auto_update/src/auto_update.rs
  crates/call/src/call_settings.rs
  crates/client/src/client.rs
  crates/collab/src/tests/editor_tests.rs
  crates/collab/src/tests/randomized_test_helpers.rs
  crates/collab/src/tests/test_server.rs
  crates/collab_ui/src/panel_settings.rs
  crates/dap/src/debugger_settings.rs
  crates/editor/src/editor_settings.rs
  crates/extension_host/src/extension_settings.rs
  crates/file_finder/src/file_finder_settings.rs
  crates/file_icons/Cargo.toml
  crates/file_icons/src/file_icons.rs
  crates/git_hosting_providers/src/settings.rs
  crates/git_ui/src/file_diff_view.rs
  crates/git_ui/src/git_panel_settings.rs
  crates/git_ui/src/text_diff_view.rs
  crates/go_to_line/src/cursor_position.rs
  crates/image_viewer/src/image_viewer_settings.rs
  crates/journal/src/journal.rs
  crates/language/src/language_settings.rs
  crates/language_models/src/settings.rs
  crates/onboarding/src/basics_page.rs
  crates/outline_panel/src/outline_panel_settings.rs
  crates/project/src/agent_server_store.rs
  crates/project/src/project.rs
  crates/project/src/project_settings.rs
  crates/project_panel/src/project_panel_settings.rs
  crates/recent_projects/src/remote_connections.rs
  crates/repl/src/jupyter_settings.rs
  crates/repl/src/repl_settings.rs
  crates/settings/src/base_keymap_setting.rs
  crates/settings/src/settings_store.rs
  crates/settings_profile_selector/src/settings_profile_selector.rs
  crates/storybook/src/storybook.rs
  crates/terminal/src/terminal_settings.rs
  crates/theme/src/fallback_themes.rs
  crates/theme/src/settings.rs
  crates/theme/src/theme.rs
  crates/theme_extension/src/theme_extension.rs
  crates/theme_selector/src/icon_theme_selector.rs
  crates/theme_selector/src/theme_selector.rs
  crates/title_bar/src/title_bar_settings.rs
  crates/vim/src/vim.rs
  crates/vim_mode_setting/src/vim_mode_setting.rs
  crates/workspace/src/item.rs
  crates/workspace/src/workspace.rs
  crates/workspace/src/workspace_settings.rs
  crates/worktree/src/worktree_settings.rs
  crates/zed/src/main.rs
  crates/zed/src/zed.rs
  crates/zlog_settings/src/zlog_settings.rs
Labels: cla-signed

#39690 Fix an issue where scrollbars would capture too many events
  crates/ui/src/components/scrollbar.rs
Labels: cla-signed

#39459 Remove empty line when collapsing diagnostics
  crates/editor/src/display_map/block_map.rs
Labels: cla-signed

#38925 windows: Fix handling of AltGr to avoid conflicts
  crates/gpui/src/platform/windows/events.rs
Labels: cla-signed

#39677 Remove unused `blake3` dependency
  Cargo.toml
Labels: cla-signed

#39633 settings ui: Move selected nav bar entry on scroll
  crates/gpui/src/elements/div.rs
  crates/settings_ui/src/settings_ui.rs
Labels: cla-signed

#39700 settings ui: Add more UX improvements
  assets/keymaps/default-linux.json
  assets/keymaps/default-macos.json
  assets/keymaps/default-windows.json
  crates/settings_ui/src/settings_ui.rs
  crates/ui/src/components/button/button.rs
  crates/ui/src/components/button/button_like.rs
  crates/ui/src/components/keybinding_hint.rs
  crates/ui/src/components/tree_view_item.rs
  crates/ui_input/src/font_picker.rs
  crates/ui_input/src/numeric_stepper.rs
  crates/zed/src/zed/app_menus.rs
Labels: cla-signed

#39731 ui: Rename and simplify NumberField component
  crates/onboarding/src/editing_page.rs
  crates/settings_ui/src/page_data.rs
  crates/settings_ui/src/settings_ui.rs
  crates/ui_input/src/number_field.rs
  crates/ui_input/src/ui_input.rs
Labels: cla-signed

#39733 settings_ui: Pre preview launch cleanup
  crates/settings/src/settings_content.rs
  crates/settings/src/settings_content/terminal.rs
  crates/settings/src/settings_content/workspace.rs
  crates/settings_ui/src/page_data.rs
  crates/settings_ui/src/settings_ui.rs
Labels: cla-signed

#39742 settings ui: Add another batch of UX fixes and improvements
  crates/onboarding/src/welcome.rs
  crates/settings_ui/src/page_data.rs
  crates/settings_ui/src/settings_ui.rs
  crates/ui/src/components/tree_view_item.rs
  crates/ui_input/src/number_field.rs
Labels: cla-signed

#39760 Fix more settings UX problems
  Cargo.lock
  crates/gpui/src/platform.rs
  crates/settings_ui/Cargo.toml
  crates/settings_ui/src/settings_ui.rs
  crates/ui/src/components/tree_view_item.rs
Labels: cla-signed

#39780 acp: Don't display failed terminal call on display only terminals
  crates/agent_ui/src/acp/thread_view.rs
Labels: cla-signed

#39768 windows: Do not exit from app in dev builds when cli is not found
  crates/zed/src/main.rs
Labels: cla-signed

#39480 file_finder: Fix path matching on starting slash
  crates/file_finder/src/file_finder.rs
  crates/file_finder/src/file_finder_tests.rs
Labels: cla-signed

#39787 agent2: Expand auto-retries for completion errors
  crates/agent2/src/thread.rs
Labels: cla-signed

#39789 keymap editor: Adjust the "edit in keymap.json" button
  crates/keymap_editor/src/keymap_editor.rs
Labels: cla-signed

#39795 Fix configuring shell in project settings
  crates/settings/src/settings_content/project.rs
  crates/settings/src/settings_content/terminal.rs
  crates/terminal/src/terminal_settings.rs
Labels: cla-signed
