Repository zed-industries/zed, pull requests merged in 2025-04, with the labels that each got.

#27811 Don't use `dbg!` in test input
  crates/vim/src/test.rs
  crates/vim/test_data/test_delete_unmatched_brace.json
Labels: cla-signed

#27805 vim: Update `:set`
  crates/vim/src/command.rs
Labels: cla-signed

#27809 Fix code actions tooltip overlapping with action context menu
  crates/editor/src/editor.rs
Labels: cla-signed

#27822 Remove assistant `ContextSnapshot`
  crates/assistant2/src/active_thread.rs
  crates/assistant2/src/buffer_codegen.rs
  crates/assistant2/src/context.rs
  crates/assistant2/src/context_store.rs
  crates/assistant2/src/context_strip.rs
  crates/assistant2/src/message_editor.rs
  crates/assistant2/src/terminal_inline_assistant.rs
  crates/assistant2/src/thread.rs
  crates/assistant2/src/ui/context_pill.rs
Labels: cla-signed

#27825 Debugger: Fix breakpoint serialization
  crates/editor/src/editor.rs
  crates/project/src/debugger/breakpoint_store.rs
  crates/workspace/src/persistence.rs
  crates/workspace/src/workspace.rs
Labels: cla-signed

#27828 Undo a refactor of `buffer_path_log_err`
  crates/assistant2/src/context_store.rs
Labels: cla-signed

#27830 workspace: Fix SSH remote restore on second open + Fix panel not opening automatically on new SSH remote
  crates/recent_projects/src/remote_servers.rs
  crates/recent_projects/src/ssh_connections.rs
  crates/workspace/src/workspace.rs
Labels: cla-signed

#27833 assistant2: Fix issue with included directories in context picker
  crates/assistant2/src/context_picker/file_context_picker.rs
  crates/assistant2/src/context_store.rs
Labels: cla-signed

#27734 Use symmetric padding in signature popovers
  crates/editor/src/signature_help.rs
Labels: cla-signed

#27838 Use pagination for GitHub issue response script
  script/issue_response/main.js
Labels: cla-signed

#27840 assistant2: Remove check icon from successful tool calls
  crates/assistant2/src/active_thread.rs
Labels: cla-signed

#27844 edit prediction: Show display mode options just for Zed
  crates/inline_completion_button/src/inline_completion_button.rs
Labels: cla-signed

#27847 assistant2: Allow profiles to enable all context servers
  assets/settings/default.json
  crates/assistant2/src/assistant_configuration/manage_profiles_modal.rs
  crates/assistant2/src/assistant_configuration/tool_picker.rs
  crates/assistant2/src/thread_store.rs
  crates/assistant_settings/src/agent_profile.rs
  crates/assistant_settings/src/assistant_settings.rs
  crates/assistant_tool/src/tool_working_set.rs
Labels: cla-signed

#27846 assistant2: Allow clicking on `@mentions`
  crates/assistant2/src/active_thread.rs
  crates/assistant2/src/context_picker.rs
  crates/assistant2/src/context_picker/completion_provider.rs
  crates/assistant2/src/thread.rs
Labels: cla-signed

#27474 Update docs for some settings
  docs/src/configuring-zed.md
Labels: cla-signed

#27852 workspace: Do not call set_active when deserializing a dock if that dock was not visible
  crates/workspace/src/dock.rs
Labels: cla-signed

#27859 assistant2: Rename key context to `AgentPanel`
  assets/keymaps/default-linux.json
  assets/keymaps/default-macos.json
  crates/assistant2/src/assistant_panel.rs
Labels: cla-signed

#27858 assistant2: Use "Agent Panel" nomenclature for panel tooltip
  crates/assistant2/src/assistant_panel.rs
Labels: cla-signed

#27856 Show commit author, not committer
  crates/git/src/repository.rs
  crates/git_ui/src/commit_view.rs
  crates/git_ui/src/git_panel.rs
  crates/project/src/git_store.rs
  crates/proto/proto/zed.proto
Labels: cla-signed

#26759 python: Add recognition of worktree -> venv links
  crates/languages/src/python.rs
Labels: cla-signed

#27853 ui: Introduce Banner component
  crates/ui/src/components.rs
  crates/ui/src/components/banner.rs
Labels: cla-signed

#27864 assistant2: Update some text to use "agent" nomenclature
  crates/assistant2/src/assistant_panel.rs
Labels: cla-signed

#27866 Fix restore button
  crates/editor/src/editor.rs
Labels: cla-signed

#27867 language_model: Add `supports_tools` method to `LanguageModel`
  crates/language_model/src/fake_provider.rs
  crates/language_model/src/language_model.rs
  crates/language_models/src/provider/anthropic.rs
  crates/language_models/src/provider/bedrock.rs
  crates/language_models/src/provider/cloud.rs
  crates/language_models/src/provider/copilot_chat.rs
  crates/language_models/src/provider/deepseek.rs
  crates/language_models/src/provider/google.rs
  crates/language_models/src/provider/lmstudio.rs
  crates/language_models/src/provider/mistral.rs
  crates/language_models/src/provider/ollama.rs
  crates/language_models/src/provider/open_ai.rs
Labels: cla-signed

#27868 find-replace tool: Return diff in output
  crates/assistant_tools/src/find_replace_file_tool.rs
Labels: cla-signed

#27869 assistant2: Ensure errors are also displayed in populated new thread view
  crates/assistant2/src/assistant_panel.rs
  crates/language_model/src/language_model.rs
  crates/language_models/src/provider/cloud.rs
  crates/ui/src/components/banner.rs
Labels: cla-signed

#27870 assistant2: Add affordances for when the selected model does not support tools
  crates/assistant2/src/profile_selector.rs
  crates/assistant2/src/thread.rs
Labels: cla-signed

#27874 vim: Add :Git
  crates/vim/src/command.rs
  docs/src/vim.md
Labels: cla-signed

#27872 assistant2: Fix notification max width
  crates/assistant2/src/ui/agent_notification.rs
Labels: cla-signed

#27871 nix: Separate debug output
  flake.nix
  nix/shell.nix
Labels: cla-signed, nix

#27877 assistant2: Rename `assistant2` actions to `agent`
  assets/keymaps/default-linux.json
  assets/keymaps/default-macos.json
  crates/assistant2/src/assistant.rs
Labels: cla-signed

#27568 Finish removing git repository state and scanning logic from worktrees
  Cargo.lock
  crates/activity_indicator/src/activity_indicator.rs
  crates/assistant2/src/thread.rs
  crates/call/src/call_impl/room.rs
  crates/collab/src/db/queries/projects.rs
  crates/collab/src/db/queries/rooms.rs
  crates/collab/src/tests/integration_tests.rs
  crates/collab/src/tests/random_project_collaboration_tests.rs
  crates/collab/src/tests/remote_editing_collaboration_tests.rs
  crates/editor/src/git/blame.rs
  crates/fs/src/fake_git_repo.rs
  crates/git/src/repository.rs
  crates/git_ui/src/branch_picker.rs
  crates/git_ui/src/commit_modal.rs
  crates/git_ui/src/git_panel.rs
  crates/git_ui/src/project_diff.rs
  crates/multi_buffer/src/multi_buffer.rs
  crates/project/Cargo.toml
  crates/project/src/buffer_store.rs
  crates/project/src/connection_manager.rs
  crates/project/src/debugger/dap_store.rs
  crates/project/src/environment.rs
  crates/project/src/git_store.rs
  crates/project/src/git_store/git_traversal.rs
  crates/project/src/lsp_store.rs
  crates/project/src/project.rs
  crates/project/src/project_tests.rs
  crates/project/src/task_store.rs
  crates/project/src/toolchain_store.rs
  crates/project_panel/src/project_panel.rs
  crates/proto/proto/zed.proto
  crates/proto/src/proto.rs
  crates/remote_server/src/remote_editing_tests.rs
  crates/sum_tree/src/tree_map.rs
  crates/title_bar/src/title_bar.rs
  crates/vim/src/normal/search.rs
  crates/worktree/Cargo.toml
  crates/worktree/src/worktree.rs
  crates/worktree/src/worktree_tests.rs
Labels: cla-signed

#27876 Use new multibuffer excerpts in find-all-references and friends
  crates/assistant2/src/assistant_diff.rs
  crates/editor/src/editor.rs
  crates/editor/src/editor_tests.rs
  crates/git_ui/src/commit_view.rs
  crates/git_ui/src/project_diff.rs
  crates/multi_buffer/src/multi_buffer.rs
  crates/multi_buffer/src/multi_buffer_tests.rs
Labels: cla-signed

#26948 Add persistence to command palette history
  Cargo.lock
  crates/command_palette/Cargo.toml
  crates/command_palette/src/command_palette.rs
  crates/command_palette/src/persistence.rs
Labels: cla-signed

#27851 assistant2: Summarize threads in context and continue long ones
  crates/assistant2/src/active_thread.rs
  crates/assistant2/src/assistant.rs
  crates/assistant2/src/assistant_panel.rs
  crates/assistant2/src/context.rs
  crates/assistant2/src/context_picker/completion_provider.rs
  crates/assistant2/src/context_store.rs
  crates/assistant2/src/inline_assistant.rs
  crates/assistant2/src/message_editor.rs
  crates/assistant2/src/terminal_inline_assistant.rs
  crates/assistant2/src/thread.rs
  crates/assistant2/src/thread_store.rs
  crates/assistant2/src/ui/context_pill.rs
Labels: cla-signed

#27857 Improve tracking for agent edits
  Cargo.lock
  assets/keymaps/default-linux.json
  assets/keymaps/default-macos.json
  crates/assistant2/src/assistant.rs
  crates/assistant2/src/assistant_diff.rs
  crates/assistant2/src/message_editor.rs
  crates/assistant2/src/thread.rs
  crates/assistant_tool/Cargo.toml
  crates/assistant_tool/src/action_log.rs
  crates/assistant_tools/Cargo.toml
  crates/assistant_tools/src/create_file_tool.rs
  crates/assistant_tools/src/edit_files_tool.rs
  crates/assistant_tools/src/find_replace_file_tool.rs
  crates/assistant_tools/src/replace.rs
  crates/git/src/repository.rs
  crates/language/src/buffer.rs
  crates/language/src/buffer_tests.rs
  crates/project/src/lsp_store.rs
  crates/text/src/patch.rs
Labels: cla-signed

#27882 git: Use doc comments for `ResetMode` variants
  crates/git/src/repository.rs
Labels: cla-signed

#27881 nix: Clean up build
  .cargo/config.toml
  .github/workflows/release_nightly.yml
  Cargo.lock
  Cargo.toml
  crates/fs/Cargo.toml
  crates/livekit_client/.cargo/config.toml
  crates/livekit_client/Cargo.toml
  nix/build.nix
  nix/shell.nix
Labels: cla-signed

#27875 Bump tree-sitter-rust to 0.24
  Cargo.lock
  Cargo.toml
Labels: cla-signed

#27884 Fix a bug that prevented repositories from being deduplicated
  crates/project/src/git_store.rs
  crates/project/src/project_tests.rs
Labels: cla-signed

#27886 Bump revision for `livekit-rust-sdks`
  Cargo.lock
  crates/livekit_client/Cargo.toml
Labels: cla-signed

#27887 Rename `assistant2` to `agent`
  Cargo.lock
  Cargo.toml
  crates/agent/Cargo.toml
  crates/agent/LICENSE-GPL
  crates/agent/src/active_thread.rs
  crates/agent/src/assistant.rs
  crates/agent/src/assistant_configuration.rs
  crates/agent/src/assistant_configuration/add_context_server_modal.rs
  crates/agent/src/assistant_configuration/manage_profiles_modal.rs
  crates/agent/src/assistant_configuration/manage_profiles_modal/profile_modal_header.rs
  crates/agent/src/assistant_configuration/tool_picker.rs
  crates/agent/src/assistant_diff.rs
  crates/agent/src/assistant_model_selector.rs
  crates/agent/src/assistant_panel.rs
  crates/agent/src/buffer_codegen.rs
  crates/agent/src/context.rs
  crates/agent/src/context_picker.rs
  crates/agent/src/context_picker/completion_provider.rs
  crates/agent/src/context_picker/fetch_context_picker.rs
  crates/agent/src/context_picker/file_context_picker.rs
  crates/agent/src/context_picker/symbol_context_picker.rs
  crates/agent/src/context_picker/thread_context_picker.rs
  crates/agent/src/context_store.rs
  crates/agent/src/context_strip.rs
  crates/agent/src/history_store.rs
  crates/agent/src/inline_assistant.rs
  crates/agent/src/inline_prompt_editor.rs
  crates/agent/src/message_editor.rs
  crates/agent/src/profile_selector.rs
  crates/agent/src/terminal_codegen.rs
  crates/agent/src/terminal_inline_assistant.rs
  crates/agent/src/thread.rs
  crates/agent/src/thread_history.rs
  crates/agent/src/thread_store.rs
  crates/agent/src/tool_use.rs
  crates/agent/src/ui.rs
  crates/agent/src/ui/agent_notification.rs
  crates/agent/src/ui/context_pill.rs
  crates/assistant_eval/Cargo.toml
  crates/assistant_eval/src/eval.rs
  crates/assistant_eval/src/headless_assistant.rs
  crates/zed/Cargo.toml
  crates/zed/src/main.rs
  crates/zed/src/zed.rs
Labels: cla-signed

#27891 Don't unwrap on bad zstd data
  crates/rpc/src/proto.rs
Labels: cla-signed

#27824 vim: Add `g?` convert to `Rot13`/`Rot47`
  assets/keymaps/vim.json
  crates/editor/src/actions.rs
  crates/editor/src/editor.rs
  crates/editor/src/element.rs
  crates/gpui/src/keymap/context.rs
  crates/vim/src/normal.rs
  crates/vim/src/normal/convert.rs
  crates/vim/src/state.rs
  crates/vim/src/vim.rs
  crates/vim/test_data/test_change_rot13_motion.json
  crates/vim/test_data/test_change_rot13_object.json
  crates/vim/test_data/test_convert_to_rot13.json
Labels: cla-signed

#27903 assistant2: Use snake_case for tool names
  crates/assistant_tools/src/batch_tool.rs
  crates/assistant_tools/src/code_symbols_tool.rs
  crates/assistant_tools/src/copy_path_tool.rs
  crates/assistant_tools/src/create_directory_tool.rs
  crates/assistant_tools/src/create_file_tool.rs
  crates/assistant_tools/src/delete_path_tool.rs
  crates/assistant_tools/src/edit_files_tool.rs
  crates/assistant_tools/src/find_replace_file_tool.rs
  crates/assistant_tools/src/list_directory_tool.rs
  crates/assistant_tools/src/move_path_tool.rs
  crates/assistant_tools/src/path_search_tool.rs
  crates/assistant_tools/src/read_file_tool.rs
  crates/assistant_tools/src/regex_search_tool.rs
  crates/assistant_tools/src/symbol_info_tool.rs
Labels: cla-signed

#27905 Fix Gemini function calling
  crates/language_models/src/provider/google.rs
Labels: cla-signed

#27907 agent: Update tool names in default profiles to reflect snake_cased rename
  assets/settings/default.json
Labels: cla-signed

#27909 language_models: Denote Copilot Chat as not supporting tools
  crates/language_models/src/provider/copilot_chat.rs
Labels: cla-signed

#27919 Ensure rejecting a hunk dismisses the diff
  crates/assistant_tool/src/action_log.rs
  crates/assistant_tools/src/edit_files_tool.rs
  crates/assistant_tools/src/find_replace_file_tool.rs
Labels: cla-signed

#27923 Avoid requiring confirmation for tools that edit buffers
  crates/assistant_tools/src/create_file_tool.rs
  crates/assistant_tools/src/edit_files_tool.rs
  crates/assistant_tools/src/find_replace_file_tool.rs
Labels: cla-signed

#27925 agent: Include context with first message that introduced it
  crates/agent/src/context.rs
  crates/agent/src/thread.rs
Labels: cla-signed

#27928 agent: Return an error to the model when trying to use a tool that is disabled
  crates/agent/src/thread.rs
Labels: cla-signed

#27921 Fix bug that prevented deletion-only hunks from being kept correctly
  crates/assistant_tool/src/action_log.rs
Labels: cla-signed

#27927 agent: Add more guidelines to system prompt
  assets/prompts/assistant_system_prompt.hbs
Labels: cla-signed

#27926 agent: Fix thinking step showing up as pending even though it is completed
  crates/agent/src/active_thread.rs
Labels: cla-signed

#27930 language_model: Remove `use_any_tool` method from `LanguageModel`
  crates/language_model/src/fake_provider.rs
  crates/language_model/src/language_model.rs
  crates/language_models/src/provider/anthropic.rs
  crates/language_models/src/provider/bedrock.rs
  crates/language_models/src/provider/cloud.rs
  crates/language_models/src/provider/copilot_chat.rs
  crates/language_models/src/provider/deepseek.rs
  crates/language_models/src/provider/google.rs
  crates/language_models/src/provider/lmstudio.rs
  crates/language_models/src/provider/mistral.rs
  crates/language_models/src/provider/ollama.rs
  crates/language_models/src/provider/open_ai.rs
Labels: cla-signed

#27934 Add comment box to negative feedback reaction
  crates/agent/src/active_thread.rs
Labels: cla-signed

#27937 file_finder: Prioritize file name matches over path matches
  crates/file_finder/src/file_finder.rs
  crates/file_finder/src/file_finder_tests.rs
Labels: cla-signed

#27939 agent: Add newtype for profile IDs
  crates/agent/src/assistant.rs
  crates/agent/src/assistant_configuration/manage_profiles_modal.rs
  crates/agent/src/assistant_configuration/tool_picker.rs
  crates/agent/src/profile_selector.rs
  crates/agent/src/thread_store.rs
  crates/assistant_settings/src/agent_profile.rs
  crates/assistant_settings/src/assistant_settings.rs
Labels: cla-signed

#27938 Log error and proceed when failing to load repo environment
  crates/project/src/environment.rs
  crates/project/src/git_store.rs
Labels: cla-signed

#27932 agent: Improve action confirmation UX
  assets/icons/check_double.svg
  assets/settings/default.json
  crates/agent/src/active_thread.rs
  crates/agent/src/assistant_configuration.rs
  crates/agent/src/assistant_panel.rs
  crates/assistant_settings/src/assistant_settings.rs
  crates/assistant_tools/src/bash_tool.rs
  crates/icons/src/icons.rs
Labels: cla-signed

#27931 Fix flickering when staging and unstaging files
  crates/editor/src/git/blame.rs
  crates/git_ui/src/git_panel.rs
  crates/git_ui/src/project_diff.rs
  crates/project/src/git_store.rs
Labels: cla-signed

#27942 Debugger: Add stop on entry support to debug adapter configs
  crates/dap_adapters/src/gdb.rs
  crates/dap_adapters/src/go.rs
  crates/dap_adapters/src/javascript.rs
  crates/dap_adapters/src/lldb.rs
  crates/dap_adapters/src/php.rs
  crates/dap_adapters/src/python.rs
  crates/debugger_ui/src/session/inert.rs
  crates/debugger_ui/src/tests/attach_modal.rs
  crates/languages/src/rust.rs
  crates/project/src/debugger/dap_store.rs
  crates/project/src/project.rs
  crates/task/src/debug_format.rs
  crates/task/src/lib.rs
  crates/task/src/task_template.rs
Labels: cla-signed

#27945 Bump Zed to v0.182
  Cargo.lock
  crates/zed/Cargo.toml
Labels: cla-signed

#27943 Use worktree qualified paths in agent file context + some code cleanup
  crates/agent/src/context_store.rs
  crates/project/src/project.rs
Labels: cla-signed

#27940 agent: Do some cleanup of feedback comments submission
  crates/agent/src/active_thread.rs
Labels: cla-signed

#27924 zed: Include full debug info in debug builds
  .github/actions/run_tests_windows/action.yml
  Cargo.toml
Labels: cla-signed

#27941 aws_http_client: Copy response headers
  crates/aws_http_client/src/aws_http_client.rs
Labels: cla-signed

#27607 docs: Add example of Ruby plain minitest task
  docs/src/languages/ruby.md
Labels: cla-signed

#27953 debugger: Add args argument to debugger launch config
  crates/dap_adapters/src/gdb.rs
  crates/dap_adapters/src/go.rs
  crates/dap_adapters/src/javascript.rs
  crates/dap_adapters/src/lldb.rs
  crates/dap_adapters/src/php.rs
  crates/dap_adapters/src/python.rs
  crates/debugger_ui/src/session/inert.rs
  crates/debugger_ui/src/tests/attach_modal.rs
  crates/languages/src/rust.rs
  crates/project/src/debugger/dap_store.rs
  crates/project/src/debugger/locator_store/cargo.rs
  crates/project/src/debugger/session.rs
  crates/project/src/project.rs
  crates/task/src/debug_format.rs
  crates/task/src/lib.rs
Labels: cla-signed

#27453 Add `completions.lsp_insert_mode` setting to control what ranges are replaced when a completion is inserted
  assets/settings/default.json
  crates/copilot/src/copilot_completion_provider.rs
  crates/editor/src/editor_tests.rs
  crates/language/src/language_settings.rs
  crates/project/src/lsp_command.rs
  crates/project/src/lsp_store.rs
  docs/src/configuring-zed.md
Labels: cla-signed

#27955 agent: Change loading label if command is waiting on permission
  crates/agent/src/message_editor.rs
Labels: cla-signed

#27971 agent: Update thread label to use plural form
  crates/agent/src/context_picker.rs
Labels: cla-signed

#27893 Use new multibuffer excerpts in project search
  Cargo.lock
  crates/multi_buffer/Cargo.toml
  crates/multi_buffer/src/multi_buffer.rs
  crates/multi_buffer/src/multi_buffer_tests.rs
  crates/project/src/search.rs
  crates/search/src/project_search.rs
Labels: cla-signed

#27976 renovate: Ignore `Cargo.toml` for `workspace-hack`
  renovate.json
Labels: cla-signed

#27980 gpui: Fix background for WrappedLine
  crates/gpui/src/elements/text.rs
  crates/gpui/src/text_system/line.rs
Labels: cla-signed

#27979 Debugger: Add pretty printers for Cargo-located tasks
  crates/project/src/debugger/dap_store.rs
  crates/project/src/debugger/locator_store/cargo.rs
  crates/project/src/debugger/locator_store/locators.rs
Labels: cla-signed

#27990 workspace-hack: remove openssl from remote_server
  .config/hakari.toml
  Cargo.lock
  tooling/workspace-hack/Cargo.toml
Labels: cla-signed, run-bundling

#27181 assistant_eval: Add ACE framework
  Cargo.lock
  Cargo.toml
  crates/assistant_eval/Cargo.toml
  crates/assistant_eval/README.md
  crates/assistant_eval/src/eval.rs
  crates/assistant_eval/src/get_exercise.rs
  crates/assistant_eval/src/git_commands.rs
  crates/assistant_eval/src/headless_assistant.rs
  crates/assistant_eval/src/judge.rs
  crates/assistant_eval/src/main.rs
  crates/assistant_eval/src/templates_eval.rs
Labels: cla-signed

#28008 Fix `test_peers_following_each_other` for Windows
  crates/collab/src/tests/following_tests.rs
Labels: cla-signed

#28014 chore: Remove stray eprintln
  crates/multi_buffer/src/multi_buffer.rs
Labels: cla-signed

#28015 editor: Fix active line number highlighting regression
  crates/editor/src/element.rs
Labels: cla-signed

#27914 agent: Include active file in recent history
  crates/agent/src/context_picker.rs
  crates/agent/src/context_picker/completion_provider.rs
  crates/file_finder/src/file_finder.rs
  crates/workspace/src/workspace.rs
Labels: cla-signed

#27950 Temporarily disable flaky conflicted-cherry-pick test
  crates/project/src/project_tests.rs
Labels: cla-signed

#28024 rust: Improve runnable detection for test modules
  crates/languages/src/rust/runnables.scm
Labels: cla-signed

#28026 Clear path-based excerpt data properly
  crates/multi_buffer/src/multi_buffer.rs
Labels: cla-signed

#28027 agent: Add button to continue iterating once all reviews are done
  assets/icons/forward_arrow.svg
  crates/agent/src/agent_diff.rs
  crates/icons/src/icons.rs
Labels: cla-signed

#27837 debugger: Start on tabless design
  .zed/debug.json
  assets/icons/arrow_down_right.svg
  assets/icons/arrow_up_right.svg
  assets/icons/bug_off.svg
  assets/icons/circle_off.svg
  assets/icons/power.svg
  crates/dap_adapters/src/lldb.rs
  crates/dap_adapters/src/python.rs
  crates/debugger_ui/src/attach_modal.rs
  crates/debugger_ui/src/debugger_panel.rs
  crates/debugger_ui/src/debugger_ui.rs
  crates/debugger_ui/src/new_session_modal.rs
  crates/debugger_ui/src/session.rs
  crates/debugger_ui/src/session/failed.rs
  crates/debugger_ui/src/session/inert.rs
  crates/debugger_ui/src/session/running.rs
  crates/debugger_ui/src/session/running/console.rs
  crates/debugger_ui/src/session/running/module_list.rs
  crates/debugger_ui/src/session/running/stack_frame_list.rs
  crates/debugger_ui/src/session/running/variable_list.rs
  crates/debugger_ui/src/session/starting.rs
  crates/debugger_ui/src/tests/attach_modal.rs
  crates/debugger_ui/src/tests/debugger_panel.rs
  crates/icons/src/icons.rs
  crates/project/src/debugger/dap_store.rs
  crates/project/src/debugger/session.rs
  crates/project/src/task_inventory.rs
  crates/task/src/debug_format.rs
  crates/tasks_ui/src/modal.rs
  crates/tasks_ui/src/tasks_ui.rs
  crates/ui/src/components/button/toggle_button.rs
  crates/ui/src/components/toggle.rs
  crates/workspace/src/workspace.rs
Labels: cla-signed

#28030 agent: Handle tool use without text
  crates/agent/src/active_thread.rs
  crates/agent/src/thread.rs
  crates/agent/src/tool_use.rs
Labels: cla-signed

#28029 Fix soft-wrapping with fold creases
  crates/editor/src/display_map.rs
  crates/editor/src/display_map/block_map.rs
  crates/editor/src/display_map/fold_map.rs
  crates/editor/src/display_map/tab_map.rs
  crates/editor/src/display_map/wrap_map.rs
  crates/editor/src/editor.rs
  crates/editor/src/element.rs
  crates/gpui/src/text_system/line_wrapper.rs
  crates/language/src/buffer.rs
Labels: cla-signed

#28038 Remove unused `extract_tool_args_from_events` functions
  crates/anthropic/src/anthropic.rs
  crates/language_models/src/provider/bedrock.rs
  crates/open_ai/src/open_ai.rs
Labels: cla-signed

#28037 agent: Add token count in the thread view
  crates/agent/src/assistant_panel.rs
  crates/agent/src/message_editor.rs
  crates/agent/src/thread.rs
  crates/assistant_context_editor/src/context_editor.rs
  crates/language_model/src/language_model.rs
Labels: cla-signed

#28034 Allow to temporarily stop LSP servers
  crates/collab/src/rpc.rs
  crates/editor/src/actions.rs
  crates/editor/src/editor.rs
  crates/editor/src/element.rs
  crates/project/src/lsp_store.rs
  crates/project/src/project.rs
  crates/proto/proto/zed.proto
  crates/proto/src/proto.rs
Labels: cla-signed

#27967 agent: Snapshot context in user message instead of recreating it
  crates/agent/src/active_thread.rs
  crates/agent/src/context.rs
  crates/agent/src/thread.rs
  crates/agent/src/thread_store.rs
  crates/assistant_eval/src/headless_assistant.rs
  crates/assistant_tool/src/action_log.rs
Labels: cla-signed

#28031 ui_input: `TextField` -> `SingleLineInput`
  Cargo.lock
  crates/agent/Cargo.toml
  crates/agent/src/assistant_configuration/add_context_server_modal.rs
  crates/ui_input/Cargo.toml
  crates/ui_input/src/ui_input.rs
Labels: cla-signed

#28043 Use more appropriate action for Vim word completions
  assets/keymaps/vim.json
  crates/editor/src/editor.rs
  crates/language/src/buffer.rs
Labels: cla-signed

#28051 Add tool use support for OpenAI models
  crates/language_models/src/provider/cloud.rs
  crates/language_models/src/provider/open_ai.rs
  crates/open_ai/src/open_ai.rs
Labels: cla-signed

#28021 chore: Bump Rust version to 1.86
  Dockerfile-collab
  crates/agent/src/active_thread.rs
  crates/collab/src/rpc.rs
  crates/file_finder/src/new_path_prompt.rs
  crates/git/src/status.rs
  crates/git_ui/src/picker_prompt.rs
  crates/gpui/src/key_dispatch.rs
  crates/gpui/src/platform/mac/metal_renderer.rs
  crates/language/src/buffer.rs
  crates/language/src/language_registry.rs
  crates/project_panel/src/project_panel.rs
  crates/prompt_store/src/prompts.rs
  crates/rope/src/chunk.rs
  crates/vim/src/motion.rs
  crates/vim/src/test/neovim_backed_test_context.rs
  crates/zed/src/zed/open_listener.rs
  rust-toolchain.toml
Labels: cla-signed

#28056 open_ai: Disable `parallel_tool_calls`
  crates/language_models/src/provider/cloud.rs
  crates/language_models/src/provider/open_ai.rs
  crates/open_ai/src/open_ai.rs
Labels: cla-signed

#28059 gpui: Avoid dereferencing null pointer in `MacWindow::active_window`
  crates/gpui/src/platform/mac/window.rs
Labels: cla-signed

#28049 Fix panic calling blocks_intersecting_buffer_range with an empty range
  crates/editor/src/display_map/block_map.rs
Labels: cla-signed

#28062 ci: Prettier GitHub Actions display
  .github/workflows/ci.yml
Labels: cla-signed

#28061 nix: Fix the `cargo-bundle` override
  nix/build.nix
Labels: cla-signed, nix, run-nix

#28045 Listen for changes to the configuration of the attached device too
  crates/livekit_client/src/livekit_client/playback.rs
Labels: cla-signed

#28075 Scroll to first hunk when clicking on a file to review in Agent Panel
  crates/agent/src/agent_diff.rs
  crates/agent/src/message_editor.rs
Labels: cla-signed

#28073 agent: Differentiate @mentions from markdown links
  crates/agent/src/active_thread.rs
  crates/agent/src/context_picker.rs
  crates/agent/src/context_picker/completion_provider.rs
  crates/markdown/src/markdown.rs
Labels: cla-signed

#28077 agent: Show which lines were read when using `read_file` tool
  crates/assistant_tools/src/read_file_tool.rs
Labels: cla-signed

#28080 Implement edit rejection in `ActionLog`
  crates/agent/src/agent_diff.rs
  crates/agent/src/thread.rs
  crates/assistant_tool/src/action_log.rs
Labels: cla-signed

#28085 agent: Add search to Thread History
  crates/agent/src/assistant_panel.rs
  crates/agent/src/history_store.rs
  crates/agent/src/thread_history.rs
Labels: cla-signed

#28060 Make CloseAll keybindings more closely match VS Code
  assets/keymaps/default-linux.json
  assets/keymaps/default-macos.json
Labels: cla-signed

#28055 gpui: Use NSOperatingSystemVersion provided by cocoa
  crates/gpui/src/platform/mac/window.rs
Labels: cla-signed

#25650 tasks: Add spawn option by tag
  assets/keymaps/default-linux.json
  assets/keymaps/default-macos.json
  assets/settings/initial_tasks.json
  crates/task/src/lib.rs
  crates/task/src/serde_helpers.rs
  crates/task/src/task_template.rs
  crates/tasks_ui/src/modal.rs
  crates/tasks_ui/src/tasks_ui.rs
  crates/zed_actions/src/lib.rs
  docs/src/tasks.md
Labels: cla-signed

#28090 collab: Add granular tokens per minute columns to `models` table
  crates/collab/migrations_llm/20250404141155_add_granular_token_limits_to_models.sql
  crates/collab/src/llm/db/tables/model.rs
Labels: cla-signed

#28088 ai: Separate model settings for each feature
  crates/agent/src/active_thread.rs
  crates/agent/src/assistant_configuration/tool_picker.rs
  crates/agent/src/assistant_model_selector.rs
  crates/agent/src/assistant_panel.rs
  crates/agent/src/buffer_codegen.rs
  crates/agent/src/inline_assistant.rs
  crates/agent/src/inline_prompt_editor.rs
  crates/agent/src/message_editor.rs
  crates/agent/src/profile_selector.rs
  crates/agent/src/terminal_codegen.rs
  crates/agent/src/terminal_inline_assistant.rs
  crates/agent/src/thread.rs
  crates/assistant/src/assistant.rs
  crates/assistant/src/assistant_panel.rs
  crates/assistant/src/inline_assistant.rs
  crates/assistant/src/terminal_inline_assistant.rs
  crates/assistant_context_editor/src/context.rs
  crates/assistant_context_editor/src/context_editor.rs
  crates/assistant_eval/src/headless_assistant.rs
  crates/assistant_eval/src/main.rs
  crates/assistant_settings/src/assistant_settings.rs
  crates/assistant_tools/src/edit_files_tool.rs
  crates/git_ui/src/git_panel.rs
  crates/language_model/src/registry.rs
  crates/language_model_selector/src/language_model_selector.rs
  crates/prompt_library/src/prompt_library.rs
  docs/src/assistant/configuration.md
Labels: cla-signed

#28094 squawk: Specify PostgreSQL version in config
  script/lib/squawk.toml
Labels: cla-signed

#28097 collab: Track input and output tokens per minute separately
  crates/collab/src/llm.rs
  crates/collab/src/llm/db/queries/usages.rs
  crates/collab/src/llm/db/tables/usage_measure.rs
  crates/collab/src/llm/db/tests/usage_tests.rs
Labels: cla-signed

#28099 docs: Adjust assistant configuration docs table of contents
  docs/src/assistant/configuration.md
  docs/theme/css/general.css
Labels: cla-signed

#28100 Try adding beta token-efficient tool use for 3.7 Sonnet
  crates/anthropic/src/anthropic.rs
Labels: cla-signed

#28102 agent: Allow renaming threads
  crates/agent/src/active_thread.rs
  crates/agent/src/agent_diff.rs
  crates/agent/src/assistant_panel.rs
  crates/agent/src/thread.rs
Labels: cla-signed

#28041 agent: Remove `edit_files` tool
  Cargo.lock
  crates/assistant_tools/Cargo.toml
  crates/assistant_tools/src/assistant_tools.rs
  crates/assistant_tools/src/edit_files_tool.rs
  crates/assistant_tools/src/edit_files_tool/description.md
  crates/assistant_tools/src/edit_files_tool/edit_action.rs
  crates/assistant_tools/src/edit_files_tool/edit_prompt.md
  crates/assistant_tools/src/edit_files_tool/log.rs
Labels: cla-signed

#28108 collab: Include max input/output tokens per minute on "Language Model Rate Limited" event
  crates/collab/src/llm.rs
Labels: cla-signed

#28106 collab: Capture upstream input/output rate limits from Anthropic
  crates/anthropic/src/anthropic.rs
  crates/collab/src/llm.rs
Labels: cla-signed

#28109 agent: Fix invalid tool names in batch tool description
  crates/assistant_tools/src/batch_tool.rs
Labels: cla-signed

#28111 collab: Adjust rate-limiting measures for Claude 3.7 Sonnet
  crates/collab/src/llm.rs
Labels: cla-signed

#28103 Flesh out helix bindings
  assets/keymaps/vim.json
  crates/vim/src/normal.rs
  crates/vim/src/vim.rs
Labels: cla-signed

#28116 collab: Include more information on some LLM usage log lines
  crates/collab/src/llm.rs
Labels: cla-signed

#28114 agent: Disable redundant tools (might delete later)
  assets/settings/default.json
Labels: cla-signed

#28119 jsx-tag-auto-close: Remove potential source of bugs and panics
  crates/editor/src/jsx_tag_auto_close.rs
Labels: cla-signed

#28117 Fix panic or bad hunks when expanding hunks w/ multiple ranges in 1 hunk
  crates/multi_buffer/src/multi_buffer.rs
  crates/multi_buffer/src/multi_buffer_tests.rs
Labels: cla-signed

#28124 Properly query remote ssh server for language servers by name
  crates/project/src/project.rs
Labels: cla-signed

#28113 agent: Fix deleting threads in history via keyboard
  assets/keymaps/default-macos.json
  crates/agent/src/assistant_panel.rs
  crates/agent/src/thread_history.rs
Labels: cla-signed

#27765 Use consistent ordering for popup menus
  crates/editor/src/code_context_menus.rs
  crates/editor/src/editor.rs
  crates/editor/src/element.rs
Labels: cla-signed

#27807 Use scap library to implement screensharing on X11
  Cargo.lock
  Cargo.toml
  crates/gpui/Cargo.toml
  crates/gpui/src/app.rs
  crates/gpui/src/platform.rs
  crates/gpui/src/platform/linux.rs
  crates/gpui/src/platform/linux/headless/client.rs
  crates/gpui/src/platform/linux/platform.rs
  crates/gpui/src/platform/linux/wayland/client.rs
  crates/gpui/src/platform/linux/x11/client.rs
  crates/gpui/src/platform/mac/platform.rs
  crates/gpui/src/platform/mac/screen_capture.rs
  crates/gpui/src/platform/scap_screen_capture.rs
  crates/gpui/src/platform/test/platform.rs
  crates/gpui/src/platform/windows/platform.rs
  crates/livekit_client/Cargo.toml
  crates/livekit_client/src/livekit_client/playback.rs
  crates/title_bar/src/collab.rs
  crates/workspace/src/workspace.rs
  script/linux
Labels: cla-signed

#28035 Add tool calling support for GitHub Copilot Chat
  crates/copilot/src/copilot_chat.rs
  crates/language_models/src/provider/copilot_chat.rs
Labels: cla-signed

#28129 agent: Hide the scrollbar if there's no mouse movement
  crates/agent/src/active_thread.rs
Labels: cla-signed

#28127 agent: Use Markdown to render tool input and output content
  crates/agent/src/active_thread.rs
  crates/agent/src/tool_use.rs
Labels: cla-signed

#28110 gpui: Avoid dereferencing null pointer in `MacWindow::update_ime_position`
  crates/gpui/src/platform/mac/window.rs
Labels: cla-signed

#28131 debugger_ui: Don't `.unwrap` debug panel access
  crates/debugger_ui/src/debugger_ui.rs
Labels: cla-signed

#28132 agent: Fix panic when opening Agent diff from the workspace
  crates/agent/src/agent_diff.rs
  crates/agent/src/assistant_panel.rs
Labels: cla-signed

#27620 Restore direct use of the input text for Markdown `Text`
  crates/editor/src/hover_popover.rs
  crates/markdown/src/markdown.rs
  crates/markdown/src/parser.rs
Labels: cla-signed

#28130 Split protobufs into separate files
  crates/proto/proto/ai.proto
  crates/proto/proto/app.proto
  crates/proto/proto/buffer.proto
  crates/proto/proto/call.proto
  crates/proto/proto/channel.proto
  crates/proto/proto/core.proto
  crates/proto/proto/debugger.proto
  crates/proto/proto/git.proto
  crates/proto/proto/lsp.proto
  crates/proto/proto/notification.proto
  crates/proto/proto/task.proto
  crates/proto/proto/toolchain.proto
  crates/proto/proto/worktree.proto
  crates/proto/proto/zed.proto
  crates/proto/src/proto.rs
  crates/proto/src/typed_envelope.rs
  crates/rpc/src/message_stream.rs
  crates/rpc/src/peer.rs
  crates/rpc/src/rpc.rs
Labels: cla-signed

#28133 telemetry_events: Rename `AssistantEvent` to `AssistantEventData`
  crates/agent/src/buffer_codegen.rs
  crates/agent/src/inline_assistant.rs
  crates/agent/src/terminal_codegen.rs
  crates/agent/src/terminal_inline_assistant.rs
  crates/assistant/src/inline_assistant.rs
  crates/assistant/src/terminal_inline_assistant.rs
  crates/assistant_context_editor/src/context.rs
  crates/client/src/telemetry.rs
  crates/language_model/src/telemetry.rs
  crates/telemetry_events/src/telemetry_events.rs
Labels: cla-signed

#28093 file_finder: Fix filename matching to require contiguous characters
  crates/file_finder/src/file_finder.rs
Labels: cla-signed

#28032 Introduce "Near" block type
  crates/agent/src/inline_assistant.rs
  crates/assistant/src/inline_assistant.rs
  crates/assistant_context_editor/src/context_editor.rs
  crates/diagnostics/src/diagnostics.rs
  crates/editor/src/display_map.rs
  crates/editor/src/display_map/block_map.rs
  crates/editor/src/display_map/fold_map.rs
  crates/editor/src/editor.rs
  crates/editor/src/editor_tests.rs
  crates/editor/src/element.rs
  crates/multi_buffer/src/anchor.rs
  crates/repl/src/session.rs
Labels: cla-signed

#28134 buffer: Fix broken autoindent when pasting code starting with new line
  crates/language/src/buffer.rs
  crates/language/src/buffer_tests.rs
Labels: cla-signed

#28048 Add actions for calls
  crates/collab_ui/src/collab_panel.rs
  crates/title_bar/src/collab.rs
  crates/title_bar/src/title_bar.rs
  crates/workspace/src/workspace.rs
Labels: cla-signed

#28141 Revert "Use scap library to implement screensharing on X11 (#27807)"
  Cargo.lock
  Cargo.toml
  crates/gpui/Cargo.toml
  crates/gpui/src/app.rs
  crates/gpui/src/platform.rs
  crates/gpui/src/platform/linux.rs
  crates/gpui/src/platform/linux/headless/client.rs
  crates/gpui/src/platform/linux/platform.rs
  crates/gpui/src/platform/linux/wayland/client.rs
  crates/gpui/src/platform/linux/x11/client.rs
  crates/gpui/src/platform/mac/platform.rs
  crates/gpui/src/platform/mac/screen_capture.rs
  crates/gpui/src/platform/scap_screen_capture.rs
  crates/gpui/src/platform/test/platform.rs
  crates/gpui/src/platform/windows/platform.rs
  crates/livekit_client/Cargo.toml
  crates/livekit_client/src/livekit_client/playback.rs
  crates/title_bar/src/collab.rs
  crates/workspace/src/workspace.rs
  script/linux
Labels: cla-signed

#28143 agent: Fix thread summary generation
  crates/agent/src/thread.rs
Labels: cla-signed

#28144 agent: Add missing notify in `ThreadHistory::delete_thread`
  crates/agent/src/thread_history.rs
  crates/agent/src/thread_store.rs
Labels: cla-signed

#28146 agent: Fix tool use output rendering
  crates/agent/src/active_thread.rs
Labels: cla-signed
