Repository zed-industries/zed, pull requests merged in 2025-07, with the labels that each got.

#33693 agent: Only consider zed provider authenticated if TOS is accepted
  crates/agent_ui/src/agent_configuration.rs
  crates/language_models/src/provider/cloud.rs
Labels: cla-signed

#33674 Remove callout for hiring
  docs/src/windows.md
Labels: cla-signed

#33608 gpui: Fix slow scrolling in lists
  crates/gpui/src/elements/list.rs
Labels: cla-signed

#33702 editor: Improve rewrap of markdown lists, todos, and block quotes
  Cargo.lock
  crates/editor/Cargo.toml
  crates/editor/src/editor.rs
  crates/editor/src/editor_tests.rs
  crates/language/src/language.rs
  crates/languages/src/markdown/config.toml
Labels: cla-signed

#33705 languages: Fix `(` wouldn’t autocomplete when `.` is preceded by it in Markdown
  crates/languages/src/markdown/config.toml
Labels: cla-signed

#33706 agent: Clarify upgrade path when starting trial
  crates/language_models/src/provider/cloud.rs
Labels: cla-signed

#33572 ruby: Add basic documentation about debugging
  docs/src/languages/ruby.md
Labels: cla-signed

#33712 language_models: Fix casing of `ZedAiConfiguration`
  crates/language_models/src/provider/cloud.rs
Labels: cla-signed

#33617 docs: Add FreeBSD build instructions and current status
  docs/src/development/freebsd.md
Labels: cla-signed

#32781 Fix IndentGuides story
  crates/storybook/src/stories.rs
  crates/storybook/src/stories/indent_guides.rs
  crates/storybook/src/story_selector.rs
  crates/storybook/src/storybook.rs
  crates/ui_input/src/ui_input.rs
Labels: cla-signed

#33688 ci: Block PRs on Nix build failures
  .github/workflows/ci.yml
Labels: cla-signed

#33723 debugger: Do not set exception breakpoints in initialization sequence in certain conditions
  crates/project/src/debugger/session.rs
Labels: cla-signed

#33731 collab: Add logs to Stripe usage sync job
  crates/collab/src/api/billing.rs
Labels: cla-signed

#33692 Move language-specific debugging docs to the page for each language
  crates/extension_api/wit/since_v0.6.0/dap.wit
  crates/task/src/debug_format.rs
  docs/src/configuring-zed.md
  docs/src/debugger.md
  docs/src/extensions/debugger-extensions.md
  docs/src/languages/c.md
  docs/src/languages/cpp.md
  docs/src/languages/go.md
  docs/src/languages/javascript.md
  docs/src/languages/python.md
  docs/src/languages/ruby.md
  docs/src/languages/rust.md
  docs/src/languages/typescript.md
Labels: cla-signed

#33739 debugger: Don't take JS adapter's suggested child session name if it's empty
  crates/dap_adapters/src/javascript.rs
Labels: cla-signed

#33746 debugger: Fix zoomed panel size regression
  crates/debugger_ui/src/debugger_panel.rs
Labels: cla-signed

#33747 keymap_ui: Add context menu for table rows
  crates/editor/src/mouse_context_menu.rs
  crates/git_ui/src/git_panel.rs
  crates/project_panel/src/project_panel.rs
  crates/settings_ui/src/keybindings.rs
  crates/settings_ui/src/ui_components/table.rs
  crates/ui/src/components/context_menu.rs
  crates/ui/src/components/right_click_menu.rs
  crates/ui/src/components/stories/context_menu.rs
  crates/workspace/src/dock.rs
  crates/workspace/src/pane.rs
  crates/zed/src/zed.rs
  crates/zed/src/zed/quick_action_bar.rs
Labels: cla-signed

#33403 Add page up/down bindings to the Markdown preview
  assets/keymaps/default-linux.json
  assets/keymaps/default-macos.json
  crates/gpui/src/elements/list.rs
  crates/markdown_preview/src/markdown_preview.rs
  crates/markdown_preview/src/markdown_preview_view.rs
Labels: cla-signed

#31366 Add ability to manage dock size via command/shortcut
  assets/keymaps/default-linux.json
  assets/keymaps/default-macos.json
  crates/workspace/src/workspace.rs
Labels: cla-signed

#33742 Respect NO_PROXY env var
  assets/settings/default.json
  crates/reqwest_client/src/reqwest_client.rs
  docs/src/configuring-zed.md
Labels: cla-signed

#33780 Never run transactions using serializable isolation
  crates/collab/src/db.rs
  crates/collab/src/db/queries/billing_customers.rs
  crates/collab/src/db/queries/billing_preferences.rs
  crates/collab/src/db/queries/billing_subscriptions.rs
  crates/collab/src/db/queries/channels.rs
  crates/collab/src/db/queries/contacts.rs
  crates/collab/src/db/queries/contributors.rs
  crates/collab/src/db/queries/embeddings.rs
  crates/collab/src/db/queries/extensions.rs
  crates/collab/src/db/queries/processed_stripe_events.rs
  crates/collab/src/db/queries/projects.rs
  crates/collab/src/db/queries/rooms.rs
  crates/collab/src/db/queries/users.rs
  crates/collab/src/db/tests.rs
  crates/collab/src/db/tests/embedding_tests.rs
  crates/collab/src/lib.rs
  crates/collab/src/main.rs
Labels: cla-signed

#33795 keymap_ui: Fix crash when using a base keymap
  crates/settings/src/keymap_file.rs
Labels: cla-signed

#33783 Bump Zed to v0.195
  Cargo.lock
  crates/zed/Cargo.toml
Labels: cla-signed

#33199 lsp: Complete overloaded signature help implementation
  Cargo.lock
  assets/keymaps/default-linux.json
  assets/keymaps/default-macos.json
  assets/keymaps/linux/emacs.json
  assets/keymaps/macos/emacs.json
  assets/keymaps/vim.json
  crates/editor/src/actions.rs
  crates/editor/src/editor.rs
  crates/editor/src/editor_tests.rs
  crates/editor/src/element.rs
  crates/editor/src/signature_help.rs
  crates/markdown/src/markdown.rs
  crates/project/Cargo.toml
  crates/project/src/lsp_command.rs
  crates/project/src/lsp_command/signature_help.rs
  crates/project/src/lsp_store.rs
  crates/theme/src/styles/accents.rs
  crates/theme/src/styles/colors.rs
  crates/theme/src/styles/players.rs
  crates/theme/src/styles/system.rs
  crates/theme/src/theme.rs
Labels: cla-signed

#33784 Reopen windows concurrently
  crates/zed/src/main.rs
Labels: cla-signed

#33811 agent: Fix issue with duplicated tool names from MCP servers
  crates/agent/src/agent_profile.rs
  crates/agent/src/thread.rs
  crates/agent/src/thread_store.rs
  crates/agent_ui/src/tool_compatibility.rs
  crates/assistant_tool/Cargo.toml
  crates/assistant_tool/src/tool_working_set.rs
Labels: cla-signed

#33794 debugger: Always use runtimeExecutable for node-terminal scenarios
  crates/dap_adapters/src/javascript.rs
Labels: cla-signed

#33816 Add refinements to the keymap UI
  crates/settings_ui/src/keybindings.rs
  crates/ui/src/components/keybinding.rs
  crates/ui/src/components/keybinding_hint.rs
  crates/ui/src/components/stories/keybinding.rs
Labels: cla-signed

#33491 terminal: Expose `selection` in context and add `keep_selection_on_copy` setting
  assets/settings/default.json
  crates/terminal/src/terminal.rs
  crates/terminal/src/terminal_settings.rs
  crates/terminal_view/src/terminal_view.rs
  docs/src/configuring-zed.md
Labels: cla-signed

#33829 windows: More precise handling of `WM_SETTINGCHANGE` and appearance updates
  crates/gpui/src/platform/windows/events.rs
  crates/gpui/src/platform/windows/system_settings.rs
  crates/gpui/src/platform/windows/util.rs
  crates/gpui/src/platform/windows/window.rs
Labels: cla-signed

#33768 agent_ui: Clear error message callout when message is edited or added in same thread
  crates/agent_ui/src/active_thread.rs
Labels: ai, cla-signed

#33857 agent: Fix bug that prevented MCP servers to appear in the settings view
  crates/project/src/context_server_store.rs
  crates/project/src/context_server_store/extension.rs
  crates/project/src/context_server_store/registry.rs
Labels: cla-signed

#33676 Fix panic on inlay split
  crates/editor/src/display_map/inlay_map.rs
Labels: cla-signed

#33874 debugger: Improve performance with large # of output
  crates/debugger_ui/src/session/running/console.rs
  crates/debugger_ui/src/tests/console.rs
  crates/project/src/debugger/session.rs
Labels: cla-signed

#33882 Fix yaml comment indent
  Cargo.lock
  crates/editor/Cargo.toml
  crates/editor/src/editor_tests.rs
  crates/languages/src/yaml/config.toml
Labels: cla-signed

#33883 Default `#[schemars(deny_unknown_fields)] for json-language-server schemas
  Cargo.lock
  crates/language/src/language_settings.rs
  crates/languages/src/json.rs
  crates/settings/src/keymap_file.rs
  crates/settings/src/settings_json.rs
  crates/settings/src/settings_store.rs
  crates/snippet_provider/src/format.rs
  crates/task/src/adapter_schema.rs
  crates/task/src/debug_format.rs
  crates/task/src/task_template.rs
  crates/theme/src/settings.rs
  crates/util/Cargo.toml
  crates/util/src/schemars.rs
  crates/util/src/util.rs
Labels: cla-signed

#33893 Move the `LoadingLabel` component to the UI crate
  crates/agent_ui/src/active_thread.rs
  crates/agent_ui/src/ui.rs
  crates/ui/src/components/label.rs
  crates/ui/src/components/label/loading_label.rs
  crates/ui/src/prelude.rs
Labels: cla-signed

#33917 gemini: Fix issue with builtin tool schemas
  crates/assistant_tools/src/schema.rs
Labels: cla-signed

#33920 agent: Fix context server restart when settings unchanged
  crates/agent_ui/src/agent_configuration/configure_context_server_modal.rs
Labels: cla-signed

#33921 settings: Remove version keys from default settings
  assets/settings/default.json
Labels: cla-signed

#33884 debugger: Fix errors in JavaScript DAP schema
  crates/dap_adapters/src/javascript.rs
Labels: cla-signed

#33876 Sync extension debuggers to remote host
  crates/extension/src/extension_builder.rs
  crates/extension/src/extension_manifest.rs
  crates/extension_host/src/extension_host.rs
  crates/extension_host/src/headless_host.rs
Labels: cla-signed

#33684 Update documentation for tailwindcss language server now that HTML/ERB is it's own file.
  docs/src/languages/ruby.md
Labels: cla-signed

#33872 ruby: Document how to use `erb-formatter` for ERB files
  docs/src/languages/ruby.md
Labels: cla-signed

#33865 emmet: Enable in `HTML/ERB` files
  extensions/emmet/extension.toml
Labels: cla-signed

#33697 Fix path parsing for goto syntax provided by Haskell language server
  crates/util/src/paths.rs
Labels: cla-signed

#33936 Use /usr/bin/env to run bash restart script
  crates/gpui/src/platform/linux/platform.rs
Labels: cla-signed

#33868 debugger: Improve debug console autocompletions
  crates/debugger_ui/src/session/running/console.rs
  crates/editor/src/code_context_menus.rs
  crates/project/src/lsp_store.rs
  crates/project/src/project.rs
  crates/proto/proto/lsp.proto
Labels: cla-signed

#33924 debugger: Fix the JavaScript debug terminal scenario
  crates/assistant_tools/src/terminal_tool.rs
  crates/dap_adapters/src/javascript.rs
  crates/debugger_ui/src/session/running.rs
  crates/extension_host/src/wasm_host/wit.rs
  crates/extension_host/src/wasm_host/wit/since_v0_6_0.rs
  crates/project/src/debugger/locators/cargo.rs
  crates/project/src/project_tests.rs
  crates/project/src/terminals.rs
  crates/proto/proto/debugger.proto
  crates/task/src/shell_builder.rs
  crates/task/src/task.rs
  crates/task/src/task_template.rs
  crates/terminal_view/src/terminal_panel.rs
  crates/vim/src/command.rs
Labels: cla-signed

#33981 Allow remote loading for DAP-only extensions
  crates/debug_adapter_extension/src/extension_locator_adapter.rs
  crates/extension/src/extension_manifest.rs
  crates/extension_host/src/extension_host.rs
  crates/extension_host/src/headless_host.rs
Labels: cla-signed

#33994 project_panel: Add Sticky Scroll
  assets/settings/default.json
  crates/gpui/src/elements/uniform_list.rs
  crates/project_panel/src/project_panel.rs
  crates/project_panel/src/project_panel_settings.rs
  crates/ui/src/components.rs
  crates/ui/src/components/sticky_items.rs
Labels: cla-signed

#33895 copilot: Indicate whether a request is initiated by an agent to Copilot API
  crates/copilot/src/copilot_chat.rs
  crates/language_models/src/provider/copilot_chat.rs
Labels: ai, cla-signed

#33856 agent_ui: Fix disabled context servers not showing in agent setting
  crates/agent_ui/src/agent_configuration.rs
  crates/project/src/context_server_store.rs
Labels: ai, cla-signed

#34004 agent: Show line numbers of symbols when using `@symbol`
  crates/agent_ui/src/context_picker/completion_provider.rs
Labels: cla-signed

#34016 Fix panic with Helix mode changing case
  crates/vim/src/normal/convert.rs
Labels: cla-signed

#34019 keymap_ui: Add ability to edit context
  crates/gpui/src/platform/keystroke.rs
  crates/settings/src/keymap_file.rs
  crates/settings_ui/src/keybindings.rs
Labels: cla-signed

#34005 agent: Send stale file notifications using the project_notifications tool
  assets/settings/default.json
  crates/agent/src/prompts/stale_files_prompt_header.txt
  crates/agent/src/thread.rs
  crates/assistant_tools/src/assistant_tools.rs
  crates/assistant_tools/src/project_notifications_tool.rs
  crates/assistant_tools/src/project_notifications_tool/description.md
  crates/assistant_tools/src/project_notifications_tool/prompt_header.txt
  crates/eval/src/examples/file_change_notification.rs
Labels: cla-signed

#34008 Make `script/generate-license` fail on WARN too
  .github/workflows/ci.yml
  script/generate-licenses
  script/licenses/zed-licenses.toml
Labels: cla-signed

#33932 debugger: Fix issues with restarting sessions
  crates/dap/src/client.rs
  crates/dap/src/transport.rs
  crates/debugger_ui/src/debugger_panel.rs
  crates/debugger_ui/src/tests/attach_modal.rs
  crates/project/src/debugger/session.rs
Labels: cla-signed

#34026 tools: Send stale file notifications only once
  crates/agent/src/thread.rs
  crates/assistant_tool/src/action_log.rs
  crates/assistant_tools/src/project_notifications_tool.rs
Labels: cla-signed

#32908 Edit debug tasks
  .zed/debug.json
  Cargo.lock
  crates/debugger_ui/Cargo.toml
  crates/debugger_ui/src/attach_modal.rs
  crates/debugger_ui/src/debugger_panel.rs
  crates/debugger_ui/src/new_process_modal.rs
  crates/debugger_ui/src/tests/new_process_modal.rs
  crates/editor/src/element.rs
Labels: cla-signed

#34025 agent: Fix max token count mismatch when not using burn mode
  Cargo.lock
  Cargo.toml
  crates/agent/src/thread.rs
  crates/agent/src/tool_use.rs
  crates/agent_ui/src/text_thread_editor.rs
  crates/language_model/src/language_model.rs
  crates/language_models/src/provider/cloud.rs
Labels: cla-signed

#34031 keymap_ui: Add auto-complete for context in keybind editor
  Cargo.lock
  crates/settings/src/base_keymap_setting.rs
  crates/settings/src/keymap_file.rs
  crates/settings/src/settings.rs
  crates/settings_ui/src/keybindings.rs
  crates/welcome/Cargo.toml
  crates/welcome/src/base_keymap_picker.rs
  crates/welcome/src/welcome.rs
  crates/zed/src/main.rs
  crates/zed/src/zed.rs
Labels: cla-signed

#34033 Automatically adjust ANSI color contrast
  assets/settings/default.json
  crates/repl/src/outputs/plain.rs
  crates/terminal/src/terminal_settings.rs
  crates/terminal_view/src/color_contrast.rs
  crates/terminal_view/src/terminal_element.rs
  crates/terminal_view/src/terminal_view.rs
Labels: cla-signed

#34041 agent: Allow clicking on the whole edit file row to trigger review
  crates/agent_ui/src/message_editor.rs
Labels: cla-signed

#34040 agent: Add setting to control edit card expanded state
  assets/settings/default.json
  crates/agent_settings/src/agent_settings.rs
  crates/assistant_tools/src/edit_file_tool.rs
  docs/src/ai/configuration.md
Labels: cla-signed

#33581 editor: Fix diagnostic popovers not being scrollable
  crates/editor/src/hover_popover.rs
Labels: cla-signed

#34061 agent: Add setting to control terminal card expanded state
  assets/settings/default.json
  crates/agent_settings/src/agent_settings.rs
  crates/assistant_tools/src/terminal_tool.rs
  docs/src/ai/configuration.md
Labels: cla-signed

#29145 windows: Add support for SSH
  Cargo.lock
  Cargo.toml
  crates/askpass/Cargo.toml
  crates/askpass/src/askpass.rs
  crates/extension_host/src/extension_host.rs
  crates/extension_host/src/headless_host.rs
  crates/file_finder/src/open_path_prompt.rs
  crates/file_finder/src/open_path_prompt_tests.rs
  crates/net/Cargo.toml
  crates/net/LICENSE-GPL
  crates/net/src/async_net.rs
  crates/net/src/listener.rs
  crates/net/src/net.rs
  crates/net/src/socket.rs
  crates/net/src/stream.rs
  crates/net/src/util.rs
  crates/project/src/debugger/dap_store.rs
  crates/project/src/project.rs
  crates/project/src/terminals.rs
  crates/project/src/worktree_store.rs
  crates/proto/Cargo.toml
  crates/proto/src/typed_envelope.rs
  crates/recent_projects/src/remote_servers.rs
  crates/remote/src/ssh_session.rs
  crates/util/src/paths.rs
  crates/zed/src/main.rs
Labels: cla-signed

#33806 Add support for Nushell in shell builder
  crates/task/src/shell_builder.rs
  crates/task/src/task_template.rs
Labels: cla-signed

#34070 Move Perplexity extension to dedicated repository
  .config/hakari.toml
  Cargo.lock
  Cargo.toml
  extensions/perplexity/Cargo.toml
  extensions/perplexity/LICENSE-APACHE
  extensions/perplexity/README.md
  extensions/perplexity/extension.toml
  extensions/perplexity/src/perplexity.rs
Labels: cla-signed

#34072 nix: Fix generate-licenses failure
  script/generate-licenses
Labels: nix, run-nix

#34092 project panel: Add indent guides for sticky items
  crates/gpui/src/elements/uniform_list.rs
  crates/outline_panel/src/outline_panel.rs
  crates/project_panel/src/project_panel.rs
  crates/storybook/src/stories/indent_guides.rs
  crates/ui/src/components/indent_guides.rs
  crates/ui/src/components/sticky_items.rs
Labels: cla-signed

#33571 vim: Add U to undo last line
  assets/keymaps/vim.json
  crates/editor/src/editor.rs
  crates/vim/src/normal.rs
  crates/vim/src/vim.rs
  crates/vim/test_data/test_undo_last_line.json
  crates/vim/test_data/test_undo_last_line_newline.json
  crates/vim/test_data/test_undo_last_line_newline_many_changes.json
Labels: cla-signed

#34093 helix: Stay in helix normal mode after helix delete
  crates/vim/src/helix.rs
  crates/vim/src/normal.rs
Labels: cla-signed

#33686 vim: Add `:sp[lit] <filename>` and `:vs[plit] <filename>` support
  crates/vim/src/command.rs
Labels: cla-signed

#34102 vim: Implement /n and /c in :s
  crates/editor/src/items.rs
  crates/project/src/search.rs
  crates/search/src/buffer_search.rs
  crates/vim/src/normal/search.rs
  crates/vim/test_data/test_replace_g.json
  crates/vim/test_data/test_replace_n.json
Labels: cla-signed

#33928 editor: Change `drag_and_drop_selection` cursor on delay elapsed + Add `drag_and_drop_selection` delay setting
  assets/settings/default.json
  crates/editor/src/editor.rs
  crates/editor/src/editor_settings.rs
  crates/editor/src/element.rs
  crates/migrator/src/migrations.rs
  crates/migrator/src/migrations/m_2025_07_08/settings.rs
  crates/migrator/src/migrator.rs
  docs/src/configuring-zed.md
Labels: cla-signed

#34112 Wrap back around in context menu properly
  crates/language_tools/src/lsp_tool.rs
  crates/ui/Cargo.toml
  crates/ui/src/components/context_menu.rs
Labels: cla-signed

#34101 Cherry-pick fix for JS debug terminal scenario
  crates/assistant_tools/src/terminal_tool.rs
  crates/dap_adapters/src/javascript.rs
  crates/debugger_ui/src/session/running.rs
  crates/extension_host/src/wasm_host/wit.rs
  crates/extension_host/src/wasm_host/wit/since_v0_6_0.rs
  crates/project/src/debugger/locators/cargo.rs
  crates/project/src/project_tests.rs
  crates/project/src/terminals.rs
  crates/proto/proto/debugger.proto
  crates/task/src/lib.rs
  crates/task/src/shell_builder.rs
  crates/task/src/task_template.rs
  crates/terminal_view/src/terminal_panel.rs
  crates/vim/src/command.rs
Labels: cla-signed

#34118 Fix panic in context server configuration
  crates/agent_ui/src/agent_configuration/configure_context_server_modal.rs
Labels: cla-signed

#34128 evals: Fix bug that prevented multiple turns from displaying
  crates/eval/src/explorer.html
Labels: cla-signed

#34124 editor: Add CollapseAllDiffHunks docs
  docs/src/git.md
Labels: cla-signed

#34138 keymap_ui: Creating keybinds
  crates/settings_ui/src/keybindings.rs
Labels: cla-signed

#34137 Show conflicts in the keymap editor
  crates/settings_ui/src/keybindings.rs
Labels: cla-signed

#34116 Fix inno dir
  script/bundle-windows.ps1
Labels: cla-signed

#34144 Simplify installer by removing a couple pages
  crates/zed/resources/windows/zed.iss
Labels: cla-signed

#33833 git_ui: Support "Open Pull Request" for more platforms
  crates/git_ui/src/remote_output.rs
Labels: cla-signed

#34153 Add button to view dap logs
  crates/debugger_ui/Cargo.toml
  crates/debugger_ui/src/debugger_panel.rs
Labels: cla-signed

#34155 agent: Allow thinking in edit file tool
  crates/assistant_tools/src/edit_agent.rs
Labels: cla-signed

#34160 agent: Make all icons used for tool calls consistent
  assets/icons/clipboard.svg
  assets/icons/file_delete.svg
  assets/icons/search_code.svg
  assets/icons/tool_copy.svg
  assets/icons/tool_delete_file.svg
  assets/icons/tool_diagnostics.svg
  assets/icons/tool_notification.svg
  crates/agent_ui/src/active_thread.rs
  crates/assistant_tools/src/copy_path_tool.rs
  crates/assistant_tools/src/create_directory_tool.rs
  crates/assistant_tools/src/delete_path_tool.rs
  crates/assistant_tools/src/diagnostics_tool.rs
  crates/assistant_tools/src/edit_file_tool.rs
  crates/assistant_tools/src/fetch_tool.rs
  crates/assistant_tools/src/find_path_tool.rs
  crates/assistant_tools/src/grep_tool.rs
  crates/assistant_tools/src/list_directory_tool.rs
  crates/assistant_tools/src/project_notifications_tool.rs
  crates/assistant_tools/src/read_file_tool.rs
  crates/assistant_tools/src/terminal_tool.rs
  crates/assistant_tools/src/thinking_tool.rs
  crates/assistant_tools/src/ui/tool_call_card_header.rs
  crates/assistant_tools/src/web_search_tool.rs
  crates/icons/src/icons.rs
Labels: cla-signed

#34084 gpui: Add `cx.intercept_keystrokes` API to intercept keystrokes before action dispatch
  crates/gpui/src/app.rs
  crates/gpui/src/window.rs
  crates/settings_ui/src/keybindings.rs
Labels: cla-signed

#34163 agent: Fix edit bar's background color when zoomed in
  assets/icons/tool_diagnostics.svg
  assets/icons/tool_read.svg
  assets/icons/tool_web.svg
  crates/agent_ui/src/message_editor.rs
  crates/assistant_tools/src/read_file_tool.rs
  crates/icons/src/icons.rs
Labels: cla-signed

#34166 Hide unused extension types from the extension UI
  crates/extensions_ui/src/extensions_ui.rs
Labels: cla-signed

#34159 Update to acp 0.0.6
  Cargo.lock
  Cargo.toml
  crates/acp/src/acp.rs
  crates/agent_ui/src/acp/thread_view.rs
Labels: cla-signed

#34172 vim: Fix panic when scrolling beyond last line
  crates/vim/src/normal/scroll.rs
Labels: cla-signed

#34123 Change the name of windows CI to reflect what it's doing
  .github/workflows/ci.yml
Labels: cla-signed

#34187 windows: Don't show cmd window when remoting
  crates/remote/src/ssh_session.rs
Labels: cla-signed

#34211 Suggest powershell extension
  crates/extensions_ui/src/extension_suggest.rs
Labels: cla-signed

#34150 Preserve agent message editor unsent text
  crates/agent_ui/src/agent_panel.rs
Labels: cla-signed

#34193 settings_ui: Open keybinding editing modal on mouse double click
  crates/settings_ui/src/keybindings.rs
Labels: cla-signed

#33902 docs: Add GitHub Copilot Enterprise configuration example
  docs/src/ai/configuration.md
  docs/src/ai/edit-prediction.md
Labels: ai, cla-signed

#34198 Remove default shell breadcrumbs on windows
  crates/terminal/src/terminal.rs
Labels: cla-signed

#34218 Remove redundant `autoscroll_horizontally` during editor prepaint
  crates/editor/src/element.rs
Labels: cla-signed

#34222 language_models: Refresh the list of models when the LLM token is refreshed
  crates/language_models/src/provider/cloud.rs
Labels: cla-signed

#34205 settings_ui: Inform about keybind conflicts in modal
  crates/settings_ui/src/keybindings.rs
Labels: cla-signed

#34241 ci: Skip ci.yml checks for script/update_top_ranking_issues
  .github/workflows/ci.yml
Labels: cla-signed

#34248 keymap_ui: Add ability to delete user created bindings
  crates/settings/src/keymap_file.rs
  crates/settings/src/settings_json.rs
  crates/settings_ui/src/keybindings.rs
Labels: cla-signed

#34250 Fix screenshare sources error handling, `is_sharing_screen() == false` on error
  crates/call/src/call_impl/room.rs
Labels: cla-signed

#34096 git: Intercept signing prompt from GPG when committing
  Cargo.lock
  crates/askpass/Cargo.toml
  crates/askpass/src/askpass.rs
  crates/fs/src/fake_git_repo.rs
  crates/git/Cargo.toml
  crates/git/src/repository.rs
  crates/git_ui/src/git_panel.rs
  crates/project/src/git_store.rs
  crates/proto/proto/git.proto
Labels: cla-signed

#34255 lsp tool: Make "Restart All Servers" always visible
  crates/language_tools/src/lsp_tool.rs
Labels: cla-signed

#34238 Don't apply contrast adjustment to decorative chars
  crates/terminal_view/src/terminal_element.rs
Labels: cla-signed

#34284 keymap_ui: Only show conflicts between user bindings
  crates/settings_ui/src/keybindings.rs
Labels: cla-signed

#34291 keymap_ui: Ensure keymap UI opens in local workspace
  crates/settings_ui/src/keybindings.rs
Labels: cla-signed

#34297 git: Change merge conflict button labels
  crates/git_ui/src/conflict_view.rs
Labels: cla-signed

#34299 Improve thread message history
  crates/agent_ui/src/acp.rs
  crates/agent_ui/src/acp/message_history.rs
  crates/agent_ui/src/acp/thread_view.rs
  crates/agent_ui/src/agent_panel.rs
Labels: cla-signed

#34295 editor: Fix scrolling stuttering at the top of multibuffers
  crates/editor/src/scroll.rs
Labels: cla-signed

#34272 Add licenses.md for Windows build
  script/bundle-windows.ps1
  script/generate-licenses.ps1
Labels: cla-signed, run-bundling

#34228 Reduce number of snapshots and notifies during editor scrolling
  crates/editor/src/element.rs
  crates/editor/src/scroll.rs
  crates/editor/src/scroll/autoscroll.rs
Labels: cla-signed

#34305 Truncate multi-line debug value hints
  crates/debugger_ui/src/tests/inline_values.rs
  crates/editor/src/editor.rs
  crates/project/src/debugger/dap_store.rs
Labels: cla-signed

#34311 DAP log view improvements
  crates/debugger_tools/src/dap_log.rs
  crates/debugger_ui/src/session.rs
Labels: cla-signed

#34318 keymap_ui: Support unbinding non-user defined keybindings
  Cargo.lock
  crates/settings/src/keymap_file.rs
  crates/settings_ui/Cargo.toml
  crates/settings_ui/src/keybindings.rs
Labels: cla-signed

#34312 keymap_ui: Dual-phase focus for keystroke input
  crates/settings_ui/src/keybindings.rs
Labels: cla-signed

#33475 Recall empty, unsaved buffers on app load
  crates/editor/src/items.rs
Labels: cla-signed

#34306 Revert "git: Intercept signing prompt from GPG when committing"
  Cargo.lock
  crates/askpass/Cargo.toml
  crates/askpass/src/askpass.rs
  crates/fs/src/fake_git_repo.rs
  crates/git/Cargo.toml
  crates/git/src/repository.rs
  crates/git_ui/src/git_panel.rs
  crates/project/src/git_store.rs
  crates/proto/proto/git.proto
Labels: cla-signed

#34253 agent: Fix crash with pathological fetch output
  crates/assistant_tools/src/fetch_tool.rs
  crates/html_to_markdown/src/markdown_writer.rs
Labels: cla-signed

#34334 Remove remaining plugin-related language server adapters
  crates/language/src/language_registry.rs
Labels: cla-signed

#34328 debugger: Fix endless restarts when connecting to TCP adapters over SSH
  Cargo.lock
  crates/collab/Cargo.toml
  crates/collab/src/tests/remote_editing_collaboration_tests.rs
  crates/dap/src/adapters.rs
  crates/dap/src/client.rs
  crates/dap/src/transport.rs
  crates/debugger_ui/src/session.rs
  crates/debugger_ui/src/session/running.rs
Labels: cla-signed

#34340 Return back the guards when goto targets are queried for
  crates/project/src/project.rs
Labels: cla-signed

#33959 debugger: Fix correctly determine replace range for debug console completions
  crates/debugger_ui/src/session/running/console.rs
Labels: cla-signed

#34296 git: Handle shift-click to stage a range of entries in the panel
  assets/keymaps/default-linux.json
  assets/keymaps/default-macos.json
  assets/keymaps/vim.json
  crates/fs/src/fake_git_repo.rs
  crates/git/src/git.rs
  crates/git_ui/src/git_panel.rs
  crates/ui/src/components/toggle.rs
Labels: cla-signed

#34362 debugger: Allow users to shutdown debug sessions while they're booting
  crates/debugger_ui/src/debugger_panel.rs
  crates/debugger_ui/src/session/running.rs
  crates/project/src/debugger/session.rs
  crates/terminal/src/pty_info.rs
  crates/terminal/src/terminal.rs
Labels: cla-signed

#34367 project_panel: Fix sticky items horizontal scroll and hover propagation
  crates/project_panel/src/project_panel.rs
  crates/ui/src/components/sticky_items.rs
Labels: cla-signed

#34387 keymap_ui: Dismiss context menu less frequently
  crates/settings_ui/src/keybindings.rs
Labels: cla-signed

#34380 linux: Add `file_finder::Toggle` key binding
  assets/keymaps/default-linux.json
Labels: cla-signed

#34389 project_panel: Do not render a single sticky entry when scrolled all the way to the top
  crates/project_panel/src/project_panel.rs
Labels: cla-signed

#34388 languages: Add JS/TS generator functions to outline
  crates/languages/src/javascript/outline.scm
  crates/languages/src/tsx/outline.scm
  crates/languages/src/typescript.rs
  crates/languages/src/typescript/outline.scm
Labels: cla-signed

#34400 emacs: Fix cmd-f not working in Terminal
  assets/keymaps/default-macos.json
Labels: cla-signed

#34403 Remove unused KeycodeSource
  crates/gpui/src/platform/linux/platform.rs
  crates/gpui/src/platform/linux/wayland/client.rs
  crates/gpui/src/platform/linux/x11/client.rs
Labels: cla-signed

#34278 vim: Add missing normal mode binding for signature help overload
  assets/keymaps/vim.json
Labels: cla-signed

#34391 debugger: A support for data breakpoint's on variables
  crates/debugger_ui/src/debugger_ui.rs
  crates/debugger_ui/src/session/running/breakpoint_list.rs
  crates/debugger_ui/src/session/running/memory_view.rs
  crates/debugger_ui/src/session/running/variable_list.rs
  crates/project/src/debugger/dap_command.rs
  crates/project/src/debugger/session.rs
Labels: cla-signed

#34425 Add test for running `Close Others` on an inactive item
  crates/workspace/src/pane.rs
Labels: cla-signed

#33067 editor: Improve minimap performance
  crates/agent_ui/src/inline_assistant.rs
  crates/agent_ui/src/text_thread_editor.rs
  crates/diagnostics/src/diagnostic_renderer.rs
  crates/diagnostics/src/diagnostics.rs
  crates/editor/src/display_map.rs
  crates/editor/src/display_map/block_map.rs
  crates/editor/src/editor.rs
  crates/editor/src/editor_tests.rs
  crates/editor/src/element.rs
  crates/git_ui/src/conflict_view.rs
  crates/repl/src/session.rs
  docs/src/development.md
Labels: cla-signed

#33973 Fix border and minimap flickering on pane split
  crates/workspace/src/workspace.rs
Labels: cla-signed

#34450 extension_cli: Copy over snippet file when bundling extensions
  crates/extension_cli/src/main.rs
Labels: cla-signed

#34437 Refine keymap UI design
  Cargo.lock
  assets/icons/play_filled.svg
  crates/icons/src/icons.rs
  crates/settings_ui/Cargo.toml
  crates/settings_ui/src/keybindings.rs
  crates/ui_input/src/ui_input.rs
Labels: cla-signed

#33995 Add severity argument to GoToDiagnostic actions
  assets/keymaps/default-linux.json
  assets/keymaps/default-macos.json
  crates/diagnostics/src/diagnostics_tests.rs
  crates/diagnostics/src/items.rs
  crates/editor/src/actions.rs
  crates/editor/src/editor.rs
  crates/editor/src/editor_tests.rs
  crates/project/src/project_settings.rs
  crates/project_panel/src/project_panel.rs
  crates/vim/src/command.rs
  crates/zed/src/zed/app_menus.rs
  crates/zed/src/zed/quick_action_bar.rs
Labels: cla-signed

#34407 gpui: Reduce manual shifting & other minor improvements
  crates/docs_preprocessor/src/main.rs
  crates/gpui/src/action.rs
  crates/gpui/src/app.rs
  crates/gpui/src/color.rs
  crates/zed/src/main.rs
Labels: cla-signed

#34464 keymap_ui: Limit length of keystroke input and hook up actions
  assets/keymaps/default-linux.json
  assets/keymaps/default-macos.json
  crates/settings_ui/src/keybindings.rs
  crates/zed/src/zed.rs
Labels: cla-signed

#34423 keymap_ui: Add column for conflict indicator and edit button
  crates/settings_ui/src/keybindings.rs
Labels: cla-signed
